fluentassertions/fluentassertions

- FluentAssertions.Core/Collections/GenericCollectionAssertions.cs
- FluentAssertions.Core/Common/ExpressionExtensions.cs
- FluentAssertions.Core/Common/TypeExtensions.cs
- FluentAssertions.Core/Core.csproj
- FluentAssertions.Core/Equivalency/AllPublicFieldsSelectionRule.cs
- FluentAssertions.Core/Equivalency/EquivalencyAssertionOptions.cs
- FluentAssertions.Core/Equivalency/EquivalencyAssertionOptionsBase.cs
- FluentAssertions.Core/Equivalency/FieldSelectedMemberInfo.cs
- FluentAssertions.Core/Equivalency/IEquivalencyAssertionOptions.cs
- FluentAssertions.Core/Equivalency/ISelectedMemberInfo.cs
- FluentAssertions.Core/Equivalency/MatchAllOrderingRule.cs
- FluentAssertions.Core/Equivalency/MustMatchByNameRule.cs
- FluentAssertions.Net40/ObjectAssertionsExtensions.cs
- FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
- FluentAssertions.Shared.Specs/CollectionEquivalencySpecs.cs
- FluentAssertions.Shared.Specs/DictionaryEquivalencySpecs.cs
- FluentAssertions.Shared.Specs/FormatterSpecs.cs
- FluentAssertions.Shared.Specs/ObjectAssertionSpecs.cs
This should resolve Issue #22.
In addition to including Fields in `ShouldBeEquivalentTo` it also makes the Binary and XML Serialization assertions check fields.
Not sure if there is any etiquette or practices around this, but I did not include the full history of my work thinking this was cleaner.
> Include fields in equivalency assertions

- FluentAssertions.Core/Common/ExpressionExtensions.cs
- FluentAssertions.Core/Equivalency/GenericDictionaryEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/GenericEnumerableEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/ShouldAllBeEquivalentToHelper.cs
- FluentAssertions.Shared.Specs/CollectionEquivalencySpecs.cs
- FluentAssertions.sln.DotSettings
Correct issues wherein ShouldAllBeEquivalentTo would lack the default SelectionRule and would apply the selection rules in the revere order.  This is the issue reported by #194.
> Fix issue 194

- FluentAssertions.Core/Equivalency/EquivalencyAssertionOptions.cs
- FluentAssertions.Core/Equivalency/EquivalencyAssertionOptionsBase.cs
- FluentAssertions.Net40/ObjectAssertionsExtensions.cs
- FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
- FluentAssertions.Shared.Specs/CollectionEquivalencySpecs.cs
- FluentAssertions.Shared.Specs/DictionaryEquivalencySpecs.cs
Switches to a more granular API for specifying runtime/declared typing and inclusion of properties/fields in ShouldBeEquivalentTo.
The thinking is this API will work better with the global configuration being introduced for #137.  The idea being global configuration could specify `ExcludingFields()` and a test just wanting runtime typing only needs to specify `RespectingRuntimeTypes()` and not need to possibly override the `ExcludingFields()` configuration.
> Different API for including fields

- FluentAssertions.Core/Formatting/DateTimeOffsetValueFormatter.cs
- FluentAssertions.Shared.Specs/DateTimeOffsetValueFormatterSpecs.cs
Right now comparing two DateTimeOffset with different time zones might lead to an unclear error message:
var expected = new DateTimeOffset(2013, 1, 10, 2, 0, 0, 0, TimeSpan.FromHours(5));
var actual   = new DateTimeOffset(2013, 1, 10, 2, 0, 0, 0, TimeSpan.FromHours(6));  // Different offset
actual.Should().Be(expected);
results in:
Expected date and time to be <2013-01-10 02:00:00>, but found <2013-01-10 02:00:00>.
This error message seems to be saying that the values match but the test has still failed. To make the difference more clear I've added timezone offset information into DateTimeOffset formatting code.
To avoid wider changes, the offset is not included if it matches the current timezone offset. The test *When_a_DateTime_is_used_it_should_format_the_same_as_a_DateTimeOffset* was …
> Include timezone offset in DateTimeOffset display

- FluentAssertions.Core/Core.csproj
- FluentAssertions.Core/TypeEnumerableExtensions.cs
- FluentAssertions.Core/TypeExtensions.cs
- FluentAssertions.Shared.Specs/TypeEnumerableExtensionsSpecs.cs
This is done on the premise that these methods are rather useful; but, hard to find.
These extension methods are still on a fairly specialized type so they  should not cause much of a pollution problem.  Even then these might be fairly common things to want to do on that type so I still think it would not be pollution.
> New extension methods to make filtering of `Type`s functionality more accessible

- FluentAssertions.Core/Primitives/ReferenceTypeAssertions.cs
- FluentAssertions.Core/Types/TypeAssertions.cs
- FluentAssertions.Shared.Specs/CollectionAssertionSpecs.cs
- FluentAssertions.Shared.Specs/ObjectAssertionSpecs.cs
- FluentAssertions.Shared.Specs/TypeAssertionSpecs.cs
In the absence of this new hiding definition, FA would try to assert the Type, `Type`, was assignable to the type.  An assertion having no real value.
This also updates the formatting on the specs of the hidden method.
This also corrects a slight inaccuracy in the failure message of the hidden method.
> Adds `BeAssignableTo` implementation for `Type` objects.

- FluentAssertions.Core/Execution/AssertionScope.cs
- FluentAssertions.Core/Execution/CollectingAssertionStrategy.cs
- FluentAssertions.Shared.Specs/AssertionScopeSpecs.cs
- FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
Corrects an issue wherein true duplicates of failure messages were being reported to users by `ShouldBeEquivalentTo` when the graph contained an Enumerable.
By 'true duplicates', I mean multiple reports of the same failure pertaining to the same member produced by a single check.  This is distinct from the previously removed "duplicates" where it was a distinct failure that produced the same failure message.
___
I found the fix a little surprising.  I did not trace history far enough to see why the code was added in the first place.  Since no tests broke by its removal I am thinking it is probably okay.  Based on how `AssertionScope.Dispose` is implemented I do not see how this removal would be an issue.
This does change the return from `Discard`, but that is what is fixing this bug for …
> Fixes duplicate failure messages in ShouldBeEquivalentTo

- FluentAssertions.Core/AssertionOptions.cs
- FluentAssertions.Core/Collections/CollectionAssertions.cs
- FluentAssertions.Core/Common/TypeExtensions.cs
- FluentAssertions.Core/Core.csproj
- FluentAssertions.Core/Equivalency/AssertionRuleEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/DictionaryEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/EnumEqualityStep.cs
- FluentAssertions.Core/Equivalency/EnumerableEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/EquivalencyAssertionOptionsBase.cs
- FluentAssertions.Core/Equivalency/EquivalencyValidator.cs
- FluentAssertions.Core/Equivalency/GenericDictionaryEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/GenericEnumerableEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/IEquivalencyAssertionOptions.cs
- FluentAssertions.Core/Equivalency/ObjectReference.cs
- FluentAssertions.Core/Equivalency/ObjectTracker.cs
- FluentAssertions.Core/Equivalency/ReferenceEqualityEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/RunAllUserStepsEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/ShouldAllBeEquivalentToHelper.cs
- FluentAssertions.Core/Equivalency/SimpleEqualityEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/StringEqualityEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/StructuralEqualityEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/SystemTypeEqualityEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/TryConversionEquivalencyStep.cs
- FluentAssertions.Core/Equivalency/ValueTypeEquivalencyStep.cs
- FluentAssertions.Core/EquivalencyStepCollection.cs
- FluentAssertions.Shared.Specs/AssertionOptionSpecs.cs
- FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
- FluentAssertions.Shared.Specs/CollectionAssertionSpecs.cs
- FluentAssertions.sln.DotSettings
- Shared/AssertionExtensions.cs
Introduced an API to change the rules for evaluating whether a type should be treated as having value semantics, either for a single structural equality comparison or globally.
> 134 central config

- FluentAssertions.Core/Equivalency/EquivalencyAssertionOptionsExtentions.cs
This would be useful for anyone writing their own IEquivalencyStep
> Makes EquivalencyAssertionOptionsExtentions.GetSubjectType public

- FluentAssertions.Core/Execution/GivenSelector.cs
(This is my first github pull request, so please bear with me)
I was unable to compile the develop branch in 26be9f6295d9b3ab6cbca8b4ee800fd9ca5674ae due to overload resolution on FailWith.
> Resolve FailWith overload resolution when only constant-string is passed

- FluentAssertions.Net40/Net40.csproj
- FluentAssertions.Shared.Specs/EventAssertionSpecs.cs
- Shared/Execution/AssertionFailedException.cs
Currently the AssertionFailedException is missing a serializable constructor. Therefore it throws an error when deserializing the exception.
See: http://stackoverflow.com/questions/94488/what-is-the-correct-way-to-make-a-custom-net-exception-serializable
Addition to implement #214 properly
Clean PR of #262
> Add serialization constructor for AssertionFailedException

- Src/Core/Collections/CollectionAssertions.cs
- Src/Core/Collections/SelfReferencingCollectionAssertions.cs
- Tests/FluentAssertions.Shared.Specs/CollectionAssertionSpecs.cs
Sometimes it is required to verify collection of objects that have no public constructor and not abstracted by interface, so there is no way to create an expected collection of objects of exactly the same type. In this case, it is useful to compare it with collection of anonymous objects that contain all required data:
```c#
IList<TypeWithPrivateCtor> actual = GetActual();
var expected = new [] 
{
new { P1 = "a", P2 = 0 },
new { P1 = "b", P2 = 1 },
new { P1 = "c", P2 = 2 },
}
actual.Should().Equal(expected, (a, e) => a.P1 == e.P1 && a.P2 == e.P2);
```
> Allow SelfReferencingCollectionAssertions to compare collections of different types using predicate

- Src/Core/Collections/GenericDictionaryAssertions.cs
GenericDictionaryAssertions<,>.ContainKeys(..) had a non-optional 'because' argument and
so did .ContainValuesAndWhich(..) - more precisely, the later for 'reasonArgs'. Both were/are inconsistent with the rest (looked like an oversight - these two parameters are used optionally / as params[] everywhere else).
Cheers,
-J
> Fixed (non-)optional 'because' and 'reasonArgs' for Dictionaries

- FluentAssertions.sln
- FluentAssertions.sln.DotSettings
- Src/Core/Core.projitems
- Src/Core/Equivalency/Selection/ExcludeMemberByPathSelectionRule.cs
- Src/Core/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
- Src/Core/Equivalency/Selection/MemberPath.cs
- Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
> Ensured that ShouldBeEquivalentTo will only include properties which name is an exact match.

- Src/Core/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions.Net40/Common/ProvidePlatformServices.cs
- Src/FluentAssertions.Net40/Net40.csproj
- Src/FluentAssertions.Net40/Xml/XmlAssertionExtensions.cs
- Src/FluentAssertions.Net40/Xml/XmlNodeAssertions.cs
- Src/FluentAssertions.Net40/Xml/XmlNodeFormatter.cs
- Src/FluentAssertions.Net40/Xml/XmlReaderValidator.cs
- Src/FluentAssertions.Net45/Net45.csproj
- Tests/FluentAssertions.Net40.Specs/Net40.Specs.csproj
- Tests/FluentAssertions.Net40.Specs/XmlNodeAssertionSpecs.cs
- Tests/FluentAssertions.Net45.Specs/Net45.Specs.csproj
- Tests/FluentAssertions.Shared.Specs/ReferenceTypeAssertionsSpecs.cs
XmlDocument/XmlElement assertions as discussed in #354. 
Only available in .NET4.0 and .NET4.5 projects, as those are the only that appears to have XmlDocument support. The real comparison work is done in the XmlReaderValidator which I think only references stuff available on all platforms, so it should be possible to move to a shared library and reuse for XDocument/XElement comparisons (they can create an XmlReader too).
The comparison is done for each xml node in document order. A basic path to the current element is included in the error message to make it easier to track down where the difference is.
Example of assertion messages produced:
> Expected local name of element at "/xml/child" to be "expected" because we want to test the failure message, but found "subject".
> Expected …
> Xml node assertions

- Src/Core/EquivalencyStepCollection.cs
- Tests/FluentAssertions.Shared.Specs/ExtensibilityRelatedEquivalencySpecs.cs
> Ensured that user equivalency steps run before all the built-in steps.

- Src/FluentAssertions.Net40/Net40.csproj
- Src/FluentAssertions.Net45/Net45.csproj
- Src/Shared/Shared.projitems
- Src/Shared/Xml/XDocumentAssertions.cs
- Src/Shared/Xml/XElementAssertions.cs
- Src/Shared/Xml/XmlReaderValidator.cs
- Tests/FluentAssertions.Net40.Specs/XmlNodeAssertionSpecs.cs
- Tests/FluentAssertions.Shared.Specs/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Shared.Specs/XElementAssertionSpecs.cs
Also fixed a bug where the location for xml comparisons was incorrect after a selfclosed <xml /> element had been compared.
The tests for `XDocument/XElement.Should().BeEquivalent()` are not very covering. They basically just checks that semantical equivalency is used. The tests for `XmlNode` are much more extensive, as those are what I used to test the `XmlReaderValidator` implementation. How do you want the tests? I can think of three options.
1. Kept as it is
2. Also do full tests/specs for `XDocument/XElement` (will be a lot of copied tests)
3. Move the detailed tests to a separate class that tests `XmlReaderValidator` directly
> Semantic (Not)BeEquivalent for XDocument/XElement

- Src/FluentAssertions.Net40/Net40.csproj
- Src/FluentAssertions.Net40/Xml/XmlAssertionExtensions.cs
- Src/FluentAssertions.Net40/Xml/XmlElementAssertions.cs
- Src/FluentAssertions.Net40/Xml/XmlNodeAssertions.cs
- Src/FluentAssertions.Net40/Xml/XmlNodeAssertionsofTSubjectTAssertions.cs
- Src/FluentAssertions.Net45/Net45.csproj
- Tests/FluentAssertions.Net40.Specs/Net40.Specs.csproj
- Tests/FluentAssertions.Net40.Specs/XmlElementAssertionSpecs.cs
- Tests/FluentAssertions.Net45.Specs/Net45.Specs.csproj
- Follows the principles of the corresponding methods on XDocument/XElement.
- It doesn't make sense to add these on XmlDocument as the DocumentElement
is an explicit property there (XDocument behaves implicitly as the document
XElement).
- Named the test HaveInnerText because the Value property is always null on XmlElements.
> HaveInnerText, HaveElement and HaveAttribute for XmlElement

- Src/Core/Common/CSharpAccessModifierExtensions.cs
- Src/Core/Core.projitems
- Src/Core/Equivalency/FieldSelectedMemberInfo.cs
- Src/Core/Equivalency/PropertySelectedMemberInfo.cs
- Src/Core/Equivalency/SelectedMemberInfo.cs
- Src/Core/Equivalency/SubjectInfoExtensions.cs
- Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
I added properties to get the access modifiers of the getter and setter on `SelectedMemberInfo`.
For field members it uses the same access modifier for both the getter and setter.
```csharp
CSharpAccessModifier GetAccessModifier { get; }
// and
CSharpAccessModifier SetAccessModifier { get; }
```
Also added extension methods on `ISubjectInfo` for checking the access modifier of the setter or getter in a fluent manner:
- `subjectInfo.WhichSetterHas(CSharpAccessModifier)`
- `subjectInfo.WhichSetterDoesNotHave(CSharpAccessModifier)`
- `subjectInfo.WhichGetterHas(CSharpAccessModifier)`
- `subjectInfo.WhichGetterDoesNotHave(CSharpAccessModifier)`
Usage sample
```csharp
subject.ShouldBeEquivalentTo(expected, config =>
config.Excluding(ctx => ctx.WhichGetterHas(CSharpAccessModifier.Internal) || …
```
> Added properties for the access modifier of getter and setter on SelectedMemberInfo

- Src/Core/Collections/CollectionAssertions.cs
- Src/Core/Collections/GenericDictionaryAssertions.cs
- Src/Core/Collections/NonGenericCollectionAssertions.cs
- Src/Core/Collections/SelfReferencingCollectionAssertions.cs
- Src/Core/Collections/StringCollectionAssertions.cs
- Tests/FluentAssertions.Shared.Specs/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
- Tests/FluentAssertions.Shared.Specs/GenericCollectionAssertionsSpecs.cs
- Tests/FluentAssertions.Shared.Specs/GenericDictionaryAssertionSpecs.cs
This should fix issue https://github.com/dennisdoomen/FluentAssertions/issues/426. I also added more NotContain methods to align Contain and NotContain overloads more.
Being completely new to Git and Github, just let me know if I need to change something
> Not contains fix

- Src/Core/Collections/CollectionAssertions.cs
- Src/Core/Collections/GenericCollectionAssertions.cs
- Tests/FluentAssertions.Shared.Specs/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Shared.Specs/GenericCollectionAssertionsSpecs.cs
Create overloads of `.Should().BeInAscendingOrder(...)` and all related methods, specifically in the `CollectionAssertions` and `GenericCollectionAssertions` classes. Custom `IComparer<T>` objects can now be passed in.
Unit tests are included for the new methods. It also looks like my VS chopped off a bunch of trailing whitespace chars; hope that's not a problem. :)
> Add collection assertion overloads for IComparer<T>

- Src/Core/Equivalency/GenericDictionaryEquivalencyStep.cs
- Tests/FluentAssertions.Shared.Specs/DictionaryEquivalencySpecs.cs
fail with a good error message (rather than NullRef) if comparing Dictionary to null
> fix for issue #468; bug in how dictionaries are compared. 

- Src/Core/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
- Src/Core/Equivalency/Selection/MemberPath.cs
- Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
> Ensured that using the Including construct always starts at the root.

- Src/Core/Primitives/ReferenceTypeAssertions.cs
- Src/Core/Types/TypeAssertions.cs
- Src/FluentAssertions.Core.Dotnet/ReflectionExtensions.cs
- Tests/FluentAssertions.Shared.Specs/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Shared.Specs/TypeAssertionSpecs.cs
Asserting _subject object or Type should be assignable to given (non-generic) type parameter_. 
- `ReferenceTypeAssertions` new overload for BeAssignableTo accepting (non-generic) type parameter
- `TypeAssertions` new overload for BeAssignableTo accepting (non-generic) type parameter
- Testing for overload implementation
I can add the samples under [Basic Assertions](https://github.com/dennisdoomen/FluentAssertions/wiki#basic-assertions) and [Type, Method and Property Assertions](https://github.com/dennisdoomen/FluentAssertions/wiki#type-method-and-property-assertions) if necessary.
_ReferenceTypeAssertion.BeAssignableTo_ overload does not return _AndWhichContraint_ since the generic type parameter is not present. Instead of returning and-which contraint with object, it returns …
> Non-generic BeAssignableTo enhancement

- FluentAssertions.sln
- Src/FluentAssertions.Dotnet/Dotnet.csproj
- Src/FluentAssertions.Dotnet/Execution/TestFrameworkProvider.cs
- Src/FluentAssertions.Net40/Execution/MSTestFrameworkV2.cs
- Src/FluentAssertions.Net40/Execution/TestFrameworkProvider.cs
- Src/FluentAssertions.Net40/Net40.csproj
- Src/FluentAssertions.Net45/Net45.csproj
- Tests/TestFrameworks/MSTestV2.Specs/FrameworkSpecs.cs
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSTestV2.Specs/Properties/AssemblyInfo.cs
- Tests/TestFrameworks/MSTestV2.Specs/packages.config
Adding in support for MSTest V2 which is the next version of the MSTest framework as detailed [here](https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/17/taking-the-mstest-framework-forward-with-mstest-v2/). It supports .Net 4.5+, UWP and dotnet core.
> MSTest V2 support

- Src/Core/Core.projitems
- Src/Core/Primitives/StringAssertions.cs
- Src/Shared/Shared.shproj
- Tests/FluentAssertions.Shared.Specs/StringAssertionSpecs.cs
Add Regex annotations for `Should().MatchRegex()` and `Should().NotMatchRegex()` to get syntax highlighting and error analysis of regular expressions.
> ReSharper Regex Annotations

- Src/Core/AssertionOptions.cs
- Src/Core/Equivalency/EquivalencyValidator.cs
- Tests/FluentAssertions.Shared.Specs/ObjectAssertionSpecs.cs
> Ensures FA doesn't treat standard .NET exception types as value types.

- Src/Core/Formatting/TimeSpanValueFormatter.cs
- Tests/FluentAssertions.Shared.Specs/TimeSpanFormatterSpecs.cs
Currently if an assertion dealing with a sub 1 millisecond timespan fails,
the error message describes the timespan as 'default'. Which makes it hard
to figure out what is going on.
This commit extends the timespan formatter to support timespans between
0.1 microseconds and 1 millisecond.
> Support timespans shorter than 1 millisecond

- Src/Shared/PropertyChangedSourceExtensions.cs
- Tests/FluentAssertions.Shared.Specs/EventAssertionSpecs.cs
Fork contains two branches: **master** and **alternative-idea**.
1. Master. Contains more clear and simple code but has one (minor?) issue. If delegate behind event has repeated generic types (like ```Action<string, string>```), assertion will be successful if expected value is present in ANY of the parameters (first string or second string).
2. Alternative-idea. Contains more strict but less pretty for end user implementation. The idea is to accept ```params``` of predicates in ```WithArgs```. So, if you need strict assertions for two input strings, you can specify two predicates, each corresponding to particular parameter in order. The one drawback is about the case when you wish to skip first N parameters and then assert the next. In this case you should specify ```null``` or ```args …
```
> Fix for issue #30: Allow not EventArgs based event handlers

- index.md
A really minor pull request correcting an inopportune typo
> Corrects spelling of 'repository'

- index.md
Hi all,
I know FV is under heavy refactoring but I wanted to submit a minor fix for the home page; I won't be offended if you reject. :) 
The home page current has an example where a list of 3 items is created but the example expects four. The explanation reads "because we thought we added three items", but it really means "because we thought we added four items." This will make the failure message make more sense.
Would have submitted an issue first, but this seemed minor enough. Thanks for your consideration!
> FluentAssertions.com example -- correction for clarity

- Src/Core/Common/TypeExtensions.cs
- Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
- Tests/FluentAssertions.Shared.Specs/TypeAssertionSpecs.cs
Fixes #540 
Unit tests were added to test `HaveDefaultConstructor` with classes that have a static constructor.
> Exclude static constructors when get a constructor by its parameters.

- CONTRIBUTING.md
Update CONTRIBUTING.md to reflect the change of documentation location since it is now on the website rather than the wiki.
Also, fixed another the example specs url since I noticed it while I was there.
> Update CONTRIBUTING.md to reflect the change of documentation location

- Src/Core/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
The code documentation for SelfReferenceEquivalencyAssertionOptions,WithoutStrictOrderingFor 
was wrong.
It implied that order was evaluated.
It seems like a copy paste error as the exact same docComment appears on  WithStrictOrderingFor.
The DocComment is corrected so it now reflects the fact that ordering is ignored
> DocComment wrong for WithoutStrictOrderingFor

- docs/_config.yml
Could be useful or at least interesting.  Since the content is no longer on the wiki, GitHub's analytics no longer covers this.  I also think there may be some integration possible with the advertisement if you wanted to link them.
> Add Google Analytics to website

- Src/Core/Collections/CollectionAssertions.cs
- Src/Core/Execution/MessageBuilder.cs
- Src/Core/Specialized/ExceptionAssertions.cs
- Tests/FluentAssertions.Shared.Specs/AssertionScopeSpecs.cs
- Tests/FluentAssertions.Shared.Specs/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
This PR resolve issues with curly braces in assertion scopes.
When providing single braces ( {} ) string.Format() would fail.
When providing double braces ( {{}} ) and skipping string.Format() because no args were provided, the double braces would not be undoubled.
This is especially annoying when working with JSON.
> Fix issues with curly braces

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
- docs/documentation.md
* x] The code complies with the [Coding Guidelines for C# 3.0, 4.0 and 5.0](http://www.csharpcodingguidelines.com/)/.
This closes #597
> Add NotHaveSameCount

- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/Shared.Specs/ObjectAssertionSpecs.cs
- Tests/Shared.Specs/TypeAssertionSpecs.cs
- docs/documentation.md
I would say it's done, but I'm unsure about one thing.
Like `BeAssignableTo<T>` returns an `AndWhichConstraint` where `Which` points to casted type, I wanted `NotBeAssignableTo` to return the Subject as an `AndConstraint` for chaining. 
But as the type is lost in `ObjectAssertions Should(this object actualValue)` `NotAssignableTo<T>().And` is of type `object``.
This gives some ugly code, where one needs to cast `someObject` back to `Exception` for chaining.
```csharp`
var someObject = new Exception("Actual Message");
Action act = () => someObject.Should().NotBeAssignableTo<DummyImplementingClass>()
.And.Subject.Should().BeOfType<Exception>()
.Which.Message.Should().Be("Other Message");
``` 
Is there a way to retain the type of `someObject`,
or would it just be so confusing that it should …
> Not be assignable to

- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
> typo in return summary of BeAssignableTo

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/Shared.Specs/TypeAssertionSpecs.cs
- Tests/Shared.Specs/TypeExtensionsSpecs.cs
> Add [Not]Have{Implicit,Explicit}ConversionOperator

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
> allowInfiniteRecursion set twice in constructor

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
When asserting that two collections are not equal, we can give a better error descriptions when the collections references the same object and therefore _should_ violate the assertion that the collections are not equal.
This of course relies on the assumption, that two collection which references the same object are equal.
This is not a universal truth, as the example below illustrates.
```csharp
int i = 0;
var sequence1 = Enumerable.Range(1, 10).Select(e => { i++; return e * i; });
var sequence2 = sequence1;
ReferenceEquals(sequence1, sequence2) // true
Enumerable.SequenceEqual(sequence1, sequence2) // false
```
If FA wants to support lazy generated sequences in this way, the reference check could be restricted to `I[ReadOnly]Collection`
This is consistent with the behavior of …
> Fail fast NotEqual if identical references

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
This PR changes the failure message when OnlyHaveUniqueItems fails.
Instead of only reporting the first duplicate key, it now reports all duplicate keys.
> Report all duplicate keys on OnlyHaveUniqueItems

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
When asserting using `NotContainNulls` the current behavior is to only report the first index of a null item.
This PR changes that to report indices of all null items instead.
> Report all indices offending NotContainNulls

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/Shared.Specs/GenericCollectionAssertionsSpecs.cs
Currently one has to do a projection on e.g. a property before using certain assertions on that it.
Example:
```csharp
list.Select(e => e.Property).Should().NotContainNull();
list.Select(e => e.Property).Should().OnlyHaveUniqueItems();
```
This PR gives two overloads for generic collections that takes a predicate
```csharp
list.Should().NotContainNull(e => e.Property);
list.Should().OnlyHaveUniqueItems(e => e.Property);
```
The difference lies in the failure message, where the two overloads contains the objects instead of the properties and the predicate body.
This closes #365
> Add predicate overload to OnlyHaveUniqueItems and NotContainNull

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
Just as on `NotEqual` we can fail fast with a better failure message when `Subject` and `unexpected` references the same object.
This PR adds such fail fast on `NotIntersectWith`, `NotBeSubsetOf`, `NotHaveSameCount` and `NotBeEquivalentTo`.
> Fail fast on more assertions 

- Src/FluentAssertions/TypeEnumerableExtensions.cs
- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
- Tests/Shared.Specs/MethodInfoSelectorAssertionSpecs.cs
- Tests/Shared.Specs/MethodInfoSelectorSpecs.cs
- Tests/Shared.Specs/PropertyInfoSelectorSpecs.cs
- Tests/Shared.Specs/TypeAssertionSpecs.cs
- Tests/Shared.Specs/TypeSelectorSpecs.cs
> NotBeDecoratedWith and ThatAreNotDecoratedWith

- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/NonGenericCollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
Adds the following assertions for `NonGenericCollections` And `GenericDictionary` 
* `NotHaveCount`
* `HaveCountGreaterThan`
* `HaveCountGreaterOrEqualTo`
* `HaveCountLessThan`
* `HaveCountLessOrEqualTo`
This closes #615
> HaveCount variants

- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
I forgot to include the `HaveCount` overloads for generic collections.
> Add HaveCount variants for generic collections

- build.ps1
Checks that the version of `nuget.exe` matches the expected version.
Will save me late hours the next time I swear about FA not building when:
* Having run `build.ps1` earlier and therefore having a `Build\nuget.exe`.
* The required version of `nuget.exe` is updated in `buid.ps1`
* does not work running `build.ps1` again 
* works in Visual Studio
> check nuget.exe version

- Tests/Net45.Specs/Net45.Specs.csproj
- Tests/NetCore.Specs/NetCore.Specs.csproj
- Tests/NetCore20.Specs/NetCore20.Specs.csproj
- Tests/TestFrameworks/XUnit2.Net45.Specs/XUnit2.Net45.Specs.csproj
- Tests/TestFrameworks/XUnit2.Net45.Specs/packages.config
- build.cake
Updates and consolidates xunit packages
If you're having problems with VS showing warnings about it cannot load something like `xunit-analyzer, version=0.3.0` it a known caching problem in VS. 
Clearing the MEF cache should solve it.
> Update xunit to 2.3.0-beta5

- CONTRIBUTING.md
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Shared.Specs/StringAssertionSpecs.cs
- docs/documentation.md
One thing I always find myself doing is asserting the contents of a string multiple times. Usually I am wanting to assert that something like a log message contains some important information in no particular order (so as to not have an overly rigid test). For example:
```csharp
logMsg.Should().Contain(customerNumber);
logMsg.Should().Contain("success");
logMsg.Should().Contain(timestamp);
```
I thought it might be nice if I could write this instead:
```csharp
logMsg.Should().ContainAllOf(new []{ customerNumber, "success", timestamp"});
```
I also thought a similar `ContainAnyOf` could be useful, so I added it while I was there.
I updated the CONTRIBUTING.MD document as well, adding the disclaimer about the v 5 rework and suggesting PRs be targeted at develop (it said master before).
> string.ContainAllOf and string.ContainAnyOf

- build.cake
When running `build.ps1` net451 tests are not discovered due to a typo in the path pattern.
> net451 tests are not discovered

- Src/FluentAssertions/TypeEnumerableExtensions.cs
- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Src/FluentAssertions/Types/TypeSelector.cs
Asserting that a type is (not) decorated with something that isn't an attribute is most likely a wrong assertion.
Let us help preventing wrong assertions by constraining `TAttribute` to `Attribute`
> Constrain TAttribute to Attribute

- Tests/NetCore20.Specs/NetCore20.Specs.csproj
MSBuild complains that it cannot find the `AllRules.ruleset` for code analysis.
This aligns the project file for NetCore20 with NetCore
> Remove reference to non-existing file

- docs/_config.yml
- docs/_data/mstest-migration/assert.yml
- docs/_data/mstest-migration/collectionAssert.yml
- docs/_data/mstest-migration/exceptions.yml
- docs/_data/mstest-migration/stringAssert.yml
- docs/_data/tips/collections.yml
- docs/_data/tips/comparable.yml
- docs/_data/tips/dictionaries.yml
- docs/_data/tips/exceptions.yml
- docs/_data/tips/nullables.yml
- docs/_data/tips/strings.yml
- docs/_data/tips/types.yml
- docs/_includes/assertion-comparison.html
- docs/assets/main.scss
- docs/examples.md
- docs/tips.md
As promised in #585 here is a list of 104 examples about:
* Converting from MSTest to Fluent Assertions.
* Rewriting assertions for clearer intentions and better failure messages.
Comments on the preface and the layout are very welcome.
> Migration from MSTest and improved assertions

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/Shared.Specs/ExecutionTimeAssertionsSpecs.cs
- docs/documentation.md
This PR aligns `ExecutionTime[Of]` with the rest of the v5.0.0 API by using `Should().` to assert.
In order to that I introduced the `ExecutionTime` as a sort of DTO object which could be asserted on.
Removed:
* `ShouldNotExceed`
Added:
* `BeLessOrEqualTo`
* `BeLessThan`
* `BeGreaterOrEqualTo`
* `BeGreaterThan`
* `BeCloseTo`
> Align ExecutionTime[Of] with v5 API

- Tests/Shared.Specs/StringAssertionSpecs.cs
I don't think we're ready for blue not being blue.
Let us postpone that until we have `ColorBlindnessAssertions` or `PhilosophicalAssertions`.
> fix typos in tests

- Tests/Shared.Specs/ExecutionTimeAssertionsSpecs.cs
My assertions for `Execution[Of]` sometimes failed, when `Thread.Sleep(100)` took considerably longer than 100ms an running tests in parallel.
This relaxed the timing limits to avoid tests failing without anything being wrong.
> Relaxed time limits

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
Found a few places where we should constrain the generic type to be an exception.
> Constraining of generic types to exceptions

- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Tests/Shared.Specs/AssemblyAssertionSpecs.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/ObjectAssertionSpecs.cs
20 tests were not consumed by the netcore2.0 test application even though the assertions are exposed to .net standard 2.0.
> Expose more tests to netcore2

- Src/FluentAssertions/Equivalency/AssertionResultSet.cs
The `BestResults` property violates the [MS guidelines](https://msdn.microsoft.com/en-us/library/ms229054%28v=vs.100%29.aspx) about when to prefer methods over properties.
> Do use a method, rather than a property, in the following situations.`
> The operation returns an array.
Probably because the use of a property made it look like a cheap operation, it was called twice, causing double enumeration and array allocation.
This is almost identical to the second example in the link above.
> Use method instead of property to avoid mistakes

- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
> Removed WithInnerMessage as chaining WithInnerException with WithMessage gives the same result.

- Src/FluentAssertions/Extensions/FluentDateTimeExtensions.cs
- Src/FluentAssertions/Extensions/FluentTimeSpanExtensions.cs
- Src/FluentAssertions/Extensions/TimeSpanConversionExtensions.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
- Tests/Shared.Specs/DateTimeAssertionSpecs.cs
- Tests/Shared.Specs/DateTimeOffsetAssertionSpecs.cs
- Tests/Shared.Specs/DateTimeOffsetValueFormatterSpecs.cs
- Tests/Shared.Specs/EventAssertionSpecs.cs
- Tests/Shared.Specs/ExecutionTimeAssertionsSpecs.cs
- Tests/Shared.Specs/ExtensibilityRelatedEquivalencySpecs.cs
- Tests/Shared.Specs/FluentDateTimeSpecs.cs
- Tests/Shared.Specs/NullableSimpleTimeSpanAssertionSpecs.cs
- Tests/Shared.Specs/ObjectAssertionSpecs.cs
- Tests/Shared.Specs/ReferenceTypeAssertionsSpecs.cs
- Tests/Shared.Specs/SimpleTimeSpanAssertionSpecs.cs
- Tests/Shared.Specs/TimeSpanConversionExtensionSpecs.cs
Fix for Issue #674, 
Moves DateTime and TimeSpan extensions into the "FluentAssertions.Extensions" namespace. I've also renamed the `TimeSpanConversionExtensions` to `FluentTimeSpanExtensions` to follow the naming conventions used in other "helper" extensions.
> Add an Extensions namespace for helper extension methods.

- Src/FluentAssertions/Extensions/FluentTimeSpanExtensions.cs
Mistakenly introduced a redundant cast in PR #675. Removed the cast and restored the original method body.
> Removed redudant cast from the TimeSpan#Nanosecond extension

- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
This PR includes all the unexpected matches in the failure message of `NotContain`.
This is useful when the predicate uses some (nested) property, then you will now know the entire structure of the object(s) which led to the failure.
> Report all matches when NotContain fails

- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
This PR adds two `params KeyValuePair<TKey, TValue>[]` overloads for:
* `GenericDictionaryAssertions.Contain` 
* `GenericDictionaryAssertions.NotContain`
> Params overloads for dictionary assertions

- Tests/Shared.Specs/DateTimeOffsetAssertionSpecs.cs
When not providing an `offset` to the `DateTimeOffset` constructor [it picks the local offset](http://referencesource.microsoft.com/#mscorlib/system/datetimeoffset.cs,69)
This PR explicitly sets the offset to `TimeSpan.Zero`.
Thanks to @alexangas for pointing this out.
> Explicitly set offset in DateTimeOffset test

- Src/FluentAssertions/Equivalency/AssertionRule.cs
- Src/FluentAssertions/Equivalency/AssertionRuleEquivalencyStep.cs
- Tests/Shared.Specs/ExtensibilityRelatedEquivalencySpecs.cs
This PR changes the failure message, when the type of a property is not equal or assignable to `TSubject`, to say that the property was not convertible to `TSubject`.
This is the first time I touch the object comparison code in Fluent Assertions, but I hope I haven't overlooked any (obvious) case(s).
E.g. are there any usages of `Using<TSubject>()` where `context.Expectation` or `context.Subject` are allowed to not be equal or assignable to `TSubject`?
This fixes #687
> Include generic type in failure message

- Src/FluentAssertions/Primitives/StringAssertions.cs
- docs/documentation.md
I've updated the documentation as a part of #592.
Stuff I have done:
* Adapting the `Should().` pattern most places
* Adding new assertions
* Fixing typos/mispellings
Stuff I _haven't_ touched:
* Archiving the current docs and link to them like we link to the 2.0 docs.
* The merging of `ShouldBeEquivalentTo` and `BeEquivalentTo`, `ShouldAllBeEquivalentTo`
* The gazillion new `Type` related assertions
* Events: `Should[Not]Raise`, `Should[Not]RaisePropertyChangeFor`
> Improve documentation for 5.0

- Src/FluentAssertions/Common/Configuration.cs
- Tests/Shared.Specs/ConfigurationSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
Configuration.Current.ValueFormatterAssembly and Configuration.Current.ValueFormatterDetectionMode can be accessed in concurrent execution safely. Spotted in #664.
> Some threadsafety for Configuration

- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/CustomAssertionAttribute.cs
- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Tests/Shared.Specs/BooleanAssertionSpecs.cs
- Tests/Shared.Specs/ExtensibilitySpecs.cs
- Tests/Shared.Specs/NullableBooleanAssertionSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
If a custom assertion (extension) method uses Fluent Assertions internally, you can mark it with the `[CustomAssertion]` attribute. This ensures that FA will ignore that method while traversing the stack frames looking for a call to `Should` as part of the caller identification process
#588
>  Allow marking custom assertions so they are ignored during caller identification

- Src/FluentAssertions/Formatting/TimeSpanValueFormatter.cs
- Tests/Shared.Specs/NullableNumericAssertionSpecs.cs
- Tests/Shared.Specs/NumericAssertionSpecs.cs
- Tests/Shared.Specs/TimeSpanFormatterSpecs.cs
Fixed tests were failing in my pl-PL settings.
In case of TimeSpan, it was not only tests, but also implementation did not specify InvariantCulture explicitly.
> Fix culture-sensitive tests

- Src/FluentAssertions/Formatting/DateTimeOffsetValueFormatter.cs
Inspired by #726.
This fixes the case where the `DateTimeFormatInfo.TimeSeparator` of your `CurrentCulture` is not `-`.
> Use the invariant culture for formatting date time offsets

- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
Some sanity checks that should still pass if one tries to add support for `IReadOnlyDictionary`.
> Sanity checks

- Src/FluentAssertions/Specialized/ActionAssertions.cs
- Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
> Fail when Should().[Not]Throw used on async void Action

- Src/FluentAssertions.nuspec
- Src/FluentAssertions/AssertionOptions.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/CollectionMemberAssertionOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/CyclicReferenceDetector.cs
- Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/ObjectReference.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/ValueTypeEquivalencyStep.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Src/FluentAssertions/Formatting/Formatter.cs
- Tests/Net45.Specs/Net45.Specs.csproj
- Tests/NetCore.Specs/NetCore.Specs.csproj
- Tests/Shared.Specs/AssertionOptionSpecs.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
- Tests/Shared.Specs/DictionaryEquivalencySpecs.cs
- docs/documentation.md
- docs/extensibility.md
Replaces all mechanisms and options to control whether or not an object has value semantics by a single algorithm: Any object that overrides object.Equals and is not an anonymous type is treated as a value type, unless ComparingByMembers<T>() is used. Also removes the global AssertionOptions.IsValueType. For those cases where this algorithm misbehaves, ComparingByValue<T> can be used.
#739
> Assuming types that override Equals to have value semantics

- Src/FluentAssertions/TypeEnumerableExtensions.cs
- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Tests/Shared.Specs/MethodInfoSelectorSpecs.cs
- Tests/Shared.Specs/PropertyInfoSelectorSpecs.cs
- Tests/Shared.Specs/TypeSelectorSpecs.cs
This PR adds new selector for type, property and method selectors in order to align the API with the new assertions introduced in #727 .
`CustomAttributes.GetCustomAttributes(property, true)` is used instead of `property.GetCustomAttributes(true)` to workaround a bug in [corefx](https://github.com/dotnet/corefx/issues/8220) where `PropertyInfo` ignores the `inherit` parameter when overriding `GetCustomAttributes(bool inherit)`.
> Add ThatAre[Not]DecoratedWithOrInherit

- Src/FluentAssertions/FluentAssertions.csproj
Adds `System.ValueTuple` as a `PackageReference` to `net45` instead of relying on a `HintPath`.
> Fix PackageReference

- Src/FluentAssertions/Execution/MessageBuilder.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
I noticed that my changes in #715 were overwritten by #705.
That turned out to be a blessing in disguise, as my previous PR was wrong.
(The last `\}` in the regex was `\{` ).
Now I've done it right and added more tests.
I assume this is a corner case, so no pressure from me to get it pushed out.
> Fix substitution of contextual tags

- Src/FluentAssertions.nuspec
- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Common/AppSettingsConfigurationStore.cs
- Src/FluentAssertions/Common/FullFrameworkReflector.cs
- Src/FluentAssertions/Common/Services.cs
- Src/FluentAssertions/Execution/AssertionFailedException.cs
- Src/FluentAssertions/Execution/GallioTestFramework.cs
- Src/FluentAssertions/Execution/LateBoundTestFramework.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/ObjectAssertionsExtensions.cs
- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Src/FluentAssertions/Xml/XmlAssertionExtensions.cs
- Src/FluentAssertions/Xml/XmlElementAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeAssertionsofTSubjectTAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeFormatter.cs
I hope this is the right way to do this. I did build using the script and it changed all the assembly info files - not sure if I was supposed to include those in this pull request - can do if necessary
> add a target for .net 4.7 that doesn't include ValueTuple fix #757

- Src/FluentAssertions/Equivalency/GenericEnumerableEquivalencyStep.cs
This PR avoids an NRE when calling `GenericEnumerableEquivalencyStep.AssertSubjectIsCollection` with a null `subject`.
This is identical to what is done in `EnumerableEquivalencyStep.AssertSubjectIsCollection`.
> Avoid NRE in AssertSubjectIsCollection

- Src/FluentAssertions/Equivalency/EnumerableEquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyValidatorExtensions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
This PR improves the failure message when collections fail in `BeEquivalentTo` due to unequal length.
Before the failure message would only state the number of found items.
The failure message now includes:
* subject collection,
* expected collection,
* the difference in length, 
* and whether the subject had too many or too few items.
> Improve message for unequal length collections in BeEquivalentTo

- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
> Fixes a FormatException when a bad string is included in the 'because' clause

- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
This is admittedly a minor case, but we should only trigger the `FormatException`/warning message from attempting to use the `because` parameter in `string.Format` if we also include `becauseArgs`.
> Only attempt to format in BecauseOf if format parameters were supplied

- Src/FluentAssertions/CallerIdentifier.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
This PR fixes a NullReferenceException, when the declaring type of a test method is not inside a namespace.
This fixes #772
> Do not assume test classes to be inside a namespace

- Tests/Shared.Specs/NullableEnumAssertionSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
A regression test to ensure that "someone" does not break the API again regarding nullable enums.
> Test that nullable enums are catched by ObjectAssertions

- Src/FluentAssertions/Equivalency/EquivalencyAssertionOptionsExtentions.cs
- Tests/Net45.Specs/Net45.Specs.csproj
- Tests/Net47.Specs/Net47.Specs.csproj
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
The `EnumerableEquivalencyStep` did not treat the expectation as an enumerable when the property type was a `Nullable<T>`. 
Fixes #777
> Nullable properties of type `IEnumerable` should still be treated as enumerables

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/Shared.Specs/TypeAssertionSpecs.cs
- docs/documentation.md
For  #645
Assertions for types (abstract, sealed, static) added. They are based on C# understanding of those keywords, as in CLR they differ.
> (Not)Be(Abstract|Sealed|Static) class assertions implemented

- Src/FluentAssertions/Primitives/StringAssertions.cs
- #809
This PR changes the XML documentation for the `values` parameter on `StringAssertions.ContainAll` to match the behavior in the method, while maintaining consistency with other similar overloads.
@luizadolphs @anitokj
> Fix String.ContainAll param documentation.

- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Tests/Shared.Specs/NumericAssertionSpecs.cs
This PR adds `[Not]BeCloseTo` for: byte, sbyte, ushort, short, uint, int, ulong and long.
I could use some feedback on the type of the `delta` parameter.
* for the signed cases they take a signed `delta`, but throw an `ArgumentOfOutRangeException` if the `delta` is negative.
* for the unsigned cases they take a unsigned `delta` which can never be negative.
So I'm unsure what the most consistent/unsurprising/user-friendly API:
* The signedness of `delta` follows the others, 
* They take a signed `delta` and conditionally throws, or
* They take an unsigned `delta`
This fixes #801
> [Not]BeCloseTo for integral types

- Src/FluentAssertions/Execution/GallioTestFramework.cs
- Src/FluentAssertions/Execution/LateBoundTestFramework.cs
Since .NET Standard 2.0 `GetAssemblies()` is now available.
This fixes #823
> Use GetAssemblies() for .NET Standard 2.0

- Src/FluentAssertions.nuspec
- Src/FluentAssertions/AssemblyInfo.cs
- docs/_pages/about.md
I noticed a few places where the documentation about which frameworks we target where out of date.
> Update documentation with target frameworks

- Src/FluentAssertions/Formatting/XElementValueFormatter.cs
- Tests/Shared.Specs/AndWhichConstraintSpecs.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
- Tests/Shared.Specs/MethodInfoSelectorAssertionSpecs.cs
- Tests/Shared.Specs/PropertyInfoSelectorAssertionSpecs.cs
- Tests/Shared.Specs/ReferenceTypeAssertionsSpecs.cs
- Tests/Shared.Specs/StringAssertionSpecs.cs
- Tests/Shared.Specs/TypeAssertionSpecs.cs
- Tests/Shared.Specs/XElementFormatterSpecs.cs
The first commit changes test to to match `*` instead of `\r\n` to make the pass on Linux.
The second commit fixes an encoding issue, where an ellipsis would not be rendered on Linux.
With this PR I can build NetStandard{1.3, 1.6, 2.0} targets and run all three NetCore unit tests projects on Linux.
> Make tests more cross-platform

- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
`ContainKey` and `ContainSingle` could throw a `KeyNotFoundException` or `InvalidOperationException` respectively.
That prevented the inclusion failure messages of succeeding assertions inside an `AssertionScope`.
This fixes #835
> Fix ContainKey and ContainSingle for AssertionScope

- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Src/FluentAssertions/Execution/GivenSelectorExtensions.cs
- Tests/Benchmarks/CollectionEqual.cs
- Tests/Benchmarks/Program.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
This PR optimizes `Equal` for generic collections as #490 mentioned performance problems.
The slowdown was mostly due generic collections of value types being boxed.
A minor downside is that now the subject will now be enumerated twice when failing, whereas before it was a copy of the subject that got enumerated in `EnumerableValueFormatter`.
I believe this is worthwhile as we should optimize for tests passing.
In the benchmark:
* `CollectionEqual_NonGeneric` is equivalent to the current behavior, 
* `CollectionEqual_Generic` is the optimized version from this PR.
* `CollectionEqual_Generic_Equality` is using a custom comparer in the benchmark, `(int s, int e) => s == e` in this example.
```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.16299.371 (1709/FallCreatorsUpdate/Redstone3)
Intel Core …
```
> Optimize generic collection Equal

- Src/FluentAssertions/CallerIdentifier.cs
See https://stackoverflow.com/questions/50120792/fluentassertions-throws-argumentoutofrangeexception-when-assertion-fails-possib?noredirect=1#50120792
> Handle an edge case that seem to happen under NCrunch

- docs/_data/tips/exceptions.yml
The exception tips are outdated and use the old syntax
```
act.ShouldThrowExactly()
```
instead of
```cs
act.Should().ThrowExactly()
```
I was wondering if about adding more tips for the `WithInnerException` and `WithInnerExceptionExactly` methods as well
something like this:
old:
```cs
act.Should().Throw<Exception>()
.Which.InnerException.Should().BeOfType<ArgumentException>();
```
new:
```cs
act.Should().Throw<Exception>()
.WithInnerException<ArgumentException>();
```
@jnyrup
> updated exceptions tips

- Src/FluentAssertions.nuspec
- Src/FluentAssertions/AssemblyInfo.cs
- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Common/AppSettingsConfigurationStore.cs
- Src/FluentAssertions/Common/FullFrameworkReflector.cs
- Src/FluentAssertions/Common/Services.cs
- Src/FluentAssertions/Events/EventAssertions.cs
- Src/FluentAssertions/Events/EventHandlerFactory.cs
- Src/FluentAssertions/Events/EventMonitor.cs
- Src/FluentAssertions/Events/EventRecorder.cs
- Src/FluentAssertions/Events/IMonitor.cs
- Src/FluentAssertions/Execution/AssertionFailedException.cs
- Src/FluentAssertions/Execution/GallioTestFramework.cs
- Src/FluentAssertions/Execution/LateBoundTestFramework.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/ObjectAssertionsExtensions.cs
- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Src/FluentAssertions/Xml/XmlAssertionExtensions.cs
- Src/FluentAssertions/Xml/XmlElementAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeAssertionsofTSubjectTAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeFormatter.cs
- Tests/NetCore20.Specs/NetCore20.Specs.csproj
- Tests/Shared.Specs/AssertionOptionSpecs.cs
- Tests/Shared.Specs/EnumAssertionSpecs.cs
- Tests/Shared.Specs/EventAssertionSpecs.cs
- docs/_pages/about.md
- docs/index.html
Some features such as ILEmit didn't work in .NET Standard 2.0, but where available up until recently when microsoft pulled System.Reflection.Emit from NuGet. So it appeared the API worked, but only really worked under the runtime platforms. See also https://github.com/dotnet/corefx/issues/29365
* {New} Added support for .NET Core 2.0 in addition to .NET Standard 2.0
* {Fix) Restricted the event assertion API to the run-time .NET platforms only 
Fixes #859
> Adds support for .NET Core 2.0 and restricts event assertion API.

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Shared.Specs/AssertionOptionSpecs.cs
The current approach from 8af4abe9313be62391065d8b0cbf9b9f3ded9001 is not thread-safe.
Using a `ConcurrentDictionary` should make it thread-safe again.
From the benchmark results below, it still seems beneficial to cache the result of `HasValueSemantics()`.
A specially crafted test suite *might* suffer from the introduced locking by using `ConcurrentDictionary`, but I couldn't find a measurable difference when running the tests. 
This fixes #862.
Current approach with `Dictionary`
```
Method |     N |         Mean |       Error |       StdDev |       Median |      Gen 0 |    Allocated |
--------------- |------ |-------------:|------------:|-------------:|-------------:|-----------:|-------------:|
BeEquivalentTo |    10 |     663.7 us |    10.25 us |     9.584 us |     668.1 us | …
```
> Make GetEqualityStrategy thread-safe again

- build.cake
I broke NUnit2 testing in fbf4b17718be39bf71c575ec0fe0a1dc82bcf1c7 👎 
nunit.runners is still required to run from console/Cake. 
NUnitTestAdapter is just for running through Visual Studio.
Apparently AppVeyor skipped the test, while locally it failed as it could not find the required runner.
> Re-add nunit.runner for NUnit2

- docs/_includes/assertion-comparison.html
- docs/_pages/tips.md
From #866 
This PR adds an `id` to all examples on the website, such that one can link directly to them.
Pros:
* No need to add individual ids to each example
Cons:
* If the order of examples is mutated or new examples are not appended to the end, then the links become invalid.
> Add id to all examples

- Tests/Shared.Specs/ThrowAssertionsSpecs.cs
Change `dit` to `did`.
I was reading through the unit tests in this project to get a better idea of how to write my own tests and noticed some spelling typos.
> fix(ThrowAssertionsSpecs): typos in exception messages

- CONTRIBUTING.md
Updates to the current `CONTRIBUTING.md`
* References changes coming in v5.0 which has been released for awhile
* Says to target the `develop` branch which doesn't exist now
* Spelling typo
* Lint according to [markdownlint for vscode](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) which recommended using a `# title` for the first line.
> docs(CONTRIBUTING): fix typos, remove/correct old messaging, lint

- Src/FluentAssertions/Equivalency/AssertionRule.cs
- Src/FluentAssertions/Equivalency/AssertionRuleEquivalencyStepAdapter.cs
- Tests/Shared.Specs/DictionaryEquivalencySpecs.cs
- Tests/Shared.Specs/ExtensibilityRelatedEquivalencySpecs.cs
> Custom rules were not executed on dictionary equivalency assertions

- Tests/Shared.Specs/AssertionOptionSpecs.cs
- Tests/Shared.Specs/CustomAssemblyInfo.cs
- Tests/Shared.Specs/Shared.Specs.projitems
- Tests/Shared.Specs/Shared.Specs.shproj
When the `AssertionOptionSpecs` run in parallel with other tests, they can affect the outcome.
> Disabled parallel execution of unit tests

- Src/FluentAssertions/Equivalency/ObjectReference.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
If you compare an object that implements `IEnumerable<T>` and returns itself, you'll end up with a deeply nested path description like `[0][0][0]`. The cyclic reference detection logic would treat that as a single element instead of a deeply nested path. 
Fixes #880
> Fixed a StackOverflow while comparing a self-returning enumerable.

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
Related to #888 
CC: @jnyrup 
Maybe it would be sensible to create some extension method to check if correct exception (or type of exception) is included in `FailWith` continuation? What do you think?
> show error instead of message for async throws

- Tests/Shared.Specs/AssertionOptionSpecs.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
- Tests/Shared.Specs/ConfigurationSpecs.cs
- Tests/Shared.Specs/CustomAssemblyInfo.cs
- Tests/Shared.Specs/DictionaryEquivalencySpecs.cs
- Tests/Shared.Specs/ExtensibilityRelatedEquivalencySpecs.cs
- Tests/Shared.Specs/FormatterSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
Instead of disabling intra-assembly parallel test execution, we can explicitly mark which test classes that contain tests which alters static state and hence must be executed sequentially.
To my knowledge those things from the public API are:
* `AssertionOptions`
* `Configuration.Current`
> Enable parallel execution of tests again

- Src/FluentAssertions.nuspec
This adds a link to the git repository in the nuspec.
Currently this adds a link "Source Code" on nuget.org
See e.g. https://www.nuget.org/packages/Newtonsoft.Json/
https://github.com/NuGet/Home/wiki/Show-source-repository-information-for-packages-on-nuget.org
> Long term ideas on the display and usage
Out-of-scope for this spec. However, some of the ideas include:
> * Show repository info as a separate section with links to file issues, show number of active issues and last activity - all of these are vital information that consumers would like to see for a given package they want to consume.
> * Compute the quality metirc based on issues fixed vs. open issues on the repository
> * Use this to switch from PackageReference to ProjectReference by automatically cloning the repo as a …
> Adds link to repository to nuspec

- Src/FluentAssertions/Equivalency/ObjectReference.cs
- Src/FluentAssertions/Formatting/Formatter.cs
I see no value in rendering a graph 15 levels deep. This should help prevent OOM exceptions while rendering an object graph. 
Fixes #889
> Limits the depth of rendering an object to a max of 5

- build.cake
Even though the path to `NetCore20.Specs.csproj` has always been wrong the tests have always executed.
> Fix path to NetCore20 project in cake

- Build/packages.config
- Tests/Benchmarks/BeEquivalentTo.cs
- Tests/Benchmarks/Benchmarks.csproj
- Tests/Benchmarks/CollectionEqual.cs
- Tests/Net45.Specs/Net45.Specs.csproj
- Tests/Net47.Specs/Net47.Specs.csproj
- Tests/NetCore.Specs/NetCore.Specs.csproj
- Tests/NetCore20.Specs/NetCore20.Specs.csproj
- Tests/NetStandard13.Specs/NetStandard13.Specs.csproj
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit2.Net45.Specs/NUnit2.Net45.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
- build.cake
The problems with upgrading xunit to 2.4.0 was apparently problems with `dotnet xunit`.
It was complete removed in 2.4.0, see [release notes](https://xunit.github.io/releases/2.4)
As recommended in the release notes I've changed from `dotnet xunit` to `dotnet test`.
This fixes #720
> Update test packages

- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
The changes proposed in #904 can cause a breaking change at runtime if one uses an array of interface types and implicitly asserts that runtime properties are respected.
Even though the consistent way would be to respect the compile type and require `RespectRuntimeTypes()`, I'd like to keep my breaking change score at 1. #762 
This PR instead adds tests to help anyone who tries to fix the inconsistent behavior of `BeEquivalentTo(params object[])`, at least for 5.x.x, not to cause a breaking change.
> Add tests to prevent breaking changes

- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Execution/FailReason.cs
- Src/FluentAssertions/Primitives/StringEqualityValidator.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
Follow up for #915.
A lazy version of `FailWith` is useful when calculations of messages are "expensive' and could be delayed until we are that we will throw. FA main scenario is that most tests do not fail, so I think it makes sense to take care of performance in that case.
Of course, as usual, tests for new functions are added.
I am curious about your comments @jnyrup @dennisdoomen.
> Define lazy version of `AssertionScope.FailWith`

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyValidator.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
Attempt to fix #914.
There are (at least) two bottlenecks:
I checked that after those three issues there are no more outstanding hot spots. Execution time is split among some `CanHandle` methods, creating objects like `EquivalencyValidationContext` and so on.
Any ideas are warmly welcomed.
> Improve performance of AllBeEquivalentTo

- docs/_pages/documentation.md
I think this documentation extension closes #846.
> Document catching trace for successful assertions

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyValidatorExtensions.cs
- Src/FluentAssertions/Equivalency/GenericDictionaryEquivalencyStep.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Execution/ChainedAssertionScope.cs
- Src/FluentAssertions/Execution/Continuation.cs
- Src/FluentAssertions/Execution/ContinuationOfGiven.cs
- Src/FluentAssertions/Execution/GivenSelector.cs
- Src/FluentAssertions/Execution/IAssertionScope.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/StringValidator.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Xml/XmlReaderValidator.cs
Introduces a `ClearExpectation` to undo the expectation that is associated with multiple assertions using `WithExpectation`. Without it, it is possible that this expectation gets appended to any successive assertions.
Fixes #918
> Ensures expectations involving multiple assertions can be cleared

- Src/FluentAssertions/Common/CSharpAccessModifier.cs
- Src/FluentAssertions/Common/CSharpAccessModifierExtensions.cs
- Tests/Net45.Specs/Net45.Specs.csproj
- Tests/Net47.Specs/Net47.Specs.csproj
- Tests/NetCore.Specs/NetCore.Specs.csproj
- Tests/NetCore20.Specs/NetCore20.Specs.csproj
- Tests/NetStandard13.Specs/NetStandard13.Specs.csproj
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/MethodBaseAssertionSpecs.cs
I changed Spec assemblies configuration to `<LangVersion>7.2</LangVersion>`. `private protected` access modifier is not available in earlier versions.
Closes #878.
> Add support for private protected access modifier

- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
I think that this simple extension to `WithMessage` code documentation closes #548.
`documentation.md` already mentions wildcard matching behaviour.
> Document  wildcard pattern matching

- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Tests/Shared.Specs/NullableNumericAssertionSpecs.cs
Two main topics of the PR:
- Introduce regions for `NumericAssertionsExtensions`, one for each method group
- Extract repeated code from each method group
I would like that to be merged before I will tackle extension of `NotBeEquivalentTo` for nullable subject and expected value (I mean folloup of #934).
> Nullable assertion extenions cleanup

- Src/FluentAssertions/Equivalency/CollectionMemberAssertionOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/ConversionSelector.cs
- Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/RunAllUserStepsEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
Refers to #738.
For sure it is a step forward, but I am not certain if it fixes the root cause. I will investigate more, and possibly follow up with another PR.  But for the time being...
the problem was the `ConversionSelector.Clone` method that treated `description` of type `StringBuilder` like it was immutable `string`. Obviously, `StringBuilder` is mutable and needs to be cloned.
Two main changes:
- Create new `StringBuilder` in `ConversionSelector.Clone`
- Rename `description` field to `descriptionBuilder` because `description` suggests it is a `string` indeed.
> Fix multiplied ConversionSelector's descriptions appearing in assertion message

- build.cake
Specifies that both `DotNetCoreRestore` and `NuGetRestore` should use `nuget.config` to ensure that `nuget.org` is used.
> Ensure specific nuget.config is used

- Tests/NetCore20.Specs/NetCore20.Specs.csproj
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
A single test didn't succeed on linux, due to difference in newlines.
Ignore NU1701 about referencing Chill (which targets .net framework) from .net core test projects as the tests ran fine.
> Cross-platform compatibility

- Tests/Net45.Specs/Net45.Specs.csproj
- Tests/Net47.Specs/Net47.Specs.csproj
- Tests/NetCore.Specs/NetCore.Specs.csproj
- Tests/NetCore20.Specs/NetCore20.Specs.csproj
- Tests/NetStandard13.Specs/NetStandard13.Specs.csproj
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/Shared.Specs/ThrowAssertionsSpecs.cs
This PR removes the dependency on FakeItEasy, because
* we only used FakeItEasy to throw exceptions with `IFoo`, and
* it mislead a contributor to use FakeItEasy instead of just a simple `Action`.
> Replace FakeItEasy dependency with custom class

- Src/FluentAssertions/Execution/ChainedAssertionScope.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
The `ClearExpectation` on a chained `Continuation` would cause the `AssertionScope` to forget the fact that an earlier assertion in that chain failed. This resulted in the equivalency API to choke on not getting any failures back when it tries to compare two collections for unordered equivalency and one of them was empty.
Fixes #965
> When deeply nested collections where compared to an empty collection it threw

- Src/FluentAssertions/AssertionExtensions.cs
- Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
Closes #964.
In hindsight, missing support for `Func<Task<T>>` seems so obvious :-).
> Add support for async assertion on Func<Task<T>>

- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
Rename parameter of `Not*` assertions to be in negative form, i.e. `expected` into `unexpected`.
> Rename expected to unexpected for negative tests

- Src/FluentAssertions/Common/MemberPath.cs
- Src/FluentAssertions/Equivalency/Selection/ExcludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
This PR has three parts:
* Lazy-loading `Segments` instead of eagerly in constructor
* Caching segments for candidates, by wrapping them as a `MemberPath`
* Use type check as fail-fast in `IsSameAs`
> Optimize performance of IncludeMemberByPathSelectionRule 

- Src/FluentAssertions/Equivalency/GenericEnumerableEquivalencyStep.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
The `GenericEnumerableEquivalencyStep` did not properly support the subject to be a non-generic collection. 
Fixes #973
> Allows BeEquivalentTo to handle a non-generic collection as the SUT

- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/GenericDictionaryEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/GenericEnumerableEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/ObjectReference.cs
This fixes `GenericDictionaryEquivalencyStep` and `GenericEnumerableEquivalencyStep` performance problems caused by the use of uncached `LambdaCompiler.Compile` which is very expensive.
Related to #475.
This makes `ObjectAssertions.BeEquivalentTo` about 4.3x faster in our test projects.
> EquivalencyValidator performance fixes

- Src/FluentAssertions/Execution/AssertionScope.cs
In #925, some of the methods of `AssertionScope` were changed to return an `IAssertionScope` instead of the full class. However, this causes binary compatibility issues for libraries extending FluentAssertions. If such a library depended on a version between 5.0 and 5.5, upgrading to 5.5 would cause missing method exception. I've reverted those changes by exposing the `IAssertionScope` interface as explicit interface implementations. 
This should fix https://github.com/fluentassertions/fluentassertions.json/issues/27
> Reverted changes to AssertionScope to maintain binary compatibility

- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
This PR adds a test to check that a custom dictionary implementing `IDictionary<TKey, TValue>` but not `IReadOnlyDictionary<TKey, TValue>` still has access to the assertions in `GenericDictionaryAssertions`.
> API breakage test for IDictionary

- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
As discussed in issue #1002 I'm providing fix for BeOfType and BeAssignableTo within an AssertionScope.
While checking the current implementations I was wondering why (Not)BeOfType(<T>) and (Not)BeAssignableTo(<T>) are looking quite different. I expected similar issues in all these methods.
Can somebody explain the differences?
> fix BeOfType and BeAssignableTo within AssertionScope (fixes #1002)

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
This could be a quick fix to #1006.
When using `AllBeAssignableTo` or `AllBeOfType` on a list of types it did convert the list to a list of `System.RuntimeType` and fail the assertion. That was because the code called `GetType()` on an object that already was a type.
BR,
Matthias
> AllBeAssignableTo and AllBeOfType for List of Types

- Src/FluentAssertions/Specialized/ActionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Tests/Shared.Specs/FunctionExceptionAssertionSpecs.cs
Attempts to fix a timing issue for the NotThrowAfter specs. Not entirely sure why this misbehaves on AppVeyor, but this seems to fix this.
> Attempt to fix a timing issue for the NotThrowAfter specs

- Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/Shared.Specs/FunctionExceptionAssertionSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
- Tests/Shared.Specs/Utilities.cs
Some tests were using `.Milliseconds` instead of `.TotalMilliseconds`, which might(?) explain the flaky tests.
It could be pure coincidence when they failed or passed.
By adding `Multiply` and `Divide` (copied from [corefx](https://github.com/dotnet/corefx/blob/09e2417cd0505df4558535651efb1bbcffdf0c59/src/Common/src/CoreLib/System/TimeSpan.cs#L489)), we retain the lifted types in the test code.
> Add TimeSpan helpers

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Tests/Shared.Specs/FunctionExceptionAssertionSpecs.cs
Got a reminder that `FailWith` does not always throw immediately when wrapping multiple assertions inside an `AssertionScope`.
> Fix continuation on NotThrow(After) in AssertionScope

- Src/FluentAssertions/Equivalency/AssertionRuleEquivalencyStepAdapter.cs
- Src/FluentAssertions/Equivalency/IAssertionRule.cs
- Src/FluentAssertions/Equivalency/RunAllUserStepsEquivalencyStep.cs
- Tests/Shared.Specs/ExtensibilityRelatedEquivalencySpecs.cs
Implementations of `IAssertionRule` (including the usage of `Using().WhenTypeIs()` were never run for root objects. 
Fixes #1032
> Allow nesting equivalency checks in custom assertion rules

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Common/NoSynchronizationContextScope.cs
- Src/FluentAssertions/Common/TaskExtensions.cs
- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/Shared.Specs/FunctionExceptionAssertionSpecs.cs
Fix for issue #1020
Removed redundant multithreading which was implemented using Task.Run.
> Removed redundant multithreading

- Src/FluentAssertions/Equivalency/DictionaryEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/GenericDictionaryEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/IEquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/MultiDimensionalArrayEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/StructuralEqualityEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/TryConversionStep.cs
Renamed `IEquivalencyValidator.RecursivelyAssertEquality` to `AssertEqualityUsing` to prevent any breaking changes for folks using this as an extension point. This was introduced in #1026.
> Undone a potential breaking name change

- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Tests/Shared.Specs/SimpleTimeSpanAssertionSpecs.cs
This PR adds missing null checks to `SimpleTimeSpanAssertions` that could cause `NullReferenceException`s when using a `null` `TimeSpan`.
Part of #1039
> Null checks for SimpleTimeSpanAssertions

- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/Formatting/MultidimensionalArrayFormatter.cs
- Tests/Shared.Specs/FormatterSpecs.cs
- Tests/Shared.Specs/MultidimensionalArrayFormatterSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
* Implemented formatting of multidimensional arrays (MultidimensionalArrayFormatter)
* Added unit test for the formatter
* Supported formatting of multidimensional arrays with bounds
* Supported formatting of n-ary dimensional arrays
> Improve formatting of multidimensional arrays (#991)

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Common/StringExtensions.cs
- Tests/Shared.Specs/GenericCollectionAssertionsSpecs.cs
- docs/_pages/documentation.md
Add "satisfy respectively" assertion, similar to xUnit `Assert.Collection` (#882).
> Add "satisfy respectively" assertion (#882)

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/Shared.Specs/FunctionExceptionAssertionSpecs.cs
After #1038 got merged, the logic for unwrapping `AggregateException` becomes a lot easier, as we now know that FluentAssertions doesn't wrap exceptions in an `AggregateException`.
Calling `Throw<TException>` is designed to also succeed if an exception of type `TException` is wrapped inside an `AggregateException`.
The same behavior should be present for `NotThrow<TException>`
This PR solves these problems.
1. `NotThrow<TException>` didn't look inside `AggregateException`s to see if an exception of type `TException` was thrown, which made it non-symmetric to `Throw<TException>`.
2. `GetFirstNonAggregateException` only looked at the `InnerException` of an `AggregateException` instead of `InnerExceptions` (*all* wrapped exceptions). E.g. it failed to handle if `TException` was the second …
> Unwrapping of AggregateExceptions

- Src/FluentAssertions/AssertionExtensions.cs
- Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/Shared.Specs/ThrowAssertionsSpecs.cs
This fixes #872 and complements #1015 by implementing 
```c#
Func<TResult> Invoking<T, TResult>(this T subject, Func<T, TResult> action)
```
For consistency this also implements 
```c#
Func<Task<TResult>> Awaiting<T, TResult>(this T subject, Func<T, Task<TResult>> action)
```
though this currently doesn't have much benefit as both `Func<Task>` and `Func<Task<T>>` uses `AsyncFunctionAssertions`.
> Invoking+Awaiting

- Src/FluentAssertions/Specialized/ActionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- Tests/Shared.Specs/FunctionExceptionAssertionSpecs.cs
> Added .NET Standard 1.3 and 1.6 support for NotThrowAfter

- Src/FluentAssertions/Specialized/ActionAssertions.cs
- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
From my comments in #1028
`invocationEndTime` should be placed after `pollInterval`.
I tried to exercise the code to see what the difference is.
When the `pollInterval` is close to `waitTime` and the `action` is fast
having `invocationEndTime` before `pollInterval` would cause an extra loop iteration, even if the `waitTime` has already been surpassed.
Just to be clear, this is not an attempt to fix the timing related test issues we've been struggling with.
> Improving NotThrowAfter

- Src/FluentAssertions/Execution/TestFrameworkProvider.cs
Instead of calling `ToLower` when looking up a key, we provide the dictionary with `StringComparer.OrdinalIgnoreCase` to achieve the same case insensitive key lookup.
> Use case insentive dictionary instead of transforming key

- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
Use pattern matching to cast directly from `TSubject` to `T` instead of through `object`.
As `TSubject` is not constrained to be a class type, we cannot use ` as ` for the conversion.
> Avoid casting throught object

- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- build.cake
Updating test frameworks.
Note: the [major bump](https://github.com/machine/machine.specifications/releases/tag/v1.0.0) of MSpec is to start using semver.
> Updating nugets

- Src/FluentAssertions/Common/MemberPath.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
Fix #1077 
I think that the method `IsSameOrInherits` should be updated to use `IsSubclassOf` instead of `AssignableFrom` to avoid some potential FPs (assignable checks also for cast not only direct inheritance).
> Fix MemberPath so that it can exclude overriden members

- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/Shared.Specs/AssertionScopeSpecs.cs
Help fixing #906 as it is now possible to create a new assertion strategy that will make a screenshot on a failure.
cc @cbries
> Allow user to specify assertion strategy for the assertion scope

- Src/FluentAssertions/ObjectAssertionsExtensions.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Src/FluentAssertions/Xml/XElementAssertions.cs
Some `IDisposable`s were left open, instead of being wrapped in `using`s.
> Disposing of disposables

- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Tests/Shared.Specs/ObjectAssertionSpecs.cs
> Fix [Not]BeAssignableTo failure messages

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Execution/GivenSelectorExtensions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
When using `WithExpectation` it should most often be matched by a `ClearExpectation`.
Not calling `ClearExpectation` can cause the `expectation` to appear in the failure message of subsequent assertions inside an `AssertionScope`.
To make `AssertCollectionsHaveSameItems` return a chainable `ContinuationOfGiven<T>` I made `CollectionWithIndex<T>`. 
It might not be very elegant, but it was the only way I could come up with.
> Missing ClearExpectation

- Tests/Shared.Specs/ExceptionAssertionSpecs.cs
- build.ps1
In .Net Core 3 preview 7, the formatting of `ArgumentException` [changed](https://github.com/dotnet/coreclr/pull/25185/files#diff-6044f205b677cd7711072c893ce07a6a).
This PR relaxes the expected formatting to also match the upcoming formatting.
> Netcore3 preparation

- Src/FluentAssertions/Numeric/NullableNumericAssertions.cs
- docs/_pages/nullabletypes.md
- docs/_pages/numerictypes.md
Only mention the new `Match` assertion once per overload and use examples, that can't be more idiomatically expressed with existing assertions.
> Only mention Match assertion once per overload

- docs/_pages/introduction.md
I couldn't find the `documentation.md` file, so this just provides the "fix". 
Please let me know if and what has to be done additionally.
> Doc: Fix incorrect rending of inline-code-block and update message

- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Formatting/AttributeBasedFormatter.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
Fix #731 
I have marked the old methods as obsolete but depending on your preferences, I could get rid of them (breaking changes).
I decided to name the methods `XXXOrInherit` not `XXXOrInherits` as recommended to follow the convention used by already implemented methods.
Some of the tests are failing because of my changes on `PropertyInfoSelector.cs` but I can't figure out what's wrong with my change. I'd be grateful for some fresh eyes because I am likely missing something obvious.
> Unify API methods to check for attribute (GH-731)

- docs/_pages/exceptions.md
Didn't understand the sentence on first read.
> Grammar correction for readability

- docs/_pages/executiontime.md
Clarify that the CompleteWithin works on `Func<Task>` and not on `Task` directly.
> Improve documentation on execution time assertions

- FluentAssertions.sln
- Fix `nuget.config` location
- Move the nuke build project at the top, so that it is the default start up project when the repository is cloned fresh and open in Visual Studio. This saves an extra step doing it manually, since no other project is executable. Also running the build with `CTRL + F5` (or `F5`) is very convenient.
> Minor solution file improvements

- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
Allows selecting an explicit interface member over a regular instance member when using `RespectingDeclaredTypes` and expectation type is interface.
Fixes #1130
> Use explicit interface member when respecting declared types

- Src/FluentAssertions/FluentAssertions.csproj
`<PackageIconUrl>` is being deprecated in favor of `<PackageIcon>` and generates `NU5048` warning when packing the `nupkg`.
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048
https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg
> Embed icon in nupkg

- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
We have great support for chaining assertions and by using `WithExpectation` we can ensure that failure messages from assertions with a shared prefix are in sync.
E.g. instead of writing
```c#
Execute.Assertion
.ForCondition(condition1)
.BeCauseOf(because, becauseArgs)
.FailWith("Expected collection to be something, but found <null>.");
Execute.Assertion
.ForCondition(condition2)
.BeCauseOf(because, becauseArgs)
.FailWith("Expected collection to be something, but it was empty.");
```
we can
```c#
Execute.Assertion
.BeCauseOf(because, becauseArgs)
.WithExpectation("Expected collection to be something, ")
.ForCondition(condition1)
.FailWith("but found <null>.")
.Then
.ForCondition(condition2)
.FailWith("but it was empty.")
.Then
.ClearExpectation();
```
Also this PR remove unnecessary extra …
> Chain assertions

- Tests/NetStandard13.Specs/NetStandard13.Specs.csproj
Instead of referencing the FluentAssertions.dll targeting netstandard1.3 directly,
we can use the `<SetTargetFramework>`, which lets us specify it explicitly.
> Simplify ProjectReference to FluentAssertions

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Equivalency/CyclicReferenceDetector.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/StructuralEqualityEquivalencyStep.cs
- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Tests/Shared.Specs/AssemblyAssertionSpecs.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/EnumAssertionSpecs.cs
- Tests/Shared.Specs/GenericCollectionAssertionsSpecs.cs
Some assertions did not include failure reason either because it:
* did not add `BecauseOf` before invoking `FailWith`, or
* did not have {reason} inside the failure message.
I added two optional because parameters to `IsCyclicReference` to achieve this.
That class is internal, so no breaking change, but if it can be done
prettier I'm all ear.
> Add missing failure messages

- Src/FluentAssertions/CallerIdentifier.cs
Apparently when compiling an UWP project with .NET Native
`StackFrame.GetMethod` can return `null`. As determination
of caller identity is just a nice-to-have and not a need-to-have
I think we should wrap it in a `try/catch` instead of throwing
exceptions.
Related to #1149
> Catch exceptions from DetermineCallerIdentity

- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
- docs/_pages/dictionaries.md
Adding support for `HaveSameCount` and `NotHaveSameCount` for dictionaries.  This was almost directly cribbed from the existing `CollectionAssertions` (including test cases).
Resolves #1176
> Add Have/NotHaveSameCount for Dictionaries

- docs/_pages/objectgraphs.md
> Add missing paren to object graphs doc

- Src/FluentAssertions/CallerIdentifier.cs
- Tests/Shared.Specs/CallerIdentifierSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
The check in `IsDotNet` only checks if the namespace starts with "System" which can cause non-dotnet namespaces like `SystemSomething.RestApi` to return true unexpectedly.
I struggled with this one at work today for a few hours as our product name (and therefor our namespaces) are `SystemProductName.RestApi`. I noticed it because the variable names were missing from our failing asserts even when building in debug mode.
> Fix unexpected IsDotNet behavior for non-dotnet namespaces

- Build/_build.csproj
- global.json
`<PackageIcon>` was included with [nuget 5.3.0/dotnet core 3.0.100](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.3).
It does not specify if it is available in any preview version of .Net Core 3.0, but the feature was merged at [August 23](https://github.com/NuGet/NuGet.Client/pull/3006) in .Net Core 3.0-preview7 was released at [July 23](https://dotnet.microsoft.com/download/dotnet-core/3.0#3.0.0-preview7).
So I hope this solves #1186
> update .net core sdk

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Tests/Shared.Specs/TypeSelectorSpecs.cs
The namespace of a type not inside any namespace is `null`.
As all types are *under* the global namespace, `ThatAreUnderNamespace` should be able to gracefully handle `null` namespaces.
This also fixes that `ThatAreUnderNamespace` would incorrectly match the
namespace of a type against a partial prefix.
This fixes #1185 and #1196
> Make `ThatAreUnderNamespace` respect null namespaces and prefixes

- .editorconfig
- Src/FluentAssertions/Xml/XmlReaderValidator.cs
- Tests/Shared.Specs/XDocumentAssertionSpecs.cs
I think, the XDocument equivalence failure message is not helpful when comparing documents with repeating element names, like HTML documents. By just providing the simple XPath it may be very difficult to identify the element with difference:
`/html/body/table/tr/td`
This PR is a proposal to improve the failure message by writing index number (according XPath syntax) when a specific element was found at least second time on same level:
`/html/body/table[2]/tr[17]/td[5]`
Additionally
* I recommend a new setting for `editorconfig` according to the current code style
* I changed a test name according to the test content
> Add index to XPath information of XDocument equivalence failure message

- .github/PULL_REQUEST_TEMPLATE.md
> Fix link to documentation in pull request template

- Src/FluentAssertions/Common/ObjectExtensions.cs
- Tests/Shared.Specs/ObjectExtensionsSpecs.cs
- Tests/Shared.Specs/Shared.Specs.projitems
When comparing whether two objects are equal, a conversion should be precision preserving.
Two examples of comparisons that currently unexpectedly passes:
* `10` is not equal to `true` even though `10` is convertible to `true` as `true` is not convertible to `10`.
* `0.02` is not equal to `0`, as that is due to truncation when converting the `double` into an `int`.
This fixes #1010 
This fixes #1183
> Be more strict when trying to convert types in IsSameOrEqualTo

- Src/FluentAssertions/Common/TypeExtensions.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
Unlinke ValueTuple<>, the older Tuple<> was treated as a value type instead of something that requires a structural equality check.
Fixed #999
> BeEquivalentTo on normal tuples should use structural equivalency

- Src/FluentAssertions/Common/IClock.cs
- Src/FluentAssertions/Equivalency/IMemberSelectionRule.cs
- Src/FluentAssertions/Events/EventAssertions.cs
- Src/FluentAssertions/Execution/IAssertionScope.cs
- Src/FluentAssertions/Formatting/AggregateExceptionValueFormatter.cs
- Src/FluentAssertions/Formatting/ByteValueFormatter.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
Some xml summaries were broken due to either:
* non-existing parameters (probably leftovers from pre-v5 API), or
* typos in `name` attribute.
> Cleanup parameter xml summaries

- Src/FluentAssertions/Common/ConfigurationStoreExceptionInterceptor.cs
- Src/FluentAssertions/Common/Services.cs
Some platforms throw reflection exceptions when trying to use `ConfigurationManager`.
This does not fix the underlying problem of not being unable to use `ConfigurationManager`, but returns `null` instead of an exception.
Relates to #1207 and #1151
> Intercept Reflection exceptions from `AppSettingsConfigurationStore`

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/Shared.Specs/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/DateTimeOffsetValueFormatterSpecs.cs
- Tests/Shared.Specs/GenericDictionaryAssertionSpecs.cs
- Tests/Shared.Specs/ReferenceTypeAssertionsSpecs.cs
- Tests/Shared.Specs/StringAssertionSpecs.cs
- Tests/Shared.Specs/TypeAssertionSpecs.cs
I installed a new version of Stryker, gave it a spin and added test cases for some low-hanging fruit.
Highlights:
* `TypeSelectorAssertions.NotBeDecoratedWithOrInherit(predicate)` only had a test verifying null check of the predicate, but no positive/negative test of the logic.
* `[Not]MatchRegex` would include two failure messages if used inside an `AssertionScope`
* No tests for `NonGenericCollectionAssertions.HaveCount(predicate)`
* No tests for `NotContainKeys` and `NotContainValues` when there is a single unexpected key/value
For anyone interessted here's the [mutation report](https://github.com/fluentassertions/fluentassertions/files/4009395/mutation-report.zip)
Part of #1068
> Increase mutation score

- Src/FluentAssertions/Common/ObjectExtensions.cs
- Tests/Shared.Specs/EnumAssertionSpecs.cs
Before #1202 we had an asymmetry where:
* `When_comparing_an_enum_and_a_numeric_for_equality_it_should_not_throw` passed, but
* `When_comparing_a_numeric_and_an_enum_for_equality_it_should_not_throw` failed.
After #1202 both of them failed.
This PR makes them both pass to minimize the change of behavior while fixing the asymmetry.
#1204 has a discussion of how to compare enums, integers and strings.
> Fix comparing enums and integers for equality

- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Tests/Shared.Specs/ComparableSpecs.cs
A new pull request for #172 in which all commits have been cleaned up. I struggled with getting Git to behave the way I wanted, but I think this should be it. 
Just to reiterate, this might be a breaking change when released since it does not check CompareTo == 0 anymore. This might be something people depend upon.
> Changed Be/NotBe on IComparable to use Object.Equals and added BeRankedEquallyTo

- .gitignore
- Build/Build.cs
- FluentAssertions.sln
- Tests/Approval.Tests/ApiApproval.cs
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net45.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.3.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.6.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
This adds an extra step to the test stage to verify that the public API does not change unnoticed.
The `approved.txt` files contains a snapshot of the current public API for all supported target frameworks.
From now on all public API changes will require updating the `approved.txt` files.
I intentionally added a API breaking change to verify that the CI build breaks as expected.
Will update the PR once the CI-build turns red as expected.
Fixes #1133
> Add API approval tests

- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Src/FluentAssertions/Xml/XAttributeAssertions.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Src/FluentAssertions/Xml/XElementAssertions.cs
- Src/FluentAssertions/Xml/XmlElementAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeAssertionsofTSubjectTAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net45.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.3.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.6.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
By specifying `because` as an optional parameter we can consolidate 58 existing assertions into 29.
> Consolidate assertion overloads with optional `because` parameter

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net45.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.3.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.6.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/Shared.Specs/TypeAssertionSpecs.cs
The cleanup part of `TypeExtensions.cs` is separated into its own commit.
This fixes #1189
> Change `BeDecoratedWith[OrInherit]` to return an `AndWhichConstraint` with the matched attribute(s)

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net45.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.3.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.6.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/Shared.Specs/AssemblyAssertionSpecs.cs
- Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/Shared.Specs/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/CollectionEquivalencySpecs.cs
- Tests/Shared.Specs/ComparableSpecs.cs
- Tests/Shared.Specs/DictionaryEquivalencySpecs.cs
Change return type from `void` to `AndConstraint` to make the assertions chainable.
I deliberately didn't add tests for `ExecutionTimeAssertions` as time hasn't been abstracted away from it yet.
> Make more assertions chainable

- Src/FluentAssertions/AssertionOptions.cs
- Src/FluentAssertions/Collections/WhichValueConstraint.cs
- Src/FluentAssertions/Equivalency/AssertionContext.cs
- Src/FluentAssertions/Equivalency/CollectionMemberMemberInfo.cs
- Src/FluentAssertions/Equivalency/Selection/NestedSelectionContext.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/OccurrenceConstraint.cs
- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
Probably just a leftover from pre C# 6, where readonly auto properties where introduced.
> Make properties with `private set` truly `readonly`

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Types/MemberInfoAssertions.cs
- Src/FluentAssertions/Types/MethodBaseAssertions.cs
- Src/FluentAssertions/Types/MethodInfoAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net45.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.3.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.6.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/Shared.Specs/Collections/CollectionAssertionSpecs.cs
- Tests/Shared.Specs/Primitives/ReferenceTypeAssertionsSpecs.cs
- Tests/Shared.Specs/Types/MethodBaseAssertionSpecs.cs
- Tests/Shared.Specs/Types/MethodInfoAssertionSpecs.cs
- docs/_pages/releases.md
In https://github.com/fluentassertions/fluentassertions/pull/1067#pullrequestreview-244314223 we kept the parameterless constructors to avoid breaking changes.
Now is the time of breaking changes.
> Prevent constructing Assertions without a `Subject`

- FluentAssertions.sln
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/Shared.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- docs/_pages/releases.md
Added NotContainMatch for string collections which does the opposite of ContainMatch. I recently had a need for NotContainMatch so decided to add it.
> Added NotContainMatch method for string collections and unit tests to cover it

- CONTRIBUTING.md
Currently the contributing markdown file states pull requests should be targeted at `master`, this should be `develop`.
> Changed so contributing file correctly states pull requests should be targeted at develop instead of master

- Tests/Shared.Specs/Equivalency/BasicEquivalencySpecs.cs
In preparation for the new option `ThrowingOnUnexpectedMembers` I am making sure that we fully grasp existing `ThrowingOnMissingMembers` by adding few tests. No tests for this option were present.
> Add tests for `ThrowingOnMissingMembers` equivalency option

- AcceptApiChanges.ps1
- Src/FluentAssertions/Equivalency/AssertionRuleEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/CollectionMemberAssertionOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/ConversionSelector.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidationContextExtensions.cs
- Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/IEquivalencyValidationContext.cs
- Src/FluentAssertions/Equivalency/RunAllUserStepsEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/TryConversionStep.cs
- Src/FluentAssertions/EquivalencyStepCollection.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/Shared.Specs/Equivalency/BasicEquivalencySpecs.cs
- Tests/Shared.Specs/Equivalency/ExtensibilityRelatedEquivalencySpecs.cs
- docs/_pages/releases.md
This implements the functionality as suggested by @jnyrup in #876. 
* If both subject and expectation are `DateTime`s, use the `Using`
* If `WithAutoConversion` is enabled, try to convert subject into the type of expectation
* If, after conversion, both the converted subject and the expectation are `DateTime`s, use the `Using`
Also fixes the API approval script.
> Using/When in BeEquivalentTo will respect the conversion rules. 

- docs/index.html
> Fix spelling on homepage 

- docs/_pages/extensibility.md
I added a simple pointer on how to register your custom `IValueFormatter`.
> Improved extensibility docs for rendering objects

- Src/FluentAssertions/Numeric/NullableNumericAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
Further constraining of `T` to `IComparable<T>` gets us:
* No more runtime type check in constructor
* Avoid (un)boxing of primitives
* Type preserving `Subject`, i.e. `T`/`T?` instead of `IComparable<T>`
> Constrain generic type on NumericAssertions

- Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/Shared.Specs/Types/PropertyInfoSelectorAssertionSpecs.cs
- docs/_pages/releases.md
Add assertion method NotBeWritable to PropertyInfoSelectorAssertions.
Closes #1256
> Add PropertyInfoSelectorAssertions.NotBeWritable

- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Tests/Shared.Specs/Numeric/NumericAssertionSpecs.cs
This pull request fixes issue #1270. NumericAssertionsExtensions.BeApproximately() was not respecting PositiveInfinity and NegativeInfinity for double and float assertions. I added the corresponding tests failing and fixed them.
Although, NumericAssertionsExtensions.NotBeApproximately() was working as expected, I also added the checks for infinity. I added tests for all four methods with positve and negative assertion.
> Fix for issue 1270. BeApproximately now respects positive and negative infinity

- Src/FluentAssertions/Xml/Equivalency/Node.cs
- Src/FluentAssertions/Xml/Equivalency/XmlReaderValidator.cs
- Tests/Shared.Specs/XDocumentAssertionSpecs.cs
- docs/_pages/releases.md
Last year I provided rework of the assertion failure message when comparing XML by introducing XPath index.
Now I found that the current implementation can generate invalid XPath. The index could should apply to the parent.
This PR replaces #1272 to target 5.X
Compare
```xml
<root>
<xml1 />
<xml1><xml2 /><xml2 a=\"x\" /></xml1>
<xml1>
<xml2 />
<xml2 a=\"x\" />
</xml1>
</root>
```
with
```xml
<root>
<xml1 />
<xml1><xml2 /><xml2 a=\"x\" /></xml1>
<xml1>
<xml2 />
<xml2 a=\"y\" /> 
</xml1>
</root>
```
Expected attribute "a" at "/root/xml1[3]/xml2[**2**]" to have value "y", but found "x".
Expected attribute "a" at "/root/xml1[3]/xml2[**4**]" to have value "y", but found "x".
> Fix XPath index calculation for XML comparison

- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/Shared.Specs/Equivalency/ExtensibilityRelatedEquivalencySpecs.cs
- Tests/Shared.Specs/Primitives/DateTimeAssertionSpecs.cs
- Tests/Shared.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
- Tests/Shared.Specs/Primitives/SimpleTimeSpanAssertionSpecs.cs
- docs/_pages/datetimespans.md
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
Whether two time instances are "close" is context dependent and therefore Fluent Assertions should not try to guess a precision.
> Remove overloads of `[Not]BeCloseTo` that has a default precision

- Src/FluentAssertions/Common/MethodInfoExtensions.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/AssertionResultSet.cs
- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Src/FluentAssertions/Xml/XAttributeAssertions.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Tests/Shared.Specs/Xml/XDocumentAssertionSpecs.cs
`IsSameOrEqualTo` is necessary when comparing boxed numerics, e.g. that `1` is equal to `1L`.
`Type` and `XDocument` are not numerics, so this check is pure overhead and can be replaced with either `==` or `Equals`.
`KeyValuePair.Equals` uses `ValueType.Equals(object)` and causes boxing.
This is avoided by converting the `KeyValuePair` into a 2-tuple and compare it against the default 2-tuple.
This is split out from #1258
> Reduce usage of IsSameOrEqualTo

- Src/FluentAssertions/Equivalency/EqualityComparerEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- docs/_pages/releases.md
Adds overloads to the `Using` method of `BeEquivalentTo` options parameter to allows using an implementation of `IEqualityComparer<T>` as an alternative to `IEquivalencyStep`.
Resolves #1236
> Allows using an IEqualityComparer<T> with BeEquivalentTo

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
- docs/_pages/releases.md
- docs/_pages/strings.md
Renamed `StartWithEquivalent` and `EndWithEquivalent` to `StartWithEquivalentOf` and `EndWithEquivalentOf` to make the API for Equivalent methods consistent
Closes #1286
> Renamed [Start|End]WithEquivalent to [Start|End]WithEquivalentOf

- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Primitives/BooleanAssertionSpecs.cs
- docs/_pages/booleans.md
- docs/_pages/releases.md
Add assertion method NotBe to BooleanAssertions.
Closes #1285
> Add BooleanAssertions.NotBe

- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Src/FluentAssertions/Formatting/EnumerableValueFormatter.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- docs/_pages/extensibility.md
- docs/_pages/releases.md
This PR makes  `DefaultValueFormatter` and `EnumerableValueFormatter` more suitable for extending for making it easier to create custom formatters.
> Overriding DefaultValueFormatter and EnumerableValueFormatter

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/NonGenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Src/FluentAssertions/Collections/WhichValueConstraint.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Numeric/NullableNumericAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetRangeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeRangeAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Primitives/NullableBooleanAssertions.cs
- Src/FluentAssertions/Primitives/NullableDateTimeAssertions.cs
- Src/FluentAssertions/Primitives/NullableDateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/NullableGuidAssertions.cs
- Src/FluentAssertions/Primitives/NullableSimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
This PR makes most assertions generic in `TAssertions`.
This benefits deriving from one of those assertion classes, as chaining
with `.And` allows you to continue use assertions from the derived class instead
of only from the base class.
Utilizing the generic type system this way also caught wrong return types.
`NullableDateTimeAssertions.Be` returned an `DateTimeAssertions`, 
where it could return an `NullableDateTimeAssertions`.
Similar "bugs" were also caught in `NullableDateTimeOffsetAssertions` and
`NullableBooleanAssertions`.
Child classes are included to match the current signatures, which is
seen by noticing that all return types of `Should`s remain the same.
The only types that do not have child classes are
* `AndWhichConstraint`
* `DateTimeRangeAssertions`
* …
> Make types generic in `TAssertions`

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Src/FluentAssertions/Collections/WhichValueConstraint.cs
- Src/FluentAssertions/Common/DictionaryHelpers.cs
- Src/FluentAssertions/Common/Guard.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs
- docs/_pages/releases.md
This PR enables using `GenericDictionaryAssertions` on `IReadOnlyDictionary`.
More precisely it enables support for any 
```
TCollection : IEnumerable<KeyValuePair<TKey, TValue>>
```
Added two new overloads:
```c#
Should<TKey, TValue>(IEnumerable<KeyValuePair<TKey, TValue>>)
Should<TCollection, TKey, TValue>(TCollection)
where TCollection : IEnumerable<KeyValuePair<TKey, TValue>>
```
The first one is picked by both:
* `IEnumerable<KeyValuePair<TKey, TValue>>`
* `IReadOnlyDictionary<TKey, TValue>`
The second overload is not picked up by anything and probably never will(?), as being an interface is regarded a better match than being *generic* in an interface.
[Related article](https://dotnetfalcon.com/back-to-the-basics-overload-resolution-in-c/)
Thus not sure if having the second one is …
> Add support for IImmutableDictionary and IReadOnlyDictionary

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Specialized/ActionAssertions.cs
- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertionHelpers.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/NonGenericAsyncFunctionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- docs/_pages/releases.md
This PR enables you to continue asserting on the result of `Func<Task<int>>` when it does not throw.
```c#
Func<Task<int>> func = () => Task.FromResult(42);
func.Should().NotThrow()
.Which.Should().Be(42);
(await func.Should().NotThrowAsync())
.Which.Should().Be(42);
func.Should().NotThrowAfter(10.Seconds(), 1.Seconds())
.Which.Should().Be(42)
(await func.Should().NotThrowAfterAsync(10.Seconds(), 1.Seconds()))
.Which.Should().Be(42);
```
The implementations and tests are mostly copied from the non-generic or sync versions.
To avoid the redefinitions of `Subject` in each class two changes in generics:
* `DelegateAssertions` and `AsyncFunctionAssertions` are now generic in `TAssertions`.
* `AsyncFunctionAssertions` is also generic in `TTask : Task` to support
both `Task` and `Task<T>` …
> Support chaining `NotThrowAfter` and `NotThrowAsync`

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Src/FluentAssertions/Common/CSharpAccessModifierExtensions.cs
- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Src/FluentAssertions/Common/MethodInfoExtensions.cs
- Src/FluentAssertions/Common/ObjectExtensions.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/EnumEqualityStep.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Events/EventHandlerFactory.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- Tests/FluentAssertions.Specs/FindAssembly.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
- Tests/FluentAssertions.Specs/Types/PropertyInfoSelectorSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
Since we've moved away from netstandard 1.3 and 1.6 it's no longer
necessary to call `GetTypeInfo` as `Type` now has all the members we
need.
Also removed some usage of LINQ by using the library method `IsDefined`.
> Remove unnecessary usage of GetTypeInfo

- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Common/Configuration.cs
- Src/FluentAssertions/Common/MethodInfoExtensions.cs
- Src/FluentAssertions/Common/PropertyInfoExtensions.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/PropertySelectedMemberInfo.cs
- Src/FluentAssertions/Execution/ContinuedAssertionScope.cs
- Src/FluentAssertions/Types/PropertyInfoAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Src/FluentAssertions/Xml/XElementAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeAssertionsofTSubjectTAssertions.cs
As pointed out by @lg2de it's difficult to review code when it's sprinkled with boolean literals.
> Use named parameters for boolean literals

- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Src/FluentAssertions/Common/Clock.cs
- Src/FluentAssertions/Common/EnumerableExtensions.cs
- Src/FluentAssertions/Common/TaskExtensions.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/ObjectAssertionsExtensions.cs
- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
This is a clear statement about using `using` statements!
Best viewed ~using IE6 in 1024x768~ ignoring whitespace.
> Use `using` statements to reduce indentation

- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
Not all `Operand`s of `UnaryExpression` are `MemberExpression`s.
I was confused with the naming `AttemptToGetMemberInfoFromCastExpression`, so had to read up on when the `Body` of `Expression<Func<T, TValue>>` would be a `MemberExpression` vs `UnaryExpression`.
https://stackoverflow.com/a/12975480/1087627
Apparently it happens when `TValue` is a value type, that's why I added `int SomeOtherProperty`.
`GetSelectedMemberInfo` wasn't used anywhere, so out it goes.
> NRE for GetPropertyInfo with unexpected Expression

- Src/FluentAssertions/Common/StringExtensions.cs
`StringAssertions.Be[EquivalentTo]` uses an `StringEqualityValidator`
and in there `IndexOfFirstMismatch` to compare if two `string`s are
equal/equivalent.
It had annoyed me for some time that we compared strings characterwise by
slicing of `char`s and converting them to single character `string`s
that we then compare.
The benchmark is calling `IndexOfFirstMismatch` two identical strings using
`Ordinal`/`OrdinalIgnoreCase` and for different lengths.
```
|                  Method |    N |        Comparison | Character |         Mean |      Error |     StdDev | Ratio | RatioSD |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |----- |------------------ |---------- |-------------:|-----------:|-----------:|------:|--------:|--------:|------:|------:|----------:|
| …
```
> Optimize IndexOfFirstMismatch

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
I re-ran my [program](https://github.com/jnyrup/fluentassertions/tree/nullReflection) to find `NullReferenceException`s when entering our library using `Should()`.
So I fixed a few more.
The remaining 76 are here:
[NullReferenceExceptions2.txt](https://github.com/fluentassertions/fluentassertions/files/4499738/NullReferenceExceptions2.txt)
We now have over 4000 tests 🎉
> Guard against NullReferenceExceptions

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
- docs/_pages/collections.md
- docs/_pages/releases.md
> Add NotContainEquivalentOf

- Src/FluentAssertions/Primitives/DateTimeOffsetRangeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeRangeAssertions.cs
- Src/FluentAssertions/Primitives/TimeSpanPredicate.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
- docs/_pages/releases.md
Fixing issue where assertion on `DateTimeRange` will fail on `BeLessThan` or `BeWithin` when the subject and target has a negative delta.
Reported in #1165
> date time range assertions - asserting difference is not negative

- Src/FluentAssertions/EventRaisingExtensions.cs
- Src/FluentAssertions/Events/EventAssertions.cs
- Src/FluentAssertions/Events/EventHandlerFactory.cs
- Src/FluentAssertions/Events/EventMonitor.cs
- Src/FluentAssertions/Events/EventRecorder.cs
- Src/FluentAssertions/Events/FilteredEventRecording.cs
- Src/FluentAssertions/Events/IEventRecording.cs
- Src/FluentAssertions/Events/IMonitor.cs
- Src/FluentAssertions/Events/RecordedEvent.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- docs/_pages/eventmonitoring.md
- docs/_pages/releases.md
* Event constraining extensions `WithArgs` and `WithSender` will return only the events that match the constraints
* Several event raising assertion APIs will return an `IEventRecording` instead of `IEventRecorder` 
* The classes `EventMonitor` and `RecordedEvent` are now treated as `internal` code 
* Renamed method `GetEventRecorder` of interface `IMonitor` to `GetRecordingFor` and will return `IEventRecording`
Fixes #337
> Event constraining extensions WithArgs and WithSender will return matching events

- Src/FluentAssertions/Equivalency/EqualityComparerEquivalencyStep.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Execution/Continuation.cs
- Src/FluentAssertions/Execution/ContinuationOfGiven.cs
- Src/FluentAssertions/Execution/ContinuedAssertionScope.cs
- Src/FluentAssertions/Execution/GivenSelector.cs
- Src/FluentAssertions/Execution/IAssertionScope.cs
- Src/FluentAssertions/Primitives/StringEqualityValidator.cs
- Src/FluentAssertions/Primitives/StringStartValidator.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/.editorconfig
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
- Tests/FluentAssertions.Specs/Execution/IgnoringFailuresAssertionStrategy.cs
- docs/_pages/releases.md
When the initial assertion run through the AssertionScope failed, the chaining API would not ignore any following calls to Given, FailWith, etc. 
Fixes #1302
> Ensure that chained assertion calls are ignored when the preceding one fails

- Src/FluentAssertions/CallerIdentifier.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
We can improve the caller identification a tiny bit without adding complexity.
This fixes #1330
> Improve identification of callers containing Should

- docs/README.md
When I was to try out my changes from #1334 I figured out I need to navigate to the `docs` subfolder to run `bundle install`
> Update README.md to navigate to docs directory

- docs/_pages/tips.md
Added `tips` on how to globally configure `AssertionOptions` for xUnit.net. As discussed in #1323.
The syntax highlighting for the `assembly` part doesn't look really nice since it's untypical C# code. I guess this is the template's limitation?
> Document using global AssertionsOptions for xUnit.net

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Equivalency/ExtensibilityRelatedEquivalencySpecs.cs
- docs/_pages/releases.md
> Allow using custom IOrderingRule

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs
- docs/_pages/collections.md
- docs/_pages/releases.md
> Add AllBe for string collections

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- docs/_pages/collections.md
- docs/_pages/releases.md
This PR adds `NotContainInOrder` assertion as requested in #318.
> Add NotContainInOrder

- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/OccurrenceConstraint.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- docs/_pages/releases.md
Improves library extension interface as requested in #1281.
Some equivalent `ForCondition` usages are replaced with `ForOccurrences` (`StringAssertions.Contain` and `StringAssertions.ContainEquivalentOf`), and as methods containing them covered with unit test, I consider `ForOccurrences` covered enough as well.  
The existence of `{expectedOccurrences}` placeholder is mentioned in documentation comment for `ForOccurrences` method. I don't think it should be in `FailWith` doc comment as it would make it too large and hard to read.
> Add ForConstraint to AssertionScope to open up OccurenceConstraint for usage in custom assertion extensions

- Build/_build.csproj
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
I didn't succeed in #1344 in triggering a CI build, that failed reporting API changes
So I'll try to update ApprovalTests.
I tried skimming it's [diff](https://github.com/approvals/approvaltests.net/compare/5.0.4...master) as it keeps no changelog and there seems to be changes related to CI agents and locating files.
It's a long shot...
> Update test dependencies

- Src/FluentAssertions/Equivalency/FieldSelectedMemberInfo.cs
- Src/FluentAssertions/Equivalency/PropertySelectedMemberInfo.cs
- Src/FluentAssertions/Equivalency/SelectedMemberInfo.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
Now it is not possible to create class in user library inherited from `SelectedMemberInfo` as it contains `internal abstract` members. In this PR i've just make them `public`.
Some additional info:
Creating custom SelectedMemberInfo allow to users create its own inheritors to implement completely different mechanism in IMemberMatchingRule (for example compare values between levels, etc.)
> Allow to override SelectedMemeberInfo in user libraries

- Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
When performing culture sensitive string comparisons:
* .Net Framework and .Net Core on Windows uses NLS, while 
* .Net Core on Linux/MacOS and the upcoming .Net 5.0 uses ICU.
See https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization#net-50
The current test for case sensitive string comparison only worked with NLS, i.e. it is fragile if changing OS or upgrading target framework.
I searched for another pair of characters that showed same behavior as the Mandarin ones, but which works with both ICU and NLS.
So I don't have an explaining why they work, I only observe that serve my purpose and hope they continue to do so.
To verify this I've checked locally that the unit tests works on
* .Net 5.0 preview 6 on windows 10 Version 2004 (the change to ICU happened in [preview …
> Make culture sensitive test less fragile to OS/TFM changes

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- docs/_pages/releases.md
- docs/_pages/strings.md
Adds the following `Should`s to `string`, to assert its casing:
- `BeUpper`
- `NotBeUpper`
- `BeLower`
- `NotBeLower`
Fixes #1356
> Implemented string upper/lower case assertions

- Src/FluentAssertions/Execution/LateBoundTestFramework.cs
- Src/FluentAssertions/Execution/MSTestFrameworkV2.cs
- Src/FluentAssertions/Execution/MSpecFramework.cs
- Src/FluentAssertions/Execution/NUnitTestFramework.cs
- Src/FluentAssertions/Execution/TestFrameworkProvider.cs
- docs/_pages/introduction.md
- docs/_pages/releases.md
If a user request an unsupported test framework via app settings, FA will now throw an exception instead of trying to detect a test framework with `AttemptToDetectUsingDynamicScanning`.
If the requested test framework is not available the failure message will contain the missing assembly name.
In both cases the failure message will contain the names of all supported frameworks.
This fixes #1359
> Improve test framework detection messages

- Src/FluentAssertions/Execution/TestFrameworkProvider.cs
Make `FallbackTestFramework` a *fallback* instead of a *supported* test framework.
With the changes in #1366 this PR introduces a breaking runtime change if a consumer deliberately requested `"fallback"`. 
It will now throw an exception that `"fallback"` is not a supported test framework.
A technical improvement:
* The order of `Dictionary.Value` is unspecified.
* `FallbackTestFramework.IsAvailable` always returns `true`.
So `AttemptToDetectUsingDynamicScanning` *could* chose to pick `FallbackTestFramework` over a real and available test framework.
> Move `FallbackTestFramework` from supported to fallback test framework

- docs/_pages/releases.md
* [+] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [+] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [+] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [+] If the contribution changes the public API the changes needs to be included by running `AcceptApiChanges.ps1`/`AcceptApiChanges.sh`.
* …
> Update release notes: added async version of Where method #1352

- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- docs/_pages/releases.md
When creating a custom assertions class, deriving from `ObjectAssertions<TSubject, TAssertions>` instead of `ReferenceTypeAssertions<TSubject, TAssertions>` gives you `[Not]Be` and `[Not]BeEquivalentTo` for free.
> Make ObjectAssertions generic in TSubject

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Common/CSharpAccessModifierExtensions.cs
- Src/FluentAssertions/Common/InternalObjectExtensions.cs
- Src/FluentAssertions/Common/InternalTypeExtensions.cs
- Src/FluentAssertions/Common/MethodInfoExtensions.cs
- Src/FluentAssertions/Common/PropertyInfoExtensions.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Common/TimeSpanExtensions.cs
- Tests/FluentAssertions.Specs/Common/TypeExtensions.cs
- Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/ExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- Tests/FluentAssertions.Specs/TypeEnumerableExtensionsSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodBaseAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoAssertionSpecs.cs
- docs/_pages/releases.md
Quite some extension methods where part of a `public` class, which caused some people to use them even though they were not designed for that. I had to keep some of them public because they are covered by tests directly.
> Internalized some of the type extensions only meant to be used by FA

- docs/_pages/releases.md
It was difficult to find the official source for the package via the docs. Adding links makes it a bit more clear.
* [NA] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [NA] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [NA] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [NA] If the …
> Added links to nuget for headers

- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/SimpleTimeSpanAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- docs/_pages/releases.md
If a negative `precision` argument is provided, this innocent looking test
```cs
double value = 1.5;
value.Should().BeApproximately(value, -1);
```
fails with the slightly confusing failure message
```
Expected value to approximate 1.5 +/- -1.0, but 1.5 differed by 0.0.
```
Instead explicitly guard against negative `precision`.
Note:
`NumericAssertionsExtensions.BeCloseTo` for integer values uses a unsigned `delta` parameter to guard against negative values.
This fixes #1384
> Guard against negative values as precision arguments

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- docs/_pages/releases.md
The new overloads allows you to use an open generic type.
If both an open and closed type are specified, the closed type takes precedence.
This fixes #1388, #1023
> Added `CompareBy{Members,Value}(Type)`

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- docs/_pages/extensibility.md
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
As primitive types do not have members, it does not make sense to try to compare them by members.
On all but one of the target frameworks two different primitives are currently incorrectly evaluated as being equivalent (#1374).
On net472 it will even hit `"The maximum recursion depth was reached"`.
This PR excludes primitive types from being compared by members.
Thought:
Should we add a guard check in `ComparingByMembers` if someone writes
`ComparingByMembers<int>()` and wonders why `int`s are still not compared by members?
For those interested in the complete set of primitive types, here are the facts from in .netcoreapp3.0 
```cs
AllTypes
.From(typeof(int).Assembly)
.Where(e => e.IsPrimitive)
.Select(e => e.Name)
.ToList();
```
```
"Boolean"
"Byte"
"Char"
"Double"
"Int16"
"Int32" …
```
> Exclude primitive types when comparing by members

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Src/FluentAssertions/Events/EventAssertions.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetRangeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeRangeAssertions.cs
- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Src/FluentAssertions/Types/MethodInfoAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Src/FluentAssertions/Xml/Equivalency/XmlReaderValidator.cs
- Src/FluentAssertions/Xml/XmlNodeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
We had some inconsistencies in:
* How we named the `params object[]` parameter used when formatting the failure message.
* The xml summaries for the `because` and `becauseArgs` parameters.
> Align parameter names and xml summaries

- Src/FluentAssertions/Equivalency/EquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
Initialize EquivalencyAssetionOptions with defaults outside of FluentAssertion.
It can be usefull when you try to use `BeEquivalentTo` inside custom equivalency step with options specified in tests (as `config` parameter).
> Init EquivalencyAssetionOptions with defaults out of FluentAssertion dll

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
Instead of throwing a test failure exception containing "but found <null>", we threw
```
Message: 
System.FormatException : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Stack Trace: 
StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
String.Format(String format, Object[] args)
MessageBuilder.FormatArgumentPlaceholders(String failureMessage, Object[] failureArgs)
MessageBuilder.Build(String message, Object[] messageArgs, String reason, ContextDataItems contextData, String identifier, String fallbackIdentifier)
<>c__DisplayClass30_0.<FailWith>b__0()
AssertionScope.FailWith(Func`1 failReasonFunc) …
```
> Fix format string for null collections

- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- docs/_pages/releases.md
For `String` assertions, `[Not]Match`, `[Not]MatchEquivalentOf`, `[Not]MatchRegex` and `[Not]ContainMatch` no longer accept a `null` or empty string as parameter.
The exception suggests to add a pattern or use one of the `[Not]BeNull`, `[Not]BeEmpty` or`[Not]Contain` methods if that behavior was intended.
Should also close #1243
> Guard  [Not]Match, [Not]MatchEquivalentOf, [Not]MatchRegex and [Not]ContainMatch against null or empty patterns

- docs/_pages/introduction.md
This assertion about all elements verifying a predicate is mentioned in the text but is not in the code example
> To verify that a collection contains a specified number of elements and that all elements match a predicate.
> 
> ```c#
> IEnumerable numbers = new[] { 1, 2, 3 };
> numbers.Should().HaveCount(4, "because we thought we put four items in the collection");
> ```
>
> Add missing example in introduction doc

- Src/FluentAssertions/Collections/CollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
- docs/_pages/releases.md
This PR adds an overloads of `CollectionAssertions.BeEquivalentTo` that takes a `config` parameter.
Since #593 `CollectionAssertions.BeEquivalentTo` no longer used `GetMissingItems`.
https://github.com/fluentassertions/fluentassertions/pull/593/files?file-filters%5B%5D=#diff-4cf34d1b2865162998773f88349aecab.
The same removal should be done here, as `GetMissingItems` relies on `Contains` which checks for equality and not equivalence.
> Add NotBeEquivalentTo with config overload

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- docs/_pages/releases.md
> Make StringAssertions.StartWith and String.StartsWith consistent

- Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionsSpecs.cs
- docs/_pages/releases.md
> Issue 1404: Escape brackets for ContainSingle(...)

- Src/FluentAssertions/Formatting/AttributeBasedFormatter.cs
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
If a method not returning a `string` is decorated with `ValueFormatter` we would throw an `InvalidCastException` when explicitly casting the return value of the `formatter` to `string`.
> Exclude custom ValueFormatters not returning a string

- Src/FluentAssertions/AssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Extensions/FluentActionsSpecs.cs
- docs/_pages/exceptions.md
- docs/_pages/releases.md
> Introduce new overload of Enumerating() (#1431)

- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/NullableDateTimeAssertions.cs
- Src/FluentAssertions/Primitives/NullableDateTimeOffsetAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
- docs/_pages/releases.md
Fixes #1427 
To mimic the behavior of NumericAssertions, I have added the cases marked in bold to `DateTimeAssertions` and `DateTimeOffsetAssertions`. Below examples are for Datetime, but same logic was followed for DatetimeOffset.
| subject       | expected      | result |
| -------       | --------      | ------ |
| 16/11/2020    | 16/11/2020    | true   |
|**16/11/2020**   | **null**          | **false** |
| null          | 16/11/2020    | false  |
| **null**          | **null**          | **true**   |
| subject       | expected      | result |
| -------       | --------      | ------ |
| 16/11/2020    | 16/11/2020             | false  |
| **16/11/2020**    | **null**          | **true**   |
| null          | 16/11/2020    | true   |
| **null**          | **null**          | **false** …
> Fix #1427 Add `DateTime.Should().Be(DateTime?)` and `DateTimeOffset.Should().Be(DateTimeOffset?)` overloads

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- docs/_pages/releases.md
- docs/_pages/strings.md
Visual Studio 2019 supports regex syntax highlighting of `System.Text.RegularExpressions.Regex`.
https://devblogs.microsoft.com/dotnet/visual-studio-2019-net-productivity/#regex-language-support
I want overloads of `StringAssertions.MatchRegex` and `StringAssertions.NotMatchRegex` that take System.Text.RegularExpressions.Regex.
> Add overloads of MatchRegex and NotMatchRegex that take System.Text.RegularExpressions.Regex

- Src/FluentAssertions/Xml/Equivalency/XmlReaderValidator.cs
- Src/FluentAssertions/Xml/XAttributeAssertions.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Src/FluentAssertions/Xml/XElementAssertions.cs
- Src/FluentAssertions/Xml/XmlElementAssertions.cs
- Tests/FluentAssertions.Specs/Xml/XAttributeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlElementAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlNodeAssertionSpecs.cs
- docs/_pages/releases.md
I was triggered by reading #1353 that most XML assertion messages does not include variable name too.
So I've started reworking these assertions to
* include variable name
* provide some useful context information.
While reviewing the texts in the unit tests I found some messages which are misleading because the XmlValidator was following the subject instead of the expectation.
You may want to review the two commits separately.
I'll add changelog when the PR number is available...
Should these two commits result into two statements in the changelog?
> Improve XML assertion messages

- Src/FluentAssertions/Equivalency/GenericDictionaryEquivalencyStep.cs
- Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs
- docs/_pages/releases.md
Sometimes BeEquivalentTo reported an incorrect message when a dictionary was missing a key.
Fixes #145
> When a dictionary does not a key, it should report the right path including the reason

- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Equivalency/EquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- docs/_pages/releases.md
`CallerIdentifier.logger` and `SelfReferenceEquivalencyAssertionOptions.orderingRules` are public fields.
This PR makes them properties instead and pascal case their names.
> Make public fields properties

- Src/FluentAssertions/Data/DataColumnAssertions.cs
- Src/FluentAssertions/Data/DataRowAssertions.cs
- Src/FluentAssertions/Data/DataSetAssertions.cs
- Src/FluentAssertions/Data/DataTableAssertions.cs
- Tests/Benchmarks/LargeDataTableEquivalency.cs
In no other `BeEquivalentTo` methods we wrap the call to `DetermineCallerIdentity` in a `Lazy<T>`.
I ran the example in `LargeDataTableEquivalencyBenchmarks` and `DetermineCallerIdentity` was not hit, so I don't really the purpose of wrapping it.
> Remove unnecessary Lazy wrapping of CallerIdentity

- Src/FluentAssertions/AssertionOptions.cs
- Src/FluentAssertions/Data/DataColumnAssertions.cs
- Src/FluentAssertions/Data/DataEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Data/DataRowAssertions.cs
- Src/FluentAssertions/Data/DataSetAssertions.cs
- Src/FluentAssertions/Data/DataTableAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
The new `CloneDefaults` added in #1419 _assumes_ that `TOptions` has a constructor that takes an `EquivalencyAssertionOptions`.
Instead of assuming the existence of such a constructor, inject a predicate to make it more type safe.
Two other benefits:
* The compiler now easily sees that `DataEquivalencyAssertionOptions` is constructed.
* It's faster to construct and inject a predicate.
```
|            Method |       Mean |    Error |   StdDev | Ratio |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------ |-----------:|---------:|---------:|------:|-------:|-------:|------:|----------:|
|     CloneDefaults | 1,437.0 ns | 27.29 ns | 29.20 ns |  1.00 | 0.4349 | 0.0038 |     - |   2.68 KB |
| CloneDefaultsFunc |   708.4 ns |  5.20 ns |  4.86 ns |  0.49 | 0.3729 | 0.0038 |     - |    2.3 …
```
> Make new `CloneDefaults` less assuming

- Build/_build.csproj
- Src/FluentAssertions/FluentAssertions.csproj
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/Benchmarks/Benchmarks.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
Skipped the FxCop assemblies because bumping them causes deprecation message to appear. See also https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019
> Bumped most dependencies to the latest and greatest

- Src/FluentAssertions/AssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/ExceptionAssertionSpecs.cs
- docs/_pages/releases.md
Add `WithParameterName` extension to assert on the `ParamName` property on `ArgumentException`.
This fixes #1453
> Add WithParameterName

- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
#1463 broke unit tests for the net47 target.
The CI build shows failed tests, but reported "Build success" in the end.
https://ci.appveyor.com/project/dennisdoomen/fluentassertions/builds/37186669
> Downgrade System.Collections.Immutable to fix net47 tests

- build.ps1
Although we bumped Nuke to the v5 version, we never updated the bootstrapping script.
> Diagnosing false positives in AppVeyor

- Src/FluentAssertions/Specialized/TaskCompletionSourceAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
- docs/_pages/releases.md
- docs/_pages/specialized.md
The assertions on `TaskCompletionSource` introduced in #1267 was missing `NotCompletedWithinAsync`.
> Add NotCompleteWithinAsync to TaskCompletionSourceAssertions

- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
To force a method to complete asynchronously we can just use `Task.Yield`.
> Remove 100ms delay from tests.

- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/FluentAssertions.Specs/Equivalency/BasicNonEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
I found some assertions that created failure messages without the provided `because` and `becauseArgs`.
> Add missing reason to failure message

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Common/ObjectExtensions.cs
- Src/FluentAssertions/EnumAssertionsExtensions.cs
- Src/FluentAssertions/Equivalency/EnumEqualityStep.cs
- Src/FluentAssertions/Equivalency/EnumerableEquivalencyStep.cs
- Src/FluentAssertions/Formatting/EnumValueFormatter.cs
- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Src/FluentAssertions/Primitives/NullableEnumAssertions.cs
- Src/FluentAssertions/Types/MethodBaseAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Primitives/EnumAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- docs/_pages/basicassertions.md
- docs/_pages/enums.md
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
- docs/_pages/upgradingtov6.md
New `EnumAssertions` to follow up #1375 and to solve #1204
`Be()` now expects an expectation of the same type of enum, which was an issue that gave false negatives, e.g. #1403.
More lightweight/relevant IntelliSense as it doesn't inherit assertion methods from `ReferenceAssertions`.
Before:
After:
I've excluded `[Not]BeEquivalentTo(object)` as all cases that I can think of are now covered by:
* `[Not]HaveSameValueAs`
* `[Not]HaveSameNameAs`
* `[Not]HaveValue(decimal)`
One question that remains for me, it whether it is too confusing that `HaveValue` is both used in:
* `NullableEnumAssertions` to assert if it is not null, and in
* `EnumAssertions` to assert on the underlying numeric value.
cc: @lg2de
This fixes #1204 
This fixes #1403
> Rework EnumAssertions

- Src/FluentAssertions/Equivalency/AssertionContext.cs
- Src/FluentAssertions/Equivalency/AssertionRuleEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Equivalency/ExtensibilityRelatedEquivalencySpecs.cs
- docs/_pages/releases.md
- docs/_pages/upgradingtov6.md
Restrict `WhenTypeIs<TMemberType>` to types assignable to `TMember`.
This should catch `NullReferenceException` or `InvalidCastException` in `CreateFromEquivalencyValidationContext` at compile-time.
The snippet below might have worked, but it assumes that the subject and expectation are both non-null.
```cs
.Using<int>()
.WhenTypeIs<int?>()
```
Instead, you now have to make this assumption more explicit by using `Nullable<int>.Value` 
```cs
Using<int?>(e => e.Subject.Value.Should().Be(e.Subject.Value))
```
Make `WhenTypeIs<TMemberType>` optional unless when chaining further.
For the most cases `TMemberType` is exactly `TMember` and in those cases `WhereTypeIs<>()` is noisy.
By adding an implicit cast operator we can avoid that.
The exception being when we need more chaining after …
> Improve `Using<TMember>`

- Src/FluentAssertions/AsyncAssertionsExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- docs/_pages/executiontime.md
- docs/_pages/releases.md
- docs/_pages/specialized.md
While further development of tests using async assertions (async methods and TaskCompletionSource) I found that asserting the result is not as fluent as possible.
Therefore I provide new idea to assert the result.
If you agree I'll complete with
* extention method for Task<AndWhichConstraint<GenericAsyncFunctionAssertions<TResult>, TResult>>
* documentation, release notes, etc.
* api validation update
> Add WithResult to TaskCompletionSourceAssertion

- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
Since the introduction of `StringCollectionAssertions` in #42 `Contain(IEnumerable<string>)` have had an extra `object becauseArg` argument.
I can only speculate that it had to do with overload resolution to avoid breaking changes.
> Simplify signature of `[Not]Contain(strings)`

- Src/FluentAssertions/Equivalency/EquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- docs/_pages/releases.md
In 69c5231d79847fccb8611afb1fc1cbe5960a345f `SelfReferenceEquivalencyAssertionOptions` was split into a generic and non-generic part, where the non-generic is used for the `defaults` in `AssertionOptions`.
`Excluding(Expression<Func<IMemberInfo, bool>> predicate)` was kept in the shared base class, but `Including(Expression<Func<IMemberInfo, bool>> predicate)` was moved to the generic child class, even though it does not rely on the generics.
With the change in this PR one can now write a test like
```cs
AssertionOptions.AssertEquivalencyUsing(e => e.Excluding(_ => true).Including(e => e.Name == "IncludeMe"));
var subject = new { IncludeMe = "Foo", ExcludeMe = "Bar" };
var expected = new { IncludeMe = "Foo", ExcludeMe = "Baz" };
subject.Should().BeEquivalentTo(expected);
```
> Move Including from EquivalencyAssertionOptions to SelfReferenceEquivalencyAssertionOptions

- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Execution/FailReason.cs
- Src/FluentAssertions/Execution/GivenSelector.cs
- Src/FluentAssertions/Execution/IAssertionScope.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
- docs/_pages/releases.md
Discussed [here](https://github.com/fluentassertions/fluentassertions/discussions/1509) - I thought I'd contribute a potential solution.
My personal use case is that I've got some costly calculations to display user-friendly failure info, and I'd like to avoid doing this for the 99% case where the tests run successfully.
> AssertionScope - allow reportables which are only calculated on failure

- Src/FluentAssertions/Equivalency/GenericDictionaryEquivalencyStep.cs
- Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs
In c847f3cc `When_an_object_implements_two_IDictionary_interfaces_it_should_fail_descriptively` was changed to asserting that it didn't throw an exception.
It looks as a mistake to me.
The error in the context pattern was introduced in d2e61fc5 but `When_an_object_implements_two_IDictionary_interfaces_it_should_fail_descriptively` no longer caught the error.
> Fix context pattern in error message when implementing multiple interfaces

- Src/FluentAssertions/Collections/MaximumMatching/MaximumMatchingSolver.cs
- Src/FluentAssertions/Common/StringExtensions.cs
- Src/FluentAssertions/Equivalency/EnumEqualityStep.cs
- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/Matching/TryMatchByNameRule.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Tests/FluentAssertions.Specs/Equivalency/ExtensibilityRelatedEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
C# 9.0 brought two new features we can use to simplify the code a bit.
* [Target-Typed Conditional Expression
](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-conditional-expression)
* [Lambda discard parameters
](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/lambda-discard-parameters)
For three-valued boolean logic in C# we can utilize [lifted operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#lifted-operators) to simplify the expressions.
For IL/ASM interested [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQMwAJMCMAbLvgEy4DCuAsAFADe9ppA9K7gMYCuATrwFMYCZixz5iuYAHtpAG1wA5aQgBCAynOkoBAFWkAKWAgD8uCHFzHcWgO4Del69wAOLhwEpcAXgB …
> Simplify code with C# 9 features

- Src/FluentAssertions/Execution/NSpecFramework.cs
- Src/FluentAssertions/Execution/TestFrameworkProvider.cs
- Src/FluentAssertions/Execution/XUnit2TestFramework.cs
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
A colleague who had "Just My Code"  in VS disabled wondered why he saw an assembly not found exception for nspec.
When I implemented this in #702 I probably just copied the xunit approach, but it _needs_ to use `Assembly.Load` for netfx #384.
For nspec this does not seems necessary and we can use the non-throwing from `LateBoundTestFramework`
I've checked the build pipeline locally that both targets of xunit are run.
> Scan AppDomain to detect nspec assembly

- README.md
- docs/_pages/about.md
- global.json
.NET SDK 5.0.200 added support for OR_GREATER preprocessor directives
to simplify multi-targeting.
https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.3/5.0.200-sdk.md#notable-changes
Is "current minimum required version" correct grammar ❓
> Update minimum .NET SDK to support OR_GREATER

- Build/Build.cs
- Src/FluentAssertions/FluentAssertions.csproj
Enable SourceLink and Deterministic builds:
* Two more green badges in Nuget Package Explorer
* Size reduction (1.50 MB -> 1.14 MB) since pdb files are no longer embedded in nupkg, but only downloaded on demand.
Possible downsides/caveats:
* Only nuget.org has a symbol server (this might not be true anymore), this is only a problem if we want to switch/add provider.
* You can't step through FA while being offline (unless the symbols are cached somewhere locally)
* Your IDE is too old to have support for symbols servers (before Visual Studio 2017 version 15.9)
* Your IDE isn't set up to download symbols from the nuget symbol server (before Visual Studio 2019 version 16.1)
The limitations of snupkg in contrast to pdb
> * They do not currently support Windows PDBs (generated by VC++, or for …
> Create SourceLink-Enabled and Deterministic nupkg

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
While working on generic collections I spotted this code and it wasn't hit by any tests.
The special casing for `string`s was added in 68f224a5 in 2010-03-15
The tests added in that commit now hits`StringCollectionAssertions`.
`StringCollectionAssertions` was first added in 4e8f844f 2013-12-05
> Remove pre-StringCollectionAssertions code

- Src/FluentAssertions/Equivalency/EnumEqualityStep.cs
`When_subject_is_null_and_enum_has_some_value_it_should_throw` threw an NRE as `FailWith` does not throw immediately.
I can't think of a test to verify this fix as the outcome is unchanged,
> EnumEqualityStep throws NRE for null subject

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
In #1529 I missed removing non-generics from `[Not]HaveSameCount`.
> Make [Not]HaveSameCount generic only

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Common/DictionaryHelpers.cs
- Src/FluentAssertions/Common/ObjectExtensions.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Tests/Benchmarks/Benchmarks.csproj
- Tests/Benchmarks/CollectionEqual.cs
- Tests/Benchmarks/Program.cs
- Tests/FluentAssertions.Specs/AndWhichConstraintSpecs.cs
- Tests/FluentAssertions.Specs/Extensions/ObjectExtensionsSpecs.cs
In #840 I did some optimizations for `Equal` to avoid some boxing value types, but we can do even better!
This PR does two things:
* Avoid all boxing for value types in the comparison method.
* Only perform `CompareNumerics` when `T` is `object`.
*  This is a generous fallback for comparing boxed numerics.
I picked `net472` as the worst case TFM we support and `net5` as the best case.
`Develop` 
```cs
collection1.Should().Equal(collection2)
```
`Develop_CustomComparer` 
```cs
collection1.Should().Equal(collection2, (a, b) => a == b)
```
`PR`
```cs
collection1.Should().Equal(collection2, ObjectExtensions.GetComparer<int>())
```
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-10750H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.300-preview.21180.15 …
```
> Avoid boxing when comparing for equality

- Src/FluentAssertions/Xml/XmlElementAssertions.cs
- Tests/FluentAssertions.Specs/Xml/XmlElementAssertionSpecs.cs
- docs/_pages/releases.md
If `HaveElement` is called without a namespace, ignore it when looking for a child element
Fixes #1523
> Ignore the namespace if it is not specified

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Streams/BufferedStreamAssertions.cs
- Src/FluentAssertions/Streams/StreamAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Streams/BufferedStreamAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Streams/StreamAssertionSpecs.cs
- docs/_pages/releases.md
- docs/_pages/streams.md
Added for `Stream`
* `[Not]BeWritable`
* `[Not]BeSeekable`
* `[Not]BeReadable`
* `[Not]BeReadOnly`
* `[Not]BeWriteOnly`
* `[Not]HaveLength`
* `[Not]HavePosition`
Added for `BufferedStream`
* `[Not]HaveBufferSize`
> Add assertions for (Buffered)Stream

- docs/_sass/minimal-mistakes/_footer.scss
- docs/_sass/minimal-mistakes/_page.scss
The sticky footer overlaps and conceals content on nearly every page.
There are [several ways to make sticky footers][1]. Replace the current one with a grid variant. It's not strictly necessary to fix the footer's position in the grid as long as the DOM has the desired element order.
[1]: https://css-tricks.com/couple-takes-sticky-footer/
This makes
look more like
I've checked
* wide screens
* narrow screens
* short content
* long content
* search box (which I'm not sure does anything...?)
> Fix sticky footer overlapping content

- Src/FluentAssertions/Common/Guard.cs
- Src/FluentAssertions/Types/MethodInfoAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs
- docs/_pages/releases.md
Inspired by #1039
* Check for Subject to be null
* Check parameters types for null (or empty)
* Check enum parameters types for out-of-range values
* Add covering unit tests
* Add possible exceptions to XmlDoc
* Try to get more consistent function/test layout
* Try to get more consistent documentation
* ~~replace "to not exist" with "not to exist", [both are valid](https://www.learnersdictionary.com/qa/to-not-be-or-not-to-be) but this feels more fluent to me, but maybe it is just taste.~~
* Condense tests
Status:
> Make type assertions more robust

- Src/FluentAssertions/Types/MemberInfoAssertions.cs
- Src/FluentAssertions/Types/MethodBaseAssertions.cs
- Src/FluentAssertions/Types/MethodInfoAssertions.cs
- Tests/FluentAssertions.Specs/Types/MethodBaseAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoAssertionSpecs.cs
- docs/_pages/releases.md
* Added Guards against null parameters
> Robust methodinfo assertions

- Src/FluentAssertions/Types/MemberInfoAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoAssertions.cs
- Tests/FluentAssertions.Specs/Types/PropertyInfoAssertionSpecs.cs
- docs/_pages/releases.md
* Added failure message when `Subject` is null
* Added `Guards` against `null` parameters
> Robust PropertyInfo assertions

- Src/FluentAssertions/Specialized/AssemblyAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/AssemblyAssertionSpecs.cs
- docs/_pages/releases.md
* Added Guards against null parameters
> Robust Assembly assertions

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/TypeExtensions.cs
- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
- docs/_pages/releases.md
Follows the changes made in #1565
* Added Guards against null parameters
Will need a rebase after #1565 is merged.
> Guard MethodInfoSelector(Assertions) against null reference exceptions

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/CollectionMemberAssertionOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/IsExternalInit.cs
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
* By default, records are compared by their members
* This can be overridden by `ComparingRecordsByValue` or `ComparingByValue<T>`
* Also improved the reporting on how types with members are compared.
Fixes #1451
> Add first-class support for C# 9.0 records

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Common/Guard.cs
- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
- Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
> Robust TypeSelector Assertions

- .editorconfig
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
- Tests/FluentAssertions.Specs/.editorconfig
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
These changes try to align IDE experiences of Rider and VS to avoid changes being added/deleted over and over in order to satisfy one of the IDEs.
ReSharper is (naturally) vague in when method groups are beneficial over lambda expressions.
Roslyn caches construction of lambdas of static functions, see
[SharpLab.io](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTCDMACZPAOQHsYBhCAYwAsBTAE0wG9M928AHAJygDcIAFzrtYgvAHE6ggBRi8UAJR4AvAD4FeANR4UAbkxsOPfkJHyAqgGc6AGQhhgDCDIQBWADxiANApiCNHkYoKjNldS5uYNDhGQAWJEUDLAwOAnx5ezBnGXCNazsHJxcRCKlZOkUko3Ya9L9xAFlpGhIGCW4SAFdOXNV8myzimXLqjABfQwxcAiQ8SlpGFjqTAWECFAA2BslpOX8FPM0dfSm01bMdgqGc9y9/XzFAqIYQsP7I6LN4xOS6mcyDhyR2uRRypQ05RklTGaX+GQOzUErXanR6fQioMcOVGyXGQA==)
I've benchmarked the difference between using a lambda and method group for static …
> Analyzer suppressions

- Src/FluentAssertions/Streams/BufferedStreamAssertions.cs
- Src/FluentAssertions/Streams/StreamAssertions.cs
- Tests/FluentAssertions.Specs/Streams/BufferedStreamAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Streams/StreamAssertionSpecs.cs
When an assertion on a stream was wrapped in an `AssertionScope` we would continue executing after a null check failed and get an NRE.
We could consider always augmenting our null tests with an enclosing `AssertionScope` to verify the null-safeness.
That's why I hijacked the original null tests for stream assertions.
cc: @eNeRGy164
> Make StreamAssertions null-safe to being wrapped in an AssertionScope

- Src/FluentAssertions/Common/EnumerableExtensions.cs
- Src/FluentAssertions/Equivalency/StringEqualityEquivalencyStep.cs
- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Src/FluentAssertions/Primitives/StringValidator.cs
For Booleans both operators are equivalent ways of expressing
"one but not both".
According to review comments the latter way is more readable.
> Replace xor with inequality operator

- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/Formatting/XmlReaderValueFormatter.cs
- Src/FluentAssertions/Xml/Equivalency/XmlReaderValidator.cs
- Src/FluentAssertions/Xml/XAttributeAssertions.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Src/FluentAssertions/Xml/XElementAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Xml/XAttributeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
- docs/_pages/releases.md
* Added Guards against null parameters
> Robust XML assertions

- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
When a property is invoked via `PropertyInfo.GetValue` and the the property, the exception is wrapped in a `TargetInvocationException`. 
This PR unwraps such exceptions a single level, to get the actually thrown exception.
> Improve formatting excepting properties

- Src/FluentAssertions/Formatting/DictionaryValueFormatter.cs
- Src/FluentAssertions/Formatting/Formatter.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- docs/_pages/releases.md
Copied and adjusted the `EnumerableValueFormatter` to handle instances of `IDictionary`.
With the addition of `DictionaryValueFormatter` the output of the included `When_formatting_a_dictionary_it_should_format_keys_and_values` changes from
```
{[FluentAssertions.Specs.Formatting.FormatterSpecs+MyKey, FluentAssertions.Specs.Formatting.FormatterSpecs+MyValue]}
```
to
```
{[
FluentAssertions.Specs.Formatting.FormatterSpecs+MyKey
{
KeyProp = 13
}] = 
FluentAssertions.Specs.Formatting.FormatterSpecs+MyValue
{
ValueProp = 37
}
}
```
Part of fixing #1527
> Add Formatter for IDictionary

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
Fixes NRE's in `StringAssertions` that were report in #1039
> Make StringAssertions null-safe to being wrapped in an AssertionScope

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Specialized/ExecutionTime.cs
- Src/FluentAssertions/Specialized/MemberExecutionTime.cs
- Tests/FluentAssertions.Specs/Exceptions/ExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
Discovered some additional NRE's when investigating #1039
* `Invoking`
* `ExecutionTime`
* `ExecutionTimeOf`
> Improve execution assertions

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- docs/_pages/exceptions.md
- docs/_pages/strings.md
Improves the documentation of wildcards for `[Not]Match`, `[Not]MatchEquivalentOf` and `WithMessage`.
Also fixes #1570
> Improve wildcard documentation

- Src/FluentAssertions/Equivalency/DataColumnEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/DataRelationEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/DataRowCollectionEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/DataRowEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/DataSetEquivalencyStep.cs
In 44efddb454397f15c50068ca5b5245b4542317db `ShouldExcludeColumn` threw an NRE when `subjectColumn` was null.
This is now null guarded to avoid checking whether a non-existing column should be excluded.
A few lines below `subjectColumn` and `expectationColumn` are compared and potential null values are taken into account.
In 03fffcd `DataRowCollectionEquivalencyStep.OnHandle` did check `subject.Count == expectation.Count` before invoking `MatchRowsByIndexAndCompare` which threw an `IndexOutOfRangeException`, but it didn't take into account being on a continuing `AssertionScope`.
I also added some more `AssertionScope` guards to the `DataSet` related classes in 03fffcd.
This fixes #1530
> Harden DataSet types against a continuing AssertionScope

- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/WhoseValueConstraint.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- docs/_pages/releases.md
I realize this has sort of been discussed in #577 and #1126, but without any real conclusion, which I think is unfortunate. However, in the case of WhichValue (on a dictionary), there can never be any ambiguity and "Which" will always be the wrong word. It could be argued that it should rather be something like "WhoseCorrespondingValue", since the Value does not belong to the Key, but that's a bit long.
> Rename WhichValue to WhoseValue

- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- docs/_pages/collections.md
Follow up on #1586, missed the `[Not]ContainsMatch` methods on `StringCollectionAssertions`.
> Improve wildcard documentation on collections

- Src/FluentAssertions/Execution/GivenSelector.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
- docs/_pages/releases.md
In a chained assertion API call, a second call to ForCondition should not even evaluate its lambda when the previous assertion failed.
Fixes #1568
> A succeeding condition should not be evaluated if the first one failed

- Tests/Benchmarks/Benchmarks.csproj
During a build, the Benchmark project generates warnings about `System.Data.DataSetExtensions`.
Adding a condition should fix this warning.
> Fix build warning

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/CollectionMemberAssertionOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/MemberSelectionContext.cs
- Src/FluentAssertions/Equivalency/MemberVisibility.cs
- Src/FluentAssertions/Equivalency/Selection/AllFieldsSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/AllPropertiesSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPredicateSelectionRule.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
`BeEquivalentTo` will no longer include `internal` properties and fields, unless `IncludingInternalProperties` or `IncludingInternalFields` is used
Fixes #1205, #744
> Optionally include internal members in equivalency assertions

- Src/FluentAssertions/Numeric/NullableNumericAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Src/FluentAssertions/Primitives/NullableEnumAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
In #1266 I changed `NullableNumericAssertions` to have a property `T? Subject` and its base class `NumericAssertions` to have a `T Subject`.
What I (presumably) didn't consider back then was extensibility.
Maybe I was fooled by `NumericAssertionsExtensions` which casted `Subject` (which used to be of type `IComparable`) to the primitive numeric type. 
If I create an extension method on `NumericAssertions` and call it on an instance of the derived `NullableNumericAssertions` it could throw an unexpected exception, if it tried to get an `int` from a `null`.
Exemplified in code
```cs
((int?)null).Should().Do();
public static void Do<T, TAssertions>(this NumericAssertions<T, TAssertions> assertions)
where T : struct, IComparable<T>
where TAssertions : NumericAssertions<T, TAssertions>
{
T …
```
> Use the same Subject nullable and non-nullable type

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionSatisfyAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ReferenceTypeAssertionsSpecs.cs
Working on #1039
**ReferenceTypeAssertions**
**StringCollectionAssertions**
**GenericCollectionAssertions**
Also small updates to documentation tags where appropriate.
> Guard more assertions against null subject variables.

- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/GuidAssertionSpecs.cs
- docs/_pages/guids.md
- docs/_pages/releases.md
* Added parameter checking to `Be`
* Added `NotBe` for symmetry.
Should close #1553
> Add Guid .Be input checking and .NotBe

- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Execution/ContinuedAssertionScope.cs
- Src/FluentAssertions/Execution/FailReason.cs
- Src/FluentAssertions/Execution/GivenSelector.cs
- Src/FluentAssertions/Execution/IAssertionScope.cs
- docs/_pages/releases.md
* Used `<inhertdoc/>` where possible
* Added paragraphs to make long text more readable
* Added emphasis for certain words
* Shortened references where possible
Close #1605
> Make xml documentation more consistent for AssertionScope and friends

- Src/FluentAssertions/Execution/ContinuedAssertionScope.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
- Tests/FluentAssertions.Specs/Execution/GivenSelectorSpecs.cs
- docs/_pages/releases.md
When digging into `AssertionScope` for #1596 I was missing a lot of specs to describe the expected behavior (hence #1599).
* Added specs for many methods/behaviors
* Fixed handling of `WithDefaultIdentifier` and `WithExpectation` after continuation
For the most recent commits I tried to follow [Making Better Unit Tests Part 2: Naming Unit Tests](https://codeburst.io/making-better-unit-tests-part-2-naming-unit-tests-8a7279c3ea4)
> Improve continuation of AssertionScope and add specs

- Src/FluentAssertions/FluentAssertions.csproj
- Tests/Approval.Tests/ApiApproval.cs
> Remove the custom output path

- Src/FluentAssertions/Common/ExceptionExtensions.cs
- Src/FluentAssertions/Equivalency/Steps/GenericEnumerableEquivalencyStep.cs
- Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs
- docs/_pages/releases.md
This fixes #1613.
When an instance to compare throws an exception during the invocation of the HandleMethod in the Handle method of GenericEnumerableEquivalencyStep, the TargetInvocationException is unwrapped (to give the innermost exception) and rethrown. This previously lead to a wrong stack trace that would indicate, that something is wrong in GenericEnumerableEquivalencyStep.
The first commit provides a test that shows this.
The second commit fixes it by using ExceptionDispatchInfo to capture the stack trace. Since the class ExceptionExtensions is internal, the signature change of the Unwrap method is not changing the public API.
If you do not like the change of the method signature, there is a hack to keep it.
I read that I should add this fix to the release notes. In this branch or …
> Improved Stack Trace for Collection Comparison

- Src/FluentAssertions/Formatting/DateTimeOffsetValueFormatter.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Formatting/DateTimeOffsetValueFormatterSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
- docs/_pages/datetimespans.md
- docs/_pages/releases.md
Not quite ready yet. More a basis for discussion.
The value formatting was one issue. I don't think the offset should be hidden, even if it's zero. It's no less significant than a positive or negative offset.
The assertion could perhaps be made with a Then step and a "...but the offsets differ" message.
> Add new BeExactly assertions for DateTimeOffset

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
- Src/FluentAssertions/Numeric/NullableNumericAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeDecoratedWith.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeDecoratedWithOrInherit.cs
- Tests/FluentAssertions.Specs/Types/TypeSelectorAssertionSpecs.cs
- docs/_pages/releases.md
Many predicate assertions uses `predicate.Body` to format their messages, thereby circumventing the formatting offered by `PredicateLambdaExpressionValueFormatter`.  More specifically, it's the part which resolves constant values which is sorely missing, e.g when using `collection.Should().Contain(x => x.Name == expectedName && x.Value == expectedValue)`.
This could be fixed by adding a new formatter or modifying the existing, but I think it makes more sense to provide the full lambda to the formatter.
Possible additions would be:
1. Include the lambda parameter part in the output. 
2. ...or removing it when possible, outputting `Name == "Expected"` instead of `a.Name == "Expected"`
3. ...and/or renaming the lambda parameter, e.g so that its always named "item", when used in a collection …
> Homogenize predicate formatting

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Common/ITimer.cs
- Src/FluentAssertions/Common/StartTimer.cs
- Src/FluentAssertions/Common/StopwatchTimer.cs
- Src/FluentAssertions/Specialized/ExecutionTime.cs
- Src/FluentAssertions/Specialized/MemberExecutionTime.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/TestTimer.cs
On AppVeyor builds, we have observed some flakiness where timing a simple `Thread.Sleep(200)` can result in up to 400 milliseconds of execution time. For those specific unit tests, we have decided to replace `Stopwatch` usage with a fake timer abstraction for those specific cases. For the other execution timing tests, I've decided to keep using the real `Stopwatch`.
Fixes #1085
> Faking time because timing executions can be flaky on AppVeyor

- Src/FluentAssertions/Equivalency/Field.cs
- Src/FluentAssertions/Equivalency/Node.cs
- Src/FluentAssertions/Equivalency/Property.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/DataEquivalencySpecs.DataColumn.cs
- Tests/FluentAssertions.Specs/Equivalency/DataEquivalencySpecs.DataRow.cs
- Tests/FluentAssertions.Specs/Equivalency/DataEquivalencySpecs.DataSet.Typed.cs
- Tests/FluentAssertions.Specs/Equivalency/DataEquivalencySpecs.DataSet.cs
- Tests/FluentAssertions.Specs/Equivalency/DataEquivalencySpecs.DataTable.Typed.cs
- Tests/FluentAssertions.Specs/Equivalency/DataEquivalencySpecs.DataTable.cs
- Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/ExtensibilityRelatedEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/XmlEquivalencySpecs.cs
- docs/_pages/releases.md
Because the equivalency validator will use the expectation to traverse the object graph, the `INode.Type` property (and the `Description` derived from that) always refers to the type of the node from the perspective of the expectation. But this was sometimes used to refer to the subject's node, causing weird failure messages where the type matched the expectation but not the subject.
> Removed the type from the failure message in equivalency checks

- Src/FluentAssertions/Common/TypeExtensions.cs
All callers was removed with #1621
(I did wonder why mutation testing marked this entire method as completely untested)
> Remove ToFriendlyName

- FluentAssertions.sln.DotSettings
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/Steps/DictionaryInterfaceInfo.cs
- Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
- Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs
- docs/_pages/releases.md
Because of some accidental design choices, in previous releases, when the expectation is a dictionary, it was picked up by the `GenericEnumerableEquivalencyStep`. This resulted in an `IDictionary<TKey, TValue>` being treated as a collection of `KeyValuePair<TKey, TValue>`. In 6.0, some of the semantics of the equivalency steps changed in such a way that a dictionary is now picked up by the `GenericEquivalencyStep`. This is expected, but had the side-effect that when a dictionary is expected, it really expects a dictionary. 
This PR changes `GenericEnumerableEquivalencyStep` so it tries to convert a collection of key-value pairs back to a dictionary and then does the equivalency check.
Fixes #1598
> A collection of similarly typed key-value pairs should be equivalent to a dictionary

- Src/FluentAssertions/Equivalency/Node.cs
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs
- docs/_pages/releases.md
When a collection is compared using `BeEquivalentTo`, and the items in that collection point to a class without members, FA would throw the `No members were found for comparison.` exception. This was caused by the `IsRoot` property that was interpreting the member path incorrectly. It assumed that if the path started with `[`, we were looking at the root. But even if the path started with `[0].SomeProperty`, it would treat the current `INode` as "root". 
Fixes #1604
> Fixed a regression where a nested class without suitable members inside a collection throws

- Src/FluentAssertions/Equivalency/Steps/DictionaryInterfaceInfo.cs
- Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
- Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs
Reviewing #1603 revealing nothing problematic to me, but we can save a call to the `ConcurrentDictionary` `Cache` by using `GetOrAdd` instead.
... and some analyzer/styling nits.
> Avoid double call to concurrent dictionary by using GetOrAdd

- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Src/FluentAssertions/Common/MemberPath.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/Field.cs
- Src/FluentAssertions/Equivalency/IMember.cs
- Src/FluentAssertions/Equivalency/Property.cs
- Src/FluentAssertions/Equivalency/Selection/AllPropertiesSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/ExcludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/FluentAssertions.Specs/Types/MethodBaseAssertionSpecs.cs
- docs/_pages/releases.md
`Excluding()` or `Including()` covariant properties in a `BeEquivalentTo` call didn't work. To reproduce this, I had to include .NET 5 to the frameworks the unit test project targets. Also, covariant properties behave completely different from normal properties. In fact, from a Reflection point of view, it looks like a covariant property is a completely different property, a bit like `new` properties. See also this [SO thread](https://stackoverflow.com/questions/68592010/how-to-find-the-base-class-property-of-a-covariant-property-override-in-c-sharp?noredirect=1#comment121223522_68592010). 
Then while looking at #1363, I discovered another problem. Simply calling `GetProperties` on a hierarchy that includes covariant or "new" properties will also include the hidden properties, causing …
> Support covariant and inherited property exclusion and inclusion in BeEquivalentTo

- docs/_pages/releases.md
API changed during PR review, but releases wasn't updated accordingly.
> Fix typo in NotContainEquivalentOf

- Src/FluentAssertions/AssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/AssemblyA/ClassA.cs
- Tests/AssemblyB/ClassC.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.Be.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs
- docs/_pages/releases.md
This is an attempt to help people when they write `.Should()` directly after `.And` by throwing an exception.
As classes with assertions are not decorated with something to recognize (e.g. a shared base class or interface) I use reflection to get all the return types for `Should` methods on the `AssertionExtensions` class.
Had to rewrite unit tests that were using `ObjectAssertions` to test cross-assembly type comparison as they would also fail with the new exception.
Should fix #1617
> Throw when asserting on AndConstraint

- Src/FluentAssertions/ExceptionAssertionsExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- docs/_pages/releases.md
Adds extension method for the remaining method `WithInnerExceptionExactly` for `ExceptionAssertions<T>` when using `ThrowAsync`.
Closes #1400
> Add extension method `WithInnerExceptionExactly` for async exception assertions

- docs/_pages/eventmonitoring.md
> Fix small grammatical error

- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Src/FluentAssertions/Data/DataColumnAssertions.cs
- Src/FluentAssertions/Data/DataRowAssertions.cs
- Src/FluentAssertions/Data/DataSetAssertions.cs
- Src/FluentAssertions/Data/DataTableAssertions.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
- docs/_pages/releases.md
This was caused by the increased dependency on the CallerIdentifier, and the additional work caller identification takes in v6.
#1657
> Resolved a significant performance degradation in `BeEquivalentTo`

- .gitignore
- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Equivalency/Steps/StringEqualityEquivalencyStep.cs
- Src/FluentAssertions/Execution/MessageBuilder.cs
- Tests/Benchmarks/Benchmarks.csproj
- Tests/Benchmarks/CollectionEqual.cs
- Tests/Benchmarks/Issue1657.cs
- Tests/Benchmarks/Program.cs
More optimizations in addition to #1660 
#1657 
Benchmark results:
**#1660**
```
|              Runtime |  N |         Mean |       Error |      StdDev |      Gen 0 |     Gen 1 |  Allocated |
|--------------------- |--- |-------------:|------------:|------------:|-----------:|----------:|-----------:|
|             .NET 5.0 |  1 |     219.9 us |     0.86 us |     0.76 us |    26.6113 |    1.2207 |     164 KB |
| .NET Framework 4.7.2 |  1 |     276.5 us |     1.54 us |     1.36 us |    28.8086 |    0.9766 |     178 KB |
|             .NET 5.0 | 10 |  11,887.3 us |    98.84 us |    92.45 us |  1546.8750 |  140.6250 |   9,535 KB |
| .NET Framework 4.7.2 | 10 |  16,133.7 us |    31.25 us |    27.71 us |  1875.0000 |  156.2500 |  11,552 KB |
|             .NET 5.0 | 50 | 302,525.7 us | …
```
> Optimize BeEquivalentTo

- global.json
Allow the next major SDK (NET 6 atm)  to compile the solution
> Allow NET 6 SDK to compile project

- docs/_pages/introduction.md
Simply fixing the broken link to `AssertionScopeSpecs.cs` on the introduction page.
> Fix link to `AssertionScopeSpecs.cs`

- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
In 86dcaccf the test body was changed to assert success, but the method name was not changed accordingly.
> Fix name of test

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.HaveCountGreaterThanOrEqualTo.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.HaveCountLessThanOrEqualTo.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/SimpleTimeSpanAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- docs/_pages/collections.md
- docs/_pages/datetimespans.md
- docs/_pages/executiontime.md
- docs/_pages/numerictypes.md
- docs/_pages/releases.md
The names of the GreaterOrEqualsTo methods (and similar) is a bit off, but more importantly they don't follow the established terminology.
> Change names of "OrEqualTo" assertion methods

- docs/_pages/releases.md
In https://github.com/fluentassertions/fluentassertions/pull/1221/commits/0a290be9a8edf5cff645840917e62aa698db343d when starting the v6.0 docs, I missed #1177.
> Added missing BeRankedEquallyTo docs for #1177

- Src/FluentAssertions/Common/TypeExtensions.cs
- Tests/FluentAssertions.Specs/IsExternalInit.cs
`GetInterfaces` was unused
Vanilla VS does not understand `ReSharper comments`, so changed it to be (hopefully) cross-IDE warning-free.
> Fix compiler warnings

- Src/FluentAssertions/AssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
Following up on #1649 this PR adds a test to verify that we don't forget to add new guarding `Should` overloads.
In the list I created in #1649 I only included overloads from `AssertionExtensions` but the `Should` for `EnumAssertions` is defined in `EnumAssertionsExtensions`.
This new test caught that oversight.
> Add test to find missing guarding Should overloads

- Src/FluentAssertions/Equivalency/Steps/EnumerableEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/GenericEnumerableEquivalencyStep.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.BeEquivalentTo.cs
- docs/_pages/releases.md
Detect specific exceptions with `.ToArray()` with `ImmutableArray<T>`.
Should fix #1655
> Handle exceptions when asserting an ImmutableArray

- docs/_pages/exceptions.md
> Fixed example for Awaiting method to assert exceptions

- Src/FluentAssertions/Extensions/FluentDateTimeExtensions.cs
- Tests/FluentAssertions.Specs/Extensions/FluentDateTimeSpecs.cs
- docs/_pages/releases.md
* `At(this DateTime date, TimeSpan time)` disregarded sub-seconds.
* Both `At` overloads created a new `DateTime` without retaining `DateTimeKind` from `date`.
> Keep DateTimeKind and Ticks precision in At

- Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
- Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs
- docs/_pages/releases.md
Calling an extension method from the expression provided to `Satisfy` causes an exception. Solves #1688 
Ignore null expressions in the constant visitor.
User-friendly formatting of an external lambda expression parameter is not solved as part of this pull request. I can see that it is also not yet cleanly solved in other APIs. 
E.g. `Should().Contain(a => allowed.Contains(a))` would fail with the following error message: 
```
"Expected actual {4} to have an item matching value(FluentAssertions.Specs.Formatting.PredicateLambdaExpressionValueFormatterSpecs+<>c__DisplayClass5_0).allowed.Contains(i).";
```
> Satisfy doesn't support extension methods #1688

- Build/Build.cs
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
- build.sh
With these changes one can now run `./build.sh` from linux.
As I wanted to be able to run tests without having mono installed, the .NET Frameworks tests are excluded when running on linux.
The upgrade from netcoreapp2.1 to net5.0 is solely to silence a build warning about net core 2.1 being EOL.
Tested on
* Ubuntu 20.04.3 (through WSL)
* Linux Mint 20.2
> Fix building on linux/WSL

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/Steps/DictionaryInterfaceInfo.cs
- Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs
- Tests/FluentAssertions.Specs/CultureAwareTesting/DictionaryExtensions.cs
In addition I noted that it doesn't seem necessary to clear the cache on calling `ComparingRecordsByValue`/`ComparingRecordsByMembers` as:
* `compareRecordsByValue` is initialized to `defaults.CompareRecordsByValue` and
* `GetEqualityStrategy` does not call recursively to determine strategy when `type.IsRecord()`.
> Add test of clearing cache when calling `ComparingByMembers`

- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
- docs/_pages/releases.md
> Adding `ThatAreAsync()` and `ThatAreNotAsync()` to `MethodInfoSelector`

- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
`MethodInfoExtensions.IsAsync` regards a method as async if and only if it is decorated with an `AsyncStateMachineAttribute`.
Returning `Task` is not enough.
Emphasize this by letting both methods in `TestClassForMethodSelectorWithAsyncAndNonAsyncMethod` return a `Task`.
> Return Task for async/non-async test method

- docs/_pages/collections.md
Support for non-generic collections was dropped as part of a breaking change in version 6.0. This causes some of the examples presented in the collections documentation to no longer be valid examples.
> Replace non-generic collection examples with generic collections in documentation

- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
- docs/_pages/releases.md
> Adds ThatAre(Not)Virtual to MethodInfoSelector

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.ContainSingle.cs
- docs/_pages/releases.md
> Prevent multiple enumeration in `ContainSingle()`

- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetRangeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeRangeAssertions.cs
- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Src/FluentAssertions/Specialized/TaskCompletionSourceAssertions.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
This fixes #1705 
To my surprise it is of no help decorating the overridden `Equals` with `[Obsolete]`.
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwGYACAZwQCcBXAYwVIGFCBvQ0z0k7gFlICyATwEBTBAAsA9gBMAFAEpSAXgB8pAKIBHGhBTk5MGihQKA3IQ5cA2gHlg5KSnGi5AIjdxSoqlSlUQUmoaUQUAXStOHikANx8qKBlRUmApJ00dPQMpYAArUQZSHNylNSCJPwB3UhhRaoA5KQQAZRoABzb/BFEZDQAPOlE2hCgpGEULAgBfIA==)
> Throw exception when calling object.Equals on Assertions class

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertionHelpers.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- docs/_pages/releases.md
If an async method has some initial sync computation, i.e. before first use of `await`, we didn't take the execution time of the sync work into account.
This fixes #1761
> Take sync work into account in CompleteWithinAsync

- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
- docs/_pages/releases.md
I'm unsure if this change will affect existing users. There is a change in https://github.com/fluentassertions/fluentassertions/blob/586035f3613e46ab84d5d4ec515103e9be065075/Src/FluentAssertions/Types/MethodInfoSelector.cs#L38 to include static methods. Is this rather a breaking change?
> Adds ThatAreStatic and ThatAreNotStatic to MethodInfoSelector

- ISSUE_TEMPLATE.md
Noticed that when going to https://fluentassertions.com/introduction/ I get a 404-page in response. If I remove the trailing slash it works.
I guess the best solution is to make it work with and without trailing slash but this is at least one way of making the Issue template not pointing to a 404-page.
> Trailing slash results in 404 page

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Common/Configuration.cs
- Src/FluentAssertions/Execution/GivenSelector.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.ContainItemsAssignableTo.cs
- docs/_pages/releases.md
Closes Issue https://github.com/fluentassertions/fluentassertions/issues/1618
Previously, `ContainItemsAssignableTo` behaved exactly the same as `AllBeAssignableTo`. `ContainItemsAssignableTo` has been changed to expect at least one item assignable to `T`.
> `ContainItemsAssignableTo` Now Expects At Least One Item Assignable to `T`

- Src/FluentAssertions/CallerIdentifier.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- docs/_pages/releases.md
> Variable name is not captured after await assertion

- Src/FluentAssertions/Primitives/HttpResponseMessageAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Types/MethodBaseAssertions.cs
- Src/FluentAssertions/Xml/XmlElementAssertions.cs
- Src/FluentAssertions/Xml/XmlNodeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
Inspired by #1772 I looked over the other `Identifier` properties to align them better.
> Adjust Identifier properties

- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
```
Failed FluentAssertions.Specs.Specialized.ExecutionTimeAssertionsSpecs.When_the_execution_time_of_an_async_action_is_less_than_a_limit_it_should_not_throw [2 s]
Error Message:
Did not expect any exception, but found Xunit.Sdk.XunitException with message "Execution of the action should be less than 2s, but it required exactly 2s, 555ms and 889.6µs."
```
https://github.com/fluentassertions/fluentassertions/runs/4832382920?check_suite_focus=true
> Relax When_the_execution_time_of_an_async_action_is_less_than_a_limit_it_should_not_throw

- .github/workflows/build.yml
- .nuke/build.schema.json
- Build/.editorconfig
- Build/Build.cs
- Build/_build.csproj
- GitVersion.yml
- build.ps1
- build.sh
* Bump Nuke/GitVersion to their latest
* PRs get a unique build number prepanded 
* Move Nuget pushing from Yaml into Nuke
> Bump Nuke/GitVersion, improve PR numbering, simplify Yaml script

- Src/FluentAssertions/Common/DictionaryHelpers.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- docs/_pages/releases.md
When I added `DictionaryHelpers` in #1298 I recall I did check that we had tests covering all the methods for `IEnumerable<KeyValuePair<TKey, TValue>>`.
Now I see that `DictionaryHelpers.TryGetValue` was only hit from `GenericDictionaryAssertions.ContainKey` which ignores the return value of `TryGetValue`.
This fixes #1783
> Fix TryGetValue for dictionary like enumerables

- Src/FluentAssertions/FluentAssertions.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
Enabling `ProduceReferenceAssembly` produces a reference assembly for `FluentAssertions.dll` in the `ref/` folder which only contains the method signatures, but no implementations. 
Similarly to the relationship between an interface and an implementation.
Project references look at the reference assembly to see what methods are available.
When making changes in Core that does _not_ change the method signatures, the reference assembly is unchanged, so compiling the Specs only need to recompile the Core dll and copy it to Specs output.
It can skip compiling the Specs dll as no method signatures have changed.
My experiments show that making a change in Core and recompiling Specs with `ProduceReferenceAssembly` enabled changes the compile time from 25s to 7s.
Additionally only having …
> Optimize build times

- Src/FluentAssertions/Execution/MessageBuilder.cs
- docs/_pages/releases.md
`DetermineCallerIdentity` is inherently unreliable (read: it's known that it's not perfect), especially in release mode.
Yet, we still use its result in `string.Format`, which may throw an unexpected `FormatException`.
This PR does not attempt to resolve the underlying issue, but takes the easy way out to fix tests unexpectedly failing.
I speculated about if we could determine if an assembly was usable for determining caller identity, but I didn't find any reliable way.
* `Assembly.GetEntryAssembly` returns `null` for net48
* net5.0 assemblies were annotated with `DebuggableAttribute` in both debug and release mode.
This partly resolves #1781.
> Guard against unformattable caller name

- Src/FluentAssertions/Common/MemberPath.cs
- Src/FluentAssertions/Common/StringExtensions.cs
- Src/FluentAssertions/Equivalency/EquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/INode.cs
- Src/FluentAssertions/Equivalency/Matching/MappedMemberMatchingRule.cs
- Src/FluentAssertions/Equivalency/Matching/MappedPathMatchingRule.cs
- Src/FluentAssertions/Equivalency/MemberFactory.cs
- Src/FluentAssertions/Equivalency/Node.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/Steps/StructuralEqualityEquivalencyStep.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
> Allow mapping properties and/or fields with different names

- Src/FluentAssertions/Primitives/StringAssertions.cs
- docs/_pages/releases.md
- docs/_pages/strings.md
Fixes https://github.com/fluentassertions/fluentassertions/issues/1768
> Improved docs on BeLowerCased and BeUpperCased for mixed strings

- Src/FluentAssertions/Execution/GivenSelector.cs
- Tests/FluentAssertions.Specs/Execution/GivenSelectorSpecs.cs
- docs/_pages/releases.md
Given the below example
```cs
bool result = Execute.Assertion
.WithExpectation("Expectation ")
.Given(() => "Don't care")
.ForCondition(_ => true)
.FailWith("Should not fail")
.Then
.ClearExpectation();
```
Even none of the assertions failed, `result` would be `false` instead of `true`
> Fixed a continuation issue in the fluent assertion API

- Src/FluentAssertions/Common/CSharpAccessModifierExtensions.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveAccessModifier.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs
- docs/_pages/releases.md
Removes IsClass check preventing enums and interfaces from being recognized as internal types when not nested.
Fixes #1741
**Note** Review without whitespace changes, e.g. https://github.com/fluentassertions/fluentassertions/pull/1793/files?diff=split&w=1
> Properly recognized non-class types as internal when using HaveAccessModifier assertion

- Src/FluentAssertions/CallerIdentification/AddNonEmptySymbolParsingStrategy.cs
- Src/FluentAssertions/CallerIdentification/AwaitParsingStrategy.cs
- Src/FluentAssertions/CallerIdentifier.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
- docs/_pages/releases.md
Certain constructs where `new` is used when constructing the argument of a method were not properly detected by the caller identification feature. 
Fixes #1695
> Caller identification does not handle all arguments using `new`

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/Steps/ValueTypeEquivalencyStep.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.ContainEquivalentOf.cs
- docs/_pages/releases.md
Fixes #1796 where tracing doesn't work for nested `AssertionScope`s. Also improves the tracing output a little bit.
**After**
```
With trace:
collection
{
property collection.Name
{
Equivalency was proven by ReferenceEqualityEquivalencyStep
}
property collection.Age
{
Treating property collection.Age as a value type because System.Int32 overrides Equals.
Equivalency was proven by ValueTypeEquivalencyStep
}
property collection.Birthdate
{
Treating property collection.Birthdate as a value type because System.DateTime overrides Equals.
Equivalency was proven by ValueTypeEquivalencyStep
}
property collection.Id
{
Treating property collection.Id as a value type because System.Int64 overrides Equals.
Equivalency was proven by ValueTypeEquivalencyStep
}
Equivalency was proven by …
```
> Fix and improve tracing for nested AssertionScopes

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Src/FluentAssertions/Common/MemberPath.cs
- Src/FluentAssertions/Equivalency/Matching/MappedPathMatchingRule.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.BeInAscendingOrder.cs
- docs/_pages/releases.md
216646a32f392c8bd437c4daa0ebf8fa839b3b34 made the empty path prohibited as part of creating a mapping between two properties.
But the empty member path corresponds to the [identity function](https://en.wikipedia.org/wiki/Identity_function) which is a perfectly valid expression to e.g. order collections by.
```cs
collection.Should().BeInAscendingOrder(x => x)
```
> Fix ordering collections by the identity function

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
This appeared to be copy/pasted from `ComparingRecordsByValue`
> Fix typo in comment for ComparingRecordsByMembers

- .github/workflows/build.yml
- Build/Build.cs
- Build/_build.csproj
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
* Adds code coverage to the build
* On local builds, report generator will generate an HTML report
* Link to the report file is added to the output, if your terminal supports it, it's clickable
* On CI builds, results will be added coveralls
* https://coveralls.io/github/fluentassertions/fluentassertions
* After the first build with coverage is merged with master, subsequent PR's will have code coverage reported in the PR by coveralls
* Very small lay-out fixes (spaces, new-lines, etc.)
Didn't add it to the release notes as it's not modifying the library itself.
> Add code coverage reporting

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Src/FluentAssertions/StringSyntaxAttribute.cs
- docs/_pages/releases.md
With Visual Studio 17.2 you can annotate arguments and properties with `StringSyntaxAttribute`, e.g. to analyze and colorize regular expressions.
So I've added this to `[Not]MatchRegex(string)`.
As VS does not look at the _actual_ type of the attribute, but only the name and namespace, we can deliver this to all TFMs by adding an internal attribute.
I assume this is the same approach Rider uses with the `[RegexPattern]` from `JetBrains.Annotations` that we already use.
Using VS 17.2.0 Preview 1.0 here's how this PR changes the looks of `When_a_string_matches_a_regular_expression_string_it_should_not_throw`.
Before:
After:
For more info about `StringSyntaxAttribute`:
* https://github.com/dotnet/runtime/issues/62505
* Demo: https://youtu.be/rwfNDyBBgks?t=1119
> Annotated [Not]MatchRegex with [StringSyntax("Regex")]

- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/FluentAssertions.Specs/AndWhichConstraintSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- Tests/FluentAssertions.Specs/ConfigurationSpecs.cs
- Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorSpecs.cs
Found two `Action`s in `StringAssertionSpecs.cs` that were never invoked.
While checking if we had done the same mistake more places I found some formatting to clean up.
> Fix uninvoked actions

- .github/workflows/release.yml
As discussed [here](https://github.com/fluentassertions/fluentassertions/discussions/1804) we can improve the auto-generated release notes by adding a [`release.yml`](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options) which can group changes by label.
I looked at the existing labels we have used to make the categories.
> Add release notes template

- Build/_build.csproj
- Src/FluentAssertions/FluentAssertions.csproj
- Tests/Approval.Tests/ApiApproval.cs
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/Benchmarks.csproj
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
Most notable changes:
* [Clipboard is moved to Verify.ClipboardAccept](https://github.com/fluentassertions/fluentassertions/commit/335cf22e685cafa56e97626a20ba6d499154dfa4)
* PublicApiGenerator makes more accurate API dumps regarding enums and generics
> Update nuget packages

- Src/FluentAssertions/Data/DataRowAssertions.cs
- Src/FluentAssertions/Data/DataSetAssertions.cs
- Src/FluentAssertions/Data/DataTableAssertions.cs
- Src/FluentAssertions/Equivalency/Steps/DataRelationEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DataRowCollectionEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DataRowEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DataSetEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DataTableEquivalencyStep.cs
- Tests/FluentAssertions.Equivalency.Specs/DataRowSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataSetSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
This PR backfills missing automated tests for System.Data.
> Fill gaps in System.Data unit testing

- .github/workflows/build.yml
- Build/Build.cs
- Build/_build.csproj
- README.md
- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Src/FluentAssertions/ObjectAssertionsExtensions.cs
- Src/FluentAssertions/StringSyntaxAttribute.cs
- Tests/Approval.Tests/ApiApproval.cs
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Benchmarks/BeEquivalentToWithDeeplyNestedStructures.cs
- Tests/Benchmarks/Benchmarks.csproj
- Tests/Benchmarks/CollectionEqual.cs
- Tests/Benchmarks/Issue1657.cs
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/Common/TimeSpanExtensions.cs
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
- docs/_pages/about.md
- docs/index.html
- global.json
This PR adds a net6.0 which is a prerequisite to implement #1754.
> Add net6.0 target

- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Src/FluentAssertions/Primitives/NullableEnumAssertions.cs
- Tests/FluentAssertions.Specs/Primitives/EnumAssertionSpecs.cs
- docs/_pages/releases.md
> Determine caller name for `EnumAssertions.Be`

- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
Adds a test for string collection. Arrays were not tested.
Related to #1823
> Adds test for string collection equivalency

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs
- docs/_pages/releases.md
The option `ExcludingMissingMembers` tries to undo what `ThrowingOnMissingMembers` does and vice-versa by clearing out all matching rules. However, by doing that, it would also remove any `MappedPathMatchingRule` instances that were added by using the `WithMapping` method. This has been fixed.
Fixes #1828
> Ensure ExcludingMissingMembers doesn't undo usage of WithMapping

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Numeric/DoubleAssertions.cs
- Src/FluentAssertions/Numeric/FloatAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
- docs/_pages/releases.md
Assertions where floats and doubles were compared to NaN did not always work as expected, especially when "larger than",  "smaller than", ranges and approximation were involved. Also, using NaN as an argument is also no longer supported (and not desired).
Fixes #1690
**Note** Review without whitespace
> Better support for NaN in numeric assertions on floats and doubles

- Src/FluentAssertions/Primitives/NullableDateOnlyAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
Unreleased, so not yet a breaking change to rename constructor parameters.
> Remove constructor parameter for NullableDateOnlyAssertions

- Build/Build.cs
- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/DoesNotReturnAttribute.cs
- Src/FluentAssertions/Execution/FallbackTestFramework.cs
- Src/FluentAssertions/Execution/ITestFramework.cs
- Src/FluentAssertions/Execution/LateBoundTestFramework.cs
- Src/FluentAssertions/Execution/NSpecFramework.cs
- Src/FluentAssertions/Execution/TestFrameworkProvider.cs
- Src/FluentAssertions/Execution/XUnit2TestFramework.cs
- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
This PR adds tests covering the fake `Should` overloads.
I first aimed for test that would find all the relevant types itself, but even before reaching that goal the test became quite unreadable.
So went with a `Theory`, which should be manageable for contributors, as `Should_methods_have_a_matching_overload_to_guard_against_chaining_and_constraints` will complain about missing `Should` overloads.
Thanks to @eNeRGy164 for the inspiration.
> Improve code coverage of fake should overloads

- Src/FluentAssertions/Primitives/StringEqualityValidator.cs
> Removes unnecessary code

- Src/FluentAssertions/Common/MemberPath.cs
- Src/FluentAssertions/Equivalency/Matching/MappedPathMatchingRule.cs
- Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs
- docs/_pages/releases.md
`WithMapping` did not take into account that when you compare two collections using `Should().BeEquivalentTo`, a slightly different path in the code-base is taken. 
This fixes #1840
> WithMapping now works in equivalency assertions on collections

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Numeric/NullableDoubleAssertions.cs
- Src/FluentAssertions/Numeric/NullableFloatAssertions.cs
- Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
- docs/_pages/releases.md
I noticed that #1859 had to add `NullableFloatAssertions`/`NullableDoubleAssertions`, so I suspected that #1822 might not cover all cases for `float?` and `double?`.
This PR ensures that `NumericAssertions.IsNaN` is overridden for `float?` and `double?`.
The tests are copied from #1822
> Better handling of NaN in nullable numeric assertions

- Src/FluentAssertions/Primitives/NullableBooleanAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/NullableBooleanAssertionSpecs.cs
- docs/_pages/releases.md
> Extend NullableBooleanAssertions by NotBe()

- Tests/FluentAssertions.Specs/OccurrenceConstraintSpecs.cs
Add test edge case coverage for `OccurrenceConstraint` types
> Add test coverage for `OccurrenceConstraint`

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.MatchRegex.cs
- docs/_pages/releases.md
- docs/_pages/strings.md
> Added a new overload to `MatchRegex()` to assert on the number of regex matches

- docs/_data/mstest-migration/collectionAssert.yml
- docs/_data/tips/collections.yml
> Update documentation: Add missing tip for `ContainItemsAssignableTo<T>()`

- Src/FluentAssertions/Numeric/ByteAssertions.cs
- Src/FluentAssertions/Numeric/DecimalAssertions.cs
- Src/FluentAssertions/Numeric/DoubleAssertions.cs
- Src/FluentAssertions/Numeric/Int16Assertions.cs
- Src/FluentAssertions/Numeric/Int32Assertions.cs
- Src/FluentAssertions/Numeric/Int64Assertions.cs
- Src/FluentAssertions/Numeric/NullableByteAssertions.cs
- Src/FluentAssertions/Numeric/NullableDecimalAssertions.cs
- Src/FluentAssertions/Numeric/NullableDoubleAssertions.cs
- Src/FluentAssertions/Numeric/NullableInt16Assertions.cs
- Src/FluentAssertions/Numeric/NullableInt32Assertions.cs
- Src/FluentAssertions/Numeric/NullableInt64Assertions.cs
- Src/FluentAssertions/Numeric/NullableSByteAssertions.cs
- Src/FluentAssertions/Numeric/NullableSingleAssertions.cs
- Src/FluentAssertions/Numeric/NullableUInt16Assertions.cs
- Src/FluentAssertions/Numeric/NullableUInt32Assertions.cs
- Src/FluentAssertions/Numeric/NullableUInt64Assertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Numeric/SByteAssertions.cs
- Src/FluentAssertions/Numeric/SingleAssertions.cs
- Src/FluentAssertions/Numeric/UInt16Assertions.cs
- Src/FluentAssertions/Numeric/UInt32Assertions.cs
- Src/FluentAssertions/Numeric/UInt64Assertions.cs
- Tests/FluentAssertions.Specs/Numeric/NumericDifferenceAssertionsSpecs.cs
Currently we avoid reporting incorrect differences for 32 and 64 bit integrals by doing a `checked` subtraction, catch any `OverflowException` and omit the difference in the failure message.
Instead we can do a widening conversion of `subject` and `expected` and _then_ perform a regular subtraction.
This removes the need for `checked` and try/catch and returns the difference.
> Improve difference calculation of overflowing integrals

- docs/_pages/eventmonitoring.md
> Update documentation for event monitoring at .netstandard2.0

- Src/FluentAssertions/Equivalency/Matching/MappedPathMatchingRule.cs
- Src/FluentAssertions/Equivalency/MultiDimensionalArrayEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/Steps/DataSetEquivalencyStep.cs
- Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/NestedPropertiesSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.AllSatisfy.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs
- Tests/UWP.Specs/Properties/AssemblyInfo.cs
This PR solves some Visual Studio errors
> Code style fixes

- Tests/FluentAssertions.Equivalency.Specs/DataColumnSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataRelationSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataRowSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataSetSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
> Add missing tests (according to coveralls) for Data* objects

- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/EnumAssertionSpecs.cs
- docs/_pages/enums.md
- docs/_pages/releases.md
> Add `BeDefined` and `NotBeDefined` to `EnumAssertions`

- Src/FluentAssertions/Execution/AssertionScope.cs
> Fix small typo in `AssertionScope`

- Src/FluentAssertions/Primitives/StringWildcardMatchingValidator.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.Match.cs
> Add missing tests for matching `null` with a wildcard

- Src/FluentAssertions/Equivalency/Execution/CollectionMemberAssertionOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/Field.cs
- Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/IMember.cs
- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/Property.cs
- Src/FluentAssertions/Equivalency/Selection/ExcludeNonBrowsableMembersRule.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/Steps/StructuralEqualityEquivalencyStep.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/CheckIfMemberIsBrowsable.cs
- Tests/Benchmarks/Program.cs
- Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
In #1807, changes were made to allow non-browsable members to be excluded from equivalency tests. But, these changes ended up being reverted because they affected processing of both subject & expectation, but include/exclude functions are supposed to apply only to the expectation. In addition, the original changes only worked properly when the subject & expectation were of the same data type. In my actual usage, the subject and expectation are different data types and _only one of them_ marks the member as non-browsable. This wasn't factored in in the original implementation, for which the unit tests exclusively test the case where the subject and expectation are the same data type. The changes in #1807 got reverted since they were in an incomplete/uncertain state and were blocking a …
> Add the ability to exclude non-browsable members from equivalency tests

- Src/FluentAssertions/AssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/ExtensibilitySpecs.cs
- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
Found that we didn't have fake `Should` overloads for `DateTime[Offset]RangeAssertions` since they don't have real `Should` overloads, but are always constructed from `DateTime[Offset]Assertions`.
I've also added code-coverage tests of guarding `Equals` methods right below `Assertions_classes_override_equals` which tests that `bool Equals(object obj)` is overridden.
> More testing of guarding methods

- docs/_pages/releases.md
The release note from the latest commit is located under v6.6.0 but actually it is not yet released.
> Fix release notes

- Tests/FluentAssertions.Equivalency.Specs/DataRowSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataSetSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
> Add missing `null` check tests in Data*Specs

- Tests/FluentAssertions.Specs/Primitives/GuidAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
> Structure assertions with nested classes instead of regions (Part 2)

- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.Be.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeEmpty.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeEquivalentTo.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeLowerCased.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeNullOrEmpty.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeNullOrWhiteSpace.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeOneOf.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeUpperCased.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.Contain.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.ContainAll.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.ContainAny.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.ContainEquivalentOf.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.EndWith.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.EndWithEquivalentOf.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.HaveLength.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.Match.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.MatchEquivalentOf.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.MatchRegex.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.StartWith.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.StartWithEquivalentOf.cs
> Structure assertions with nested classes instead of regions (Part 3)

- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- Tests/FluentAssertions.Specs/UIFactsDefinition.cs
Everyone's tired of `[UIFact]` tests (semi-)randomly failing and I don't have a clue what's causing the issue.
I initially wanted to use https://github.com/JoshKeegan/xRetry to simply retry them, but it doesn't seem combinable with `UIFact`.
So instead I went with running the `[UIFact]` tests sequentially and crossing fingers it'll improve things.
Disable whitespace while reviewing.
> Try to stabilize UIFact tests by running them sequentially

- Tests/FluentAssertions.Specs/Types/MethodBaseAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoSelectorAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/PropertyInfoAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/PropertyInfoSelectorAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.Be.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeAbstract.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeAssignableTo.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeDecoratedWith.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeDecoratedWithOrInherit.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeDerivedFrom.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeSealed.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.BeStatic.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveAccessModifier.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveConstructor.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveDefaultConstructor.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveExplicitConversionOperator.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveExplicitMethod.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveExplicitProperty.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveImplicitConversionOperator.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveIndexer.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveMethod.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveProperty.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.Implement.cs
- Tests/FluentAssertions.Specs/Types/TypeSelectorAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XAttributeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlElementAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlNodeAssertionSpecs.cs
> Structure assertions with nested classes instead of regions (Part 5)

- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Tests/FluentAssertions.Equivalency.Specs/.editorconfig
- Tests/FluentAssertions.Equivalency.Specs/DataSetSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
- Tests/FluentAssertions.Specs/.editorconfig
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.Contain.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.Equal.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.HaveCount.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.Satisfy.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/EnumAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.ContainEquivalentOf.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodBaseAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveIndexer.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.Implement.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlNodeAssertionSpecs.cs
> Fix codestyle issues

- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.MatchRegex.cs
- docs/_pages/releases.md
In my daily work, I was really pissed about the fact, that I have forgotten to include the actual subject in the failure message.
This PR fixes my own fault. :)
> Fix the failure message for occurrence regex

- Src/FluentAssertions/EventRaisingExtensions.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- docs/_pages/releases.md
> Do not add all arguments of type `T` to the matching events, if one is found

- Src/FluentAssertions/EventRaisingExtensions.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
Adjust the XML summaries of `WithArgs` to more closely clarify the implementation.
* For the overload taking a single predicate only a single argument of type `T` has to match the predicate.
* So for three arguments of type `T` it's enough for e.g. the second argument to match.
* I found "some argument" preferable to "an argument" to signal that the event can have other arguments besides the matching one(s).
* Be explicit about that it's the arguments and not the event that have to match the predicate.
I also discovered that the summaries for the entire type was in past tense where all others (as far as I could see) are written in present tense.
> More specifically clarify the intentions of `WithArgs`

- Directory.Build.props
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Src/FluentAssertions/StringBuilderExtensions.cs
- Tests/AssemblyA/AssemblyA.csproj
- Tests/AssemblyB/AssemblyB.csproj
- Tests/Benchmarks/Benchmarks.csproj
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/UWP.Specs/UWP.Specs.csproj
Upgrade all our projects to C# 10 and centralize it in `Directory.Build.props`.
This triggered an analyzer since `StringBuilder.AppendLine()` now may resolve to `StringBuilder.AppendLine(ref AppendInterpolatedStringHandler)`
For more information about string interpolation handlers.
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler
https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/
> Upgrade to C# 10

- Src/FluentAssertions/CallerIdentification/AddNonEmptySymbolParsingStrategy.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Formatting/MultidimensionalArrayFormatter.cs
- Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/DateOnlyAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Primitives/NullableBooleanAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Primitives/TimeOnlyAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/SimpleTimeSpanAssertionSpecs.cs
Many primitive types have overloaded comparison operators so developers don't have to use the `IComparable<T>.CompareTo(T)` method.
With the increasingly improved pattern matching in C# I often feel the combined use of `HasValue` and `Value` is similar to using `ContainsKey` + `[key]` instead of `TryGetValue`.
> More use of pattern matching and lifted operators

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Equivalency/ConversionSelector.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/Node.cs
- Src/FluentAssertions/Equivalency/Steps/StructuralEqualityEquivalencyStep.cs
- Tests/FluentAssertions.Equivalency.Specs/CyclicReferencesSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
In #1932 I noticed that we generate the equivalency summary even when a test does not fail.
That didn't look right to me.
<details>
```cs
[MemoryDiagnoser]
[SimpleJob(RuntimeMoniker.Net472)]
[SimpleJob(RuntimeMoniker.Net60)]
public class BeEquivalentToBenchmarks
{
public class MyClass
{
public int MyProperty { get; set; }
}
private readonly MyClass a = new();
private readonly MyClass b = new();
[Benchmark]
public AndConstraint<ObjectAssertions> BeEquivalentTo() => a.Should().BeEquivalentTo(b);
}
```
</details>
develop
|         Method |              Runtime |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Allocated |
|--------------- |--------------------- |----------:|----------:|----------:|-------:|-------:|----------:|
| BeEquivalentTo |             .NET 6.0 |  8.888 us | …
> Optimize `BeEquivalentTo`

- Src/FluentAssertions/CallerIdentifier.cs
.NET 7 Preview 5 includes https://github.com/dotnet/runtime/pull/67917 which might change the looks of the stack trace when using reflection to create dynamic methods like we do for `GenericEnumerableEquivalencyStep.HandleMethod`.
The stack trace for some tests changed from
```
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
```
to
```
at InvokeStub_GenericEnumerableEquivalencyStep.HandleImpl(Object, Object, IntPtr*)
at …
```
> Filter dynamic methods from stack trace

- Src/FluentAssertions/Common/MemberPath.cs
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- docs/_pages/releases.md
> Make For/Excluding work with nested paths

- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
When using line breaks, print commas behind the listed items, instead of on a new line.
Before:
```
Expected someCollection {
item1
,
item2
,
```
After:
```
Expected someCollection {
item1,
item2,
```
> Print commas at the end of the line

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.ContainInOrder.cs
There's no need to repeatedly allocating sub-arrays.
In the worst case, when subject and expected are identical, we will allocate N sub-arrays of a total length of O(N^2).
Instead we simply keep an index of how far we have scanned the subject.
The added tests are not meant as authoritative but only to ensure behavior has not changed.
> Avoid allocating sub-arrays in ContainInOrder

- docs/_pages/tips.md
Since we worked out the cumbersome workaround to setup `AssertionOptions` exactly once for xUnit in a thread-safe manner, .NET 5 has introduced the `ModuleInitializerAttribute` to make this much easier 🎉
> Document how to use `ModuleInitializer`

- Src/FluentAssertions/Common/ICollectionWrapper.cs
- Src/FluentAssertions/Common/ReadOnlyNonGenericCollectionWrapper.cs
- Src/FluentAssertions/DataColumnCollectionAssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
Initial implementation: Per @dennisdoomen in comments on #1893, this PR marks the `ReadOnlyNonGenericCollectionWrapper<TCollection, TItem>` type public so that it can be referenced by an extension package. An XMLDoc comment is added to advise perusers that the type is an internal implementation detail, despite its access modifier.
Take two: Instead of altering the `ReadOnlyNonGenericCollectionWrapper<TCollection, TItem>` type, an interface `IHasUnderlyingCollection<TCollection>` is introduced that permits consumers to interact with types that have an `UnderlyingCollection` of a specific type without needing access to the actual implementation.
> Make it possible for third-party libraries to access the underlying collection of instances of ReadOnlyNonGenericCollectionWrapper`2

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/TaskCompletionSourceAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- docs/_pages/executiontime.md
- docs/_pages/releases.md
In addition to `CompleteWithAsync` in assertions for `Task` and `Task<T>`, and similar to assertions for `TaskCompletionSource`, I added `NotCompleteWithinAsync`.
Checking the existing tests I found some inconsistency which I've fixed (hopefully) in several separate commits. Maybe you want to review these commits one by one for better overview.
> Added NotCompleteWithinAsync for Task assertions

- Src/FluentAssertions/Equivalency/Execution/ObjectInfo.cs
- Src/FluentAssertions/Equivalency/Field.cs
- Src/FluentAssertions/Equivalency/INode.cs
- Src/FluentAssertions/Equivalency/IObjectInfo.cs
- Src/FluentAssertions/Equivalency/Node.cs
- Src/FluentAssertions/Equivalency/Ordering/CollectionMemberObjectInfo.cs
- Src/FluentAssertions/Equivalency/Property.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/ExtensibilitySpecs.cs
- docs/_pages/releases.md
Adds `IObjectInfo.ParentType` to help determining the declaring type in a call to `Using`/`When` constructs.
Also marks `IObjectInfo.Type` as obsolete since its purpose is so confusing.
Fixes #1949
> Extend IObjectInfo with info about DeclaringType

- docs/_pages/assemblies.md
Fixes a typo (a redundant 'the' definite article) on the [Assembly References](https://fluentassertions.com/assemblies/) documentation page.
> Fix a typo on the Assembly References documentation page

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
In #1967 I added two protected methods. In review I made only one private.
After suggestion of @jnyrup I made both private.
For better review I split it into two commits.
Updating release notes should not be necessary.
> Make `CompletesWithinTimeoutAsync` private before release

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/Specialized/TaskCompletionSourceAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/AssertionExtensions.cs
- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
- docs/_pages/releases.md
The non-generic `TaskCompletionSource` was introduced in .NET 5.
Special thanks to my colleague René H. inspiring this feature.
I took the liberty to adjust the wording in the changelog. I hope this is in your sense.
> Added assertions for non-generic TaskCompletionSource

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/NonGenericAsyncFunctionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
While implementing #1967 I found Rider hint on the second constructor of `AsyncFunctionAssertions` that it can be made protected.
Thinking deeper I found that the this class is constructed like a base class but not implemented like that.
I recommend to make this class a real base class, maybe also with renaming, but at least making used ctor protected and removing unused ctor. Further some methods can be moved to one base class because it is over written in the other one (with `new`).
All these are breaking changes, I guess. This is why I recommend to make the ctors obsolete today.
What do you think?
> Prepare constructors of `AsyncFunctionAssertions` to make them protected in V7

- Src/FluentAssertions/Common/ReadOnlyNonGenericCollectionWrapper.cs
- Src/FluentAssertions/DataColumnCollectionAssertionExtensions.cs
- Src/FluentAssertions/DataRowCollectionAssertionExtensions.cs
- Src/FluentAssertions/DataTableCollectionAssertionExtensions.cs
- Src/FluentAssertions/Equivalency/Field.cs
- Src/FluentAssertions/Events/EventMonitor.cs
Just some small changes that I wanted to change for some time now.
> Code cleanups

- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
Adds an additional test to compensate for a slight degradation in coverage caused by #1950.
> Improve coverage for CollectionMemberObjectInfo

- Tests/Approval.Tests/ApiApproval.cs
In the ApproveApi test, read the target frameworks directly from the FluentAssertions.csproj file instead of copying them all as InlineData.
This should future proof when new target frameworks are added/removed from the main project.
> Deduplicate target frameworks

- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- docs/_pages/releases.md
Fixes https://github.com/fluentassertions/fluentassertions/issues/1975
> Removed netcoreapp2.0 framework check in formatting precision tests

- Src/FluentAssertions/Primitives/StringWildcardMatchingValidator.cs
- Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
- docs/_pages/releases.md
I recently learned that regex in C# per default uses the current culture when doing case-insensitive matches.
This means that we current fails the Turkey Test, i.e. considering `i` and `I` equivalent when disregarding casing.
For 6.0.0 we changed all other known string comparisons to use Invariant culture, see #1283.
> Use InvariantCulture when doing case-insensitive matches

- Src/FluentAssertions/Equivalency/Execution/CollectionMemberAssertionOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
- Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs
- docs/_pages/releases.md
Fixes #1977 
Because of the way `GetEqualityStrategy` was implemented, the behavior for records never took into account any global settings. 
Unfortunately, this requires a breaking change on the `IEquivalencyAssertionOptions` interface, but given its core usage and the very unlikely possibility to use that from consumer code, I think that's acceptable. 
**Note** First commit is just a refactoring.
> Global record equivalency settings were not taken into account

- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
Changes private function:
ShouldCompareMembersThisDeep to ShouldCompareNodesThisDeep.
@dennisdoomen
> EquivalencyValidator: ShouldCompareMembersThisDeep -> ShouldCompareNodesThisDeep.

- Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs
> Remove usage of method name in test method name

- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- docs/_pages/releases.md
Expressions can contain brackets, which cause the failure message formatting to fail. I escaped all of the cases for execution time, not sure if there are other types affected
> Escape brackets in execution time failures

- Src/FluentAssertions/Events/EventAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- docs/_pages/releases.md
Changed the private field to a public property, thereby exposing the IMonitor object to extensions methods.
Closes #2008
- Added Unit test.
- Ran and updated accept api changes.
- Added release notes.
> Exposes the IMonitor object to extensions methods.

- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
- docs/_pages/releases.md
> Calculate the difference between the subject and the expected nearby time

- docs/_pages/releases.md
Accidentally added the issue id instead of the PR id.
Sorry :)
> Fix the PR link in releases.md

- docs/_pages/releases.md
- docs/index.html
> Prepare 6.8.0

- .github/workflows/build.yml
An extra layer of testing to ensure we also work on other operating systems. 
Until now I've once in a while run our tests on my local Linux machine or in WSL.
> Enable CI unit tests on linux and mac

- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
Locally I could not reproduce anymore #2004. I guess it was fixed together with #1967.
> New unit test to verify CompleteWithinAsync behaves correctly in an assertion scope

- Src/FluentAssertions/Data/DataEquivalencyAssertionOptions.cs
- Tests/FluentAssertions.Equivalency.Specs/DataColumnSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/TypedDataSetSpecs.cs
I've added new tests to improve code coverage according to #1823.
While analyzing the code I found that there was thrown an `Exception`, an exception type which shall not be used directly. I've changed it to `ArgumentException` which should compatible.
Further tests on `DataEquivalencyAssertionOptions` I could not create because I do not understand their intention.
Please note (and check?) the method `ExcludingColumns(string tableName, IEnumerable<string> columnNames)` which creates locally a variable named `excludeColumnNames` which hides similar member. I'm not sure whether this is correct or potential bug. Maybe @logiclrd can check this because you created this code in #1419.
> Improve coverage on data assertions

- global.json
PolySharp requires a newer SDK to use source generators
> Bump minimum SDK to 6.0.400

- Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs
Currently the test in `ComparableSpecs` for `[Not]Be` wrongly exercises `ObjectAssertions.[Not]Be` instead of `ComparableTypeAssertions`.
This is because `EquatableOfInt` does not implement `IComparable<T>`, so `Should()` resolves to `ComparableTypeAssertions` instead of `ObjectAssertions`.
> Let `EquatableOfInt` implement `IComparable<T>`

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllBeAssignableTo.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllBeOfType.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.Contain.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.ContainInOrder.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.HaveCount.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.NotContainNulls.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.OnlyHaveUniqueItems.cs
I've added new tests for better code coverage on collection assertions according to #1823.
While writing these tests I found some inconsistencies in building assertion messages which I've fixed silently.
> New tests for better code coverage on collection assertions

- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- docs/_pages/basicassertions.md
- docs/_pages/numerictypes.md
- docs/_pages/releases.md
> Added `BeOneOf` for `IComparable`s and object comparisons.

- Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
`SameInstanceIsNotEqualClass` did not implement `IComparable<T>` so `Should` resolved to `ObjectAssertions` instead of `ComparableTypeAssertions`.
The PR is structured into three commits for easier reviewing.
This is a follow-up to #2036 and #2028
> Comparable type assertions referential equality

- Src/FluentAssertions/Common/PropertyInfoExtensions.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Types/PropertyInfoSelectorSpecs.cs
- docs/_pages/releases.md
- docs/_pages/typesandmethods.md
> Add `ThatAre[Not]Abstract`, `ThatAre[Not]Static` and `ThatAre[Not]Virtual` to `PropertyInfoSelector`

- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
Hi Folks,
Thanks again for this awesome library.  I often forget which assertion I should use on collections when I want to assert on the order of the elements or ignore it.  This change adds the suggestion for the "other" one to the XML docs for the string collection assertions.  The idea here is somewhat similar to my previous [usability PR](https://github.com/fluentassertions/fluentassertions/pull/2006).
If this change is acceptable to you all, I can add a similar change to the other collection assertions classes as well.  Wordsmithing suggestions definitely welcome.
If this is not an interesting PR to you, no worries and we can close it.
Many thanks!
> Document alternatives for collection order

- Src/FluentAssertions/Types/TypeSelector.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
- docs/_pages/releases.md
- docs/_pages/typesandmethods.md
> Add `ThatAre[Not]Sealed` to `TypeSelector.cs`

- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/ExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Extensions/ObjectExtensionsSpecs.cs
- Tests/FluentAssertions.Specs/Formatting/EnumerableExtensionsSpecs.cs
- Tests/FluentAssertions.Specs/Formatting/MultidimensionalArrayFormatterSpecs.cs
- Tests/FluentAssertions.Specs/OccurrenceConstraintSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
- Tests/FluentAssertions.Specs/Streams/StreamAssertionSpecs.cs
After I learned about `TheoryData` in #1980 I searched for more places we could apply this to increase type-safety and remove some cruft.
> Use TheoryData

- docs/_pages/introduction.md
> Document that `PathMap` is currently not supported

- Src/FluentAssertions/Common/FullFrameworkReflector.cs
- Src/FluentAssertions/Equivalency/Steps/ValueTypeEquivalencyStep.cs
- Src/FluentAssertions/Extensions/FluentDateTimeExtensions.cs
- Src/FluentAssertions/Formatting/DateTimeOffsetValueFormatter.cs
- Tests/FluentAssertions.Specs/Common/TimeSpanExtensions.cs
1) Found some more places where patterns can be used.
2) The guards were introduced in #669, but this is only an optimization when passing in 0.
I estimate that most usages do not that, as why would you call `AddMicroSeconds(0)`.
> Pattern combinators

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/SubsequentOrderingAssertions.cs
- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
- docs/_pages/releases.md
`Comparer<string>.Default` returns a culture aware string comparer. This may cause tests to fail when executed under a different culture.
> Order strings with ordinal comparison

- Src/FluentAssertions/Common/TypeExtensions.cs
net471/netcoreapp20/netstandard21 introduced the `ITuple` interface which all `Tuple` and `ValueTuple` types implement.
So for a modern TFM like net6 `IsTuple()` can be 3-5 times faster.
|  Method |              Runtime |      DataType |       Mean |     Error |    StdDev | Ratio | RatioSD |
|-------- |--------------------- |-------------- |-----------:|----------:|----------:|------:|--------:|
| develop |             .NET 6.0 |        `List<>` |  47.839 ns | 0.8258 ns | 0.7725 ns |  1.00 |    0.00 |
|      PR |             .NET 6.0 |        `List<>` |   9.802 ns | 0.1631 ns | 0.1525 ns |  0.20 |    0.00 |
|         |                      |               |            |           |           |       |         |
| develop | .NET Framework 4.7.2 |        `List<>` |  80.891 ns | 0.8988 ns | …
> Improve performance of `IsTuple()`

- Src/FluentAssertions/Common/TypeExtensions.cs
`<Clone>$` is an "unspeakable" method name generated by Roslyn, which should be sufficient to determine if a type is a record.
> Optimize `IsRecord()`

- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/BooleanAssertionSpecs.cs
- docs/_pages/booleans.md
- docs/_pages/releases.md
> Add `Imply()` to `BooleanAssertions`

- Src/FluentAssertions/Types/TypeSelector.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
- docs/_pages/releases.md
> Add `ThatAre[Not]ValueTypes` method to `TypeSelector.cs`

- Build/Build.cs
- build.ps1
- build.sh
This ref. 
https://github.com/dotnet/sdk/issues/29543
https://github.com/dotnet/sdk/issues/28975
https://github.com/dotnet/sdk/issues/28975#issuecomment-1359645133
This is a workaround for users who running NUKE on the local dev device and having a different dotnet cli language than `en-US` and using the latest .NET7 sdk (at this time 7.0.101). Therefore the test steps are failing.
I don't know when the [pull request](https://github.com/dotnet/sdk/pull/29559) (which fixes the problem) is being merged.. Maybe this change here is not necessary, but I thought I give this hint according this bug.
> Set process dotnet cli language to en-US

- .github/workflows/build.yml
- README.md
- global.json
In #2076 I began using `nameof()` within an attribute which is technically a [C#11 feature](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/extended-nameof-scope), but seems to work as long as you use C#11 compatible SDK.
> Bump required .NET SDK to v7

- Build/Build.cs
My fault.. ~~over-optimized code..~~ should be fixed now 
`PullRequestBase` is empty and not `null`/`default`
> Fix build breaking on non PR branches

- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Tests/FluentAssertions.Specs/Types/PropertyInfoSelectorSpecs.cs
- docs/_pages/releases.md
> Extend `ThatArePublicOrInternal` to also look at the setter of properties

- Build/Build.cs
As proposed in https://github.com/fluentassertions/fluentassertions/pull/2084#issuecomment-1370862201, also adding it to the specific test targets inside NUKE for IDE guys :D
> Add process env variable `DOTNET_CLI_UI_LANGUAGE` also inside targets

- docs/_pages/releases.md
> Fix broken link in releases.md

- Src/FluentAssertions/NumericAssertionsExtensions.cs
- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/NotThrowSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
#2101 inspired me to look for some more places, where we would continue assertion despite `Subject` being null, which would throw a `NullReferenceException` or `InvalidOperationException`.
> Avoid exceptions when wrapping in `AssertionScope`

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Equivalency/Matching/MappedMemberMatchingRule.cs
- Src/FluentAssertions/Equivalency/Matching/MappedPathMatchingRule.cs
- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/Matching/TryMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/MemberFactory.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- docs/_pages/releases.md
Fixes #1982 
If a derived class is used as the expectation and hides a base-class field of the same type using the `new` keyword, FA would get confused about which field to use. Now, it'll start at the compile- or run-time type (depending on the options and reference passed) and find the property or field from there. 
This does have a potential side-effect. Since we don't know the compile-time type of the subject-under-test, we now do the same thing for the subject's properties and fields. Before this PR, we tried to find the best match. 
**Note** Review by commit
> Improves how BeEquivalentTo handles fields hiding base-class fields

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/TaskCompletionSourceAssertions.cs
Due to https://github.com/fluentassertions/fluentassertions/pull/2103#discussion_r1070650590
Review with whitespaces ignored
> Revert early returns for project consistency

- Src/FluentAssertions/AsyncAssertionsExtensions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Tests/FluentAssertions.Specs/FakeClock.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- docs/_pages/releases.md
> Fix timeout check in WithResult extension

- Src/FluentAssertions/Common/Configuration.cs
- Src/FluentAssertions/Common/Services.cs
- Src/FluentAssertions/Execution/TestFrameworkProvider.cs
- Src/FluentAssertions/Execution/XUnit2TestFramework.cs
- Tests/FluentAssertions.Equivalency.Specs/TypedDataSetSpecs.cs
- Tests/FluentAssertions.Specs/Execution/FallbackTestFrameworkTests.cs
- Tests/FluentAssertions.Specs/Execution/TestFrameworkProviderTests.cs
I've created some new tests (and minor refactoring) for better coverage in the namespace `Execution` according to #1823.
> Add unit tests for better coverage in Execution namespace

- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
I recall I didn't include this for `XUnit2.Specs` as `coverlet.collector` has problems running with `net47`, but we can run it with `net6`.
> Add code coverage to XUnit2.Specs

- Build/Build.cs
- Build/_build.csproj
Heavily inspired from the NUKE build pipeline
After checking something in the action outputs, I noticed this cool summary :)
If desired, I will add a summary to the tests as well ;-)
Looks like this now:
> Add fancy `ReportSummary`

- .github/ISSUE_TEMPLATE/03_general_feature.yml
This is meant for changes, that should be discussed first, but neither fit into the `bug` nor in the `api-proposal` template/category.
This looks like this:
> Add new issue template for a general feature

- Tests/FluentAssertions.Specs/Extensions/TimeSpanConversionExtensionSpecs.cs
In `FluentTimeSpanExtensions`
Main reason why I not simply deleted this method was, that this is part of the public API, and would be a potential "breaking" change.
> Add missing tests for `int.Seconds(TimeSpan)`

- Build/Build.cs
> Add test summaries

- Build/Build.cs
> Declare few more files as `DocumentationChanges`

- InstallPfx.bat
The referenced `WinRT81.Specs_TemporaryKey.pfx` was removed in dd5ecdbce385670bfa4e49f49bb60e6a56b00d3f
> Remove unused InstallPfx.bat

- Src/FluentAssertions/FluentAssertions.csproj
- Tests/Benchmarks/Benchmarks.csproj
- docs/_pages/releases.md
Declaring System.Net.Http as a nuget dependency for net47 is problematic for some consuming projects because it offers assembly version 4.1.1.3, whereas the FluentAssertions assembly itself references 4.2.0.0 of that same assembly. This causes the C# compiler to break the build for these projects.
The fix is to declare that System.Net.Http comes from an ordinary `Reference` item that is supplied by the target framework (which in fact it should as it does for FluentAssertions itself) instead of from the NuGet package.
It is interesting to call out that although this project previously declared `System.Net.Http` as a `PackageReference`, msbuild nevertheless chose to use the targeting framework version instead of the nuget version. This is ... not something I can explain. And many other …
> Declare System.Net.Http as a framework dependency

- .gitignore
- .nuke/build.schema.json
- Build/Build.cs
`build(.sh|.ps1) --generate-bin-log` or `build(.sh|.ps1) --generate-bin-log true` (same outcome)
> Add optional parameter to generate a `binlog` file

- Src/FluentAssertions/FluentAssertions.csproj
Remove the need to ever update the copyright year again by having MSBuild dynamically insert the current year.
> Dynamic copyright year

- .editorconfig
- Build/Build.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Tests/Benchmarks/CheckIfMemberIsBrowsable.cs
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/EnumSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Extensions/ObjectExtensionsSpecs.cs
My VS seems to prefer not having a space between attributes.
I don't care if there is space or not but I cannot find a e.ditorconfig setting that VS respects.
But found [`csharp_space_between_attribute_sections`](https://www.jetbrains.com/help/resharper/EditorConfig_CSHARP_SpacesPageSchema.html#resharper_csharp_space_between_attribute_sections) for ReSharper.
My VS also complains about this wanting a space between the commas which is contrary to e.g. https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/multidimensional-arrays#array-initialization 😞  
https://github.com/fluentassertions/fluentassertions/blob/454f16b54a88e2ebb5debbf7e40fab2937dfc147/Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs#L1992
> Styling to please both VS and Rider

- Tests/FluentAssertions.Equivalency.Specs/DataSpecs.cs
In this recent [run](https://github.com/fluentassertions/fluentassertions/actions/runs/4152072760) `FluentAssertions.Equivalency.Specs.DataColumnSpecs.When_MaxLength_does_not_match_and_property_is_not_excluded_it_should_fail` failed.
```
Error: [xUnit.net 00:00:01.14]     FluentAssertions.Equivalency.Specs.DataColumnSpecs.When_MaxLength_does_not_match_and_property_is_not_excluded_it_should_fail [FAIL]
16:00:47 [ERR] [xUnit.net 00:00:01.14]     FluentAssertions.Equivalency.Specs.DataColumnSpecs.When_MaxLength_does_not_match_and_property_is_not_excluded_it_should_fail [FAIL]
16:00:47 [DBG]   Failed FluentAssertions.Equivalency.Specs.DataColumnSpecs.When_MaxLength_does_not_match_and_property_is_not_excluded_it_should_fail [3 ms]
16:00:47 [DBG]   Error Message:
16:00:47 [DBG] …
```
> Use a fixed seed for random generator

- Src/FluentAssertions/DataColumnCollectionAssertionExtensions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
> Add missing xml docs for parameters

- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Data/DataRowAssertions.cs
- Src/FluentAssertions/Data/DataSetAssertions.cs
- Src/FluentAssertions/Data/DataTableAssertions.cs
- Src/FluentAssertions/Events/EventAssertions.cs
- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Src/FluentAssertions/Xml/XElementAssertions.cs
- Src/FluentAssertions/Xml/XmlElementAssertions.cs
- Tests/FluentAssertions.Equivalency.Specs/DataRowSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataSetSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlElementAssertionSpecs.cs
- docs/_pages/releases.md
Found a few places, where we would throw an NRE if the assertion was wrapped in an `AssertionScope`.
> Increase robustness of assertions when wrapped in an `AssertionScope`

- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
> Pluralize "key" in failure message

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertionsBase.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- docs/_pages/executiontime.md
- docs/_pages/releases.md
Any thoughts before I continue, @dennisdoomen, @jnyrup?
> Added `ThrowWithinAsync` assertions

- Src/FluentAssertions/Formatting/ExceptionValueFormatter.cs
- Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/NotThrowSpecs.cs
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- docs/_pages/releases.md
Fixes #2015 
Also modified some tests so the new formatting matches. It turns out that the current formatting scheme was not as good as simply using ToString.
Formatter before:
```
System.Exception with message "OuterExceptionMessage"
```
After:
```
System.Exception: OuterExceptionMessage
---> System.InvalidOperationException: InnerExceptionMessage
--- End of inner exception stack trace ---
```
> Use ToString to format exceptions

- FluentAssertions.sln.DotSettings
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/INode.cs
- Tests/FluentAssertions.Equivalency.Specs/BasicSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/CyclicReferencesSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/TestTypes.cs
- docs/_pages/releases.md
* Renamed some of the cyclic reference detection specs
* Removed two overlapping specs
* Moved two specs which had nothing to do with cyclic reference detection to `BasicSpecs`
* Added specs to properly cover the edge cases for deep object graphs.
* Ensured that the maximum depth is properly respecting the "official" definition of depth
Fixes #1993
> Ensured the maximum depth is properly respecting the "official" definition of depth

- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Tests/FluentAssertions.Specs/Exceptions/InnerExceptionSpecs.cs
The null checking of `Subject` in `AssertInnerExceptions` seems to irrelevant since https://github.com/fluentassertions/fluentassertions/commit/5f4f371e691d04cb4b205b6e195b450eb6e4207f where `ExceptionAssertions` was changed to having a more pure constructor.
No other assertions in `ExceptionAssertions` null checks `Subject`.
The second commit is a micro-optimization when asserting for an exact type.
The last two commits are cleanups
> Exception cleanup

- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
Some analyzer I played around with some time ago pointed out that we weren't awaiting these `Task`s.
> await `Task` when inside using block

- Src/FluentAssertions/Equivalency/EquivalencyAssertionOptions.cs
- Src/FluentAssertions/Equivalency/Ordering/PathBasedOrderingRule.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- docs/_pages/releases.md
I hope it's okay that I circumvented the "separate issue with api-approved label" since the feature I'm adding is essentially already there for "WithStrictOrderingFor".
> Add WithoutStrictOrderingFor overload with an expression

- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
When `FailWith` does not cause immediate termination we must guard against it.
On line 33 we checked if `subjectMember` was null, but we might continue execution, so this PR guards against executing `subjectMember.IsBrowsable`.
The test _triggers_ the problem, but I failed to find a way to properly verify it in the assertion part 🤔
> Prevent `NullReferenceException`

- Src/FluentAssertions/Equivalency/Ordering/PathBasedOrderingRule.cs
- Src/FluentAssertions/Equivalency/Ordering/PredicateBasedOrderingRule.cs
- Src/FluentAssertions/Equivalency/Steps/DataRowEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/EnumerableEquivalencyValidator.cs
- Src/FluentAssertions/Primitives/StringWildcardMatchingValidator.cs
As PolySharp generates `IsExternalInit` for older runtimes we can use init properties for at minimum internal types
> Use init properties

- Src/FluentAssertions/Common/MemberPathSegmentEqualityComparer.cs
- Src/FluentAssertions/Common/StringExtensions.cs
- Src/FluentAssertions/Equivalency/Node.cs
- Src/FluentAssertions/Equivalency/Ordering/PathBasedOrderingRule.cs
- Src/FluentAssertions/Equivalency/Selection/SelectMemberByPathSelectionRule.cs
- Src/FluentAssertions/Execution/MessageBuilder.cs
Per default `\d` and `[0-9]` is not the same.
See https://www.meziantou.net/dotnet-regex-d-is-different-from-0-9.htm
> Regex cleanup

- Src/FluentAssertions/Equivalency/Selection/ExcludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/SelectMemberByPathSelectionRule.cs
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- docs/_pages/releases.md
Fixes #1989 #1919
I removed the `!ContainsIndexingQualifiers(selectedPath)` check on this piece of code which was introduced here: https://github.com/fluentassertions/fluentassertions/commit/aab3303a1a227b6c35d66278ed88547dbc58f97a#diff-53539b5c2a4cdb7276ff5e63cbe410a164938d3620ebf08f20797810d22b394c. I am 100% unsure what it does and what the implications are of me removing it. However, there are no failing tests with the condition removed.
```c#
if (!ContainsIndexingQualifiers(selectedPath))  // <-- removed this
{
currentPath = RemoveIndexQualifiers(currentPath);
}
```
If removing this condition is bad for whatever reason, please tell me which test case I can add to cover this.
> Make Excluding() work on nested collections if root is a collection

- Src/FluentAssertions/Equivalency/EquivalencyValidationContext.cs
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Equivalency/Execution/CyclicReferenceDetector.cs
- Src/FluentAssertions/Equivalency/Execution/ObjectReference.cs
Some minor internal naming changes that I found while using the code in a workshop
> Some internal naming improvements

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Common/TypeMemberReflector.cs
- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
As preparation for #2152, I've extracted all the logic to identify the members of a type into a dedicated class.
> Extracts the type reflection logic into a dedicated class

- Directory.Build.props
- FluentAssertions.sln
- Src/FluentAssertions/CallerIdentification/MultiLineCommentParsingStrategy.cs
- Src/FluentAssertions/CallerIdentification/QuotesParsingStrategy.cs
- Src/FluentAssertions/CallerIdentification/SingleLineCommentParsingStrategy.cs
- Src/FluentAssertions/Common/ExpressionExtensions.cs
Updates to C# 11 and switches to list patterns a few places.
> Update to C# 11

- Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
Added 4 tests and one static member to DataSpec.
Most of them had to do with edge cases relating to primary keys in the corresponding match mode. I wasn't able to find how you could cover the Equals method on the ConpundKey, but the rest should be covered.
Part of #1823
> Improve the `DataRowCollectionEquivalency` code coverage

- Tests/FluentAssertions.Specs/Primitives/DateOnlyAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/TimeOnlyAssertionSpecs.cs
Mostly NotBe and BeNull that were missing coverage.
Part of #1823
> Improve the DateOnly and TimeOnly code coverage

- docs/_pages/releases.md
The changed line and the one above both referenced #1031
Found while answering https://stackoverflow.com/questions/75939296/
> fix link to PR in release notes

- .github/workflows/build.yml
- Build/_build.csproj
This switches the underlying coveralls reporter from [node-coveralls](https://github.com/nickmerwin/node-coveralls) to
[coverage-reporter](https://github.com/coverallsapp/coverage-reporter) which fixes two problems.
1) A deprecation notice in the github action output:
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
2) Files containing multiple types did not have coverage information on coveralls.io.
https://github.com/fluentassertions/fluentassertions/commit/9625e1f23773ad58d54e4b7ec4ad7bbfaed5229c partly fixed this by separating most types to separate files.
Left are files with multiple …
> Update to Coveralls v2

- Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
- Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs
- docs/_pages/releases.md
Prevent `InvalidOperationException` when formatting lambda expression calling a constructor
This fixes #2175
> Prevent `InvalidOperationException` when formatting lambda expression

- .github/workflows/build.yml
The new version of [coverallsapp](https://github.com/coverallsapp/github-action/releases/tag/v2.1.0) adds a new flag `allow-empty`, which returns error code `0`, i.e. no error, when the coverage file did not exist.
> Use builtin coveralls flag to ignore missing coverage file

- .github/workflows/build.yml
https://github.com/fluentassertions/fluentassertions/actions/runs/4713721247/jobs/8359603202?pr=2181
Fails with
> 🚨 ERROR: Couldn't find specified file: TestResults/reports/lcov.info
Seems I was wrong about what the new flag `allow-empty` meant.
Apparently it does not mean an empty _set_ of coverage files, but an empty _file_.
> Revert "Use builtin coveralls flag to ignore missing coverage file"

- docs/_pages/releases.md
Running the webpage locally gave this warning
```
Liquid Warning: Liquid syntax error (line 231): Unexpected character { in "{{{{` or `}}" in _pages/releases.md
```
Turns out `{{` was interpret as the start of a liquid template.
develop:
PR:
> Do not interpret double braces as liquid template

- Src/FluentAssertions/Collections/MaximumMatching/MaximumMatchingSolver.cs
- Src/FluentAssertions/Common/TypeMemberReflector.cs
- Src/FluentAssertions/Equivalency/Steps/DataColumnEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DictionaryInterfaceInfo.cs
- Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
I installed the latest .NET 8 preview SDK to see what new buit-in analyzers we can expect when .NET 8 is released later this year.
CA1859 suggests using concrete types instead of interfaces for (micro) performance reasons.
> Prepare for .NET 8 analyzers

- Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
- Tests/FluentAssertions.Equivalency.Specs/DataColumnSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
This improves coverage in 3 small cases.
For the generic dictionary one, it turns out that the other version of the method was length checking already which made the check redundant as it wasn't possible to hit that line in general.
Part of #1823
> Code coverage improvements

- Src/FluentAssertions/Equivalency/Steps/DictionaryInterfaceInfo.cs
- Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
In #2180 I spotted that `GenericDictionaryEquivalencyStep.AssertExpectationIsNotNull` checked if expectation was null, but that had already been done as the first thing in `EquivalencyResult Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)`.
This made it always true or from a mutation testing perspective, an unkillable mutation.
> Simplify `GenericDictionaryEquivalencyStep`

- .nuke/build.schema.json
- Build/Build.cs
- Build/_build.csproj
- Directory.Build.props
- Src/FluentAssertions/FluentAssertions.csproj
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
* Bumps Nuke to 7.0.0
* Bumps the Roslyn analyzers and disables a new rule we don't care about in tests
* Bump the remainder of our dependencies
~~* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.~~
~~* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).~~
~~* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).~~
~~* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the …
> Bump all dependencies

- Src/FluentAssertions/ObjectAssertionsExtensions.cs
- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertionsBase.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Streams/StreamAssertions.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
https://github.com/fluentassertions/fluentassertions/pull/2144#discussion_r1177338724 pointed out that we incorrectly added `Environment.Newline` as an argument, which due to how `StringValueFormatter` format strings, adds double quotes around the newline.
This bug was added in #712 by yours truly.
> Avoid quoting newlines

- .editorconfig
- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
- Src/FluentAssertions/Collections/StringCollectionAssertions.cs
- Src/FluentAssertions/Equivalency/Steps/ConstraintEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/GenericEnumerableEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/StructuralEqualityEquivalencyStep.cs
- Src/FluentAssertions/EventRaisingExtensions.cs
- Src/FluentAssertions/Events/EventMonitor.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Execution/CollectingAssertionStrategy.cs
- Src/FluentAssertions/Formatting/TimeSpanValueFormatter.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertionsBase.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
Fixes newly enabled .NET analyzers CA1860 rule. More information about the rule at https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1860
> CA1860: Avoid using 'Enumerable.Any()' extension method

- Src/FluentAssertions/Equivalency/Steps/EnumEqualityStep.cs
- Tests/FluentAssertions.Equivalency.Specs/EnumSpecs.cs
- docs/_pages/releases.md
Include because+becauseArgs when comparing collections of enums for equivalency.
When comparing just instances of enums, the reason was already set on the `AssertionScope` when entering `EnumEqualitySteps`.
I noticed that `EnumerableEquivalencyValidator.TryToMatch` and `EnumerableEquivalencyValidator.StrictlyMatchAgainst` creates a new `AssertionScope` without calling `scope.BecauseOf(context.Reason)`.
Couldn't tell on first sight if this was right 🤷‍♂️
> Include because+becauseArgs when comparing collections of enums for equivalency

- docs/_pages/collections.md
Since this new behaviour leads to some confusion, I gave it a quick mention in the docs.
Ref. #2216, #2126, #2109
> Add documentation for `IComparer<T>` overload

- Build/Build.cs
- Build/_build.csproj
- Directory.Build.props
- Src/FluentAssertions/CallerIdentification/MultiLineCommentParsingStrategy.cs
- Src/FluentAssertions/CallerIdentification/QuotesParsingStrategy.cs
- Src/FluentAssertions/CallerIdentification/SingleLineCommentParsingStrategy.cs
- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Src/FluentAssertions/Common/MethodInfoExtensions.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
> Bump nuget dependencies

- .editorconfig
- Build/Build.cs
- Src/FluentAssertions/Formatting/FormattedObjectGraph.cs
- Tests/.editorconfig
- Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
I installed the latest .NET8 preview to see what analyzers we would trigger.
These three lines trigger [CA1861: Avoid constant arrays as arguments](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1861)
https://github.com/fluentassertions/fluentassertions/blob/343e80ff81a0598f58d241ba7a4f1588e3fff35d/Src/FluentAssertions/Common/MemberPath.cs#L119
https://github.com/fluentassertions/fluentassertions/blob/343e80ff81a0598f58d241ba7a4f1588e3fff35d/Src/FluentAssertions/Common/StringExtensions.cs#L121
https://github.com/fluentassertions/fluentassertions/blob/343e80ff81a0598f58d241ba7a4f1588e3fff35d/Src/FluentAssertions/Equivalency/Execution/ObjectReference.cs#L42
As I see it, we have three options here:
* Follow the analyzer and extract the constant arrays to …
> Prepare for .NET8 analyzers

- Src/FluentAssertions/CallerIdentification/AddNonEmptySymbolParsingStrategy.cs
- Src/FluentAssertions/Common/Configuration.cs
- Src/FluentAssertions/Common/Guard.cs
- Src/FluentAssertions/Data/DataTableAssertions.cs
- Src/FluentAssertions/Equivalency/MemberFactory.cs
- Src/FluentAssertions/Equivalency/OrderingRuleCollection.cs
- Src/FluentAssertions/Equivalency/Steps/DataColumnEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DataRowCollectionEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DataSetEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/DataTableEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
- Src/FluentAssertions/Execution/LateBoundTestFramework.cs
- Src/FluentAssertions/Execution/NSpecFramework.cs
- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/EnumAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Types/MethodInfoSelector.cs
- Src/FluentAssertions/Types/PropertyInfoSelector.cs
- Src/FluentAssertions/Types/TypeSelector.cs
- Src/FluentAssertions/Xml/Equivalency/XmlReaderValidator.cs
- qodana.yaml
Went through the Qodana report and here are fixes to some that should be non-controversial.
This is in addition to be fixed in #2221.
There are a lot of warnings about unused methods/return values of public methods.
To silence them, it seems the idiomatic way is to annotate them with [`[PublicAPI]`](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#PublicAPIAttribute)
> Qodana fixes

- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- docs/_pages/basicassertions.md
- docs/_pages/releases.md
> Added `Be`, `NotBe` and `BeOneOf` for object comparisons with custom comparer

- Src/FluentAssertions/CallerIdentification/CallerStatementBuilder.cs
- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Common/TypeMemberReflector.cs
- Src/FluentAssertions/Equivalency/ConversionSelector.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPredicateSelectionRule.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/StringBuilderExtensions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
I installed the latest .NET 8 preview 7 and the updated analyzers pointed out some new stuff.
> Analyzer cleanups

- Src/FluentAssertions/FluentAssertions.csproj
To increase the readability of the csproj file, I've grouped toe framework dependent configuration. I also added some `Label`'s.
> Group framework dependent configuration

- .github/workflows/code_quality.yml
Changed the workflow that invokes Qodana to always run the GHA workflow that is part of the target branch (using the `pull_request_target`). This should hopefully allow it to be run on PRs coming from forks as well.
> Another Qodana test from the same repository

- Src/FluentAssertions/Equivalency/Steps/AutoConversionStep.cs
- Tests/FluentAssertions.Equivalency.Specs/MemberConversionSpecs.cs
- docs/_pages/releases.md
`Enum.IsDefined` throws an `ArgumentException` if the value is of different enum type or different underlying integral type.
`Enum.IsDefined` allows strings, but `Enum.ToObject` does _not_ and throws an `ArgumentException`.
This fixes #2259
> Fix auto conversion to enums

- .github/ISSUE_TEMPLATE/01_bug_report.yml
- .github/ISSUE_TEMPLATE/02_api_proposal.yml
- .github/ISSUE_TEMPLATE/03_general_feature.yml
Inspired from the issue templates of NUKE
Main reason for this change is: If  one can help with a PR he should have the possibility of "first blood" on his issue.
> Add a pre-check if a user can help with a PR

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.NotContainItemsAssignableTo.cs
- docs/_pages/collections.md
- docs/_pages/releases.md
New API method for checking that collection does not contain any element assignable to given type
Issue: https://github.com/fluentassertions/fluentassertions/issues/2249
> Add `NotContainItemsAssignableTo`

- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlElementAssertionSpecs.cs
- Tests/VB.Specs/VB.Specs.vbproj
- Tests/VB.Specs/VBSpecs.vb
- qodana.yaml
> Fix qodana issues part 2

- docs/_pages/releases.md
#2144 was introduced in 6.12 and not 6.11
> Move "Format records and anonymous objects with their member values" to the correct release

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- docs/_data/mstest-migration/assert.yml
- docs/_pages/releases.md
> Remove obsolete `OrEqualTo` methods

- docs/_pages/collections.md
Closing parenthesis was added to the code block in the "special overloads" section of the `collections.md` file.
I ran the `spellcheck` command with success, though a warning did occur; not sure if it's important, but I've included the results below.
> added closing parenthesis in docs (collections.md)

- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- docs/_pages/extensibility.md
- docs/_pages/releases.md
`SpacesPerIndentionLevel` was added in #1295 but #1469 stopped using it.
Both these PRs where while making v6, so `SpacesPerIndentionLevel` has never worked in any released version of Fluent Assertions.
Not sure what to put in the release notes (if anything) 🤔 
This fixes #2197
> Remove `SpacesPerIndentionLevel`

- Build/Build.cs
We've seen two cases where `GitVersion` could not be injected and later in the pipeline `Libgit2Sharp` failed to extract the source branch name.
See longer discussion in #2301
> Make Gitversion+GitRepository required

- Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
Silence another case of [CA1859](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1859) after updating to .NET 8 RC1.
The alternative of changing the fields to `int[]` and `string[]` would then require casts to `IEnumerable<>` later as the array types only exposes the non-generic `GetEnumerator()` directly.
> Silence CA1859

- .github/workflows/code_quality.yml
According to JetBrains, in order for Qodana to properly detect .NET 4.7 usage, we need to run the build on Windows.
> Run the Qodana on Windows so .NET 4.7 scanning works.

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Common/TypeMemberReflector.cs
- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/Matching/TryMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/MemberFactory.cs
- Src/FluentAssertions/Equivalency/MemberVisibility.cs
- Src/FluentAssertions/Equivalency/Selection/AllFieldsSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/AllPropertiesSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Equivalency/Selection/IncludeMemberByPredicateSelectionRule.cs
- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Tests/Approval.Tests/ApiApproval.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/TestTypes.cs
- docs/_pages/releases.md
* When trying to find a property on the subject to match the one on the expectation, if a normal property exists next to an implicitly implemented one, the normal property will be selected.
* Some tests related to explicit interface implementations assumed a dependency on whether or not `RespectingDeclaredTypes` and `RespectingRuntimeTypes` was used. But those options don't affect the subject.
* The `WithMapping` construct also didn't support mapping to properties implemented through explicitly-implemented interfaces.
* Removed the "non-private" part names since visibility is now used to find members
**Note**   I had to extend `MemberVisibility` to optionally include explicitly implemented members. This _could_ be perceived as a breaking change. But it won't affect consumers, so for now, …
> Ensure explicitly implemented members are discoverable in BeEquivalentTo

- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs
This also ref. qodana complaining about 'Method return value is never used'
> Add missing `DateTimeOffset` assertions

- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllBeAssignableTo.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllBeOfType.cs
While working on #2321 I noticed that some other assertions on `GenericCollectionAssertions` did support vacuous truths, but no tests verified that.
> Test that collection assertions supports vacuous truths

- .nuke/build.schema.json
- Build/Build.cs
If I watch the build pipeline I find it sometimes difficult to distinguish between the `UnitTestsNetFramework` and `UnitTestsNewerFrameworks` when the log is quickly passing by :)
So I renamed them to fit more what's actually done.
> Rename the unit test steps to match what's done inside the steps

- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs
- docs/_pages/releases.md
> Pass down the reason to inner `AssertionScope`

- Src/FluentAssertions/Common/TypeMemberReflector.cs
- Tests/Benchmarks/TypeMemberReflectorBenchmarks.cs
Picking some low-hanging fruits in `TypeMemberReflector` to speed it up a bit.
The `_Old` suffix is the version of `TypeMemberReflector` in `develop`.
The "Ratio" column is manually calculated as `new / old`
|                                    Method |     Mean | Ratio |     Error |    StdDev |   Gen0 | Allocated | Ratio |
|------------------------------------------ |---------:|------:|----------:|----------:|-------:|----------:|------:|
|                                   Publicc | 2.759 us |  0.55 | 0.0548 us | 0.0631 us | 0.5646 |   3.46 KB |  0.60 |
|                               Publicc_Old | 5.006 us |       | 0.0433 us | 0.0384 us | 0.9384 |   5.77 KB |       |
|                           Public_Internal | 4.190 us |  0.60 | 0.0386 us | 0.0342 us | 0.8240 |   5.06 KB |  0.70 |
| …
> Optimize `TypeMemberReflector`

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllSatisfy.cs
- docs/_pages/releases.md
> Change `AllSatisfy` to succeed on empty collections

- Tests/Benchmarks/TypeMemberReflectorBenchmarks.cs
> Add missing `internal` modifier for `TypeMemberReflector` benchmarks

- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Execution/ContinuedAssertionScope.cs
- Src/FluentAssertions/Execution/IAssertionScope.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Execution/AssertionScope.ChainingApiSpecs.cs
- docs/_pages/releases.md
Until 6.12 you are not able to chain `.ForConstraint()` after `.Then`.
The only possibility for was to check `.ForConstraint()` first and then chain all subsequent assertions with `.Then`.
This leads to following issue: you cannot pre-check for e.g. `null` or empty, which leads to multiple sets of `Execute.Assertions...` to check every possible failure first.
This PR introduces this `.ForConstraint()` to the contract `IAssertionScope` to make this before mentioned possible.
Closes #1918
> Add `ForConstraint` to `IAssertionScope`

- Tests/FluentAssertions.Specs/Execution/AssertionScope.ChainingApiSpecs.cs
| Before | After |
|--------|--------|
|  ![image](https://github.com/fluentassertions/fluentassertions/assets/44049228/c97da9fc-794e-4742-ad53-6901cd6d7adc) |  ![image](https://github.com/fluentassertions/fluentassertions/assets/44049228/dc4682d8-e8d5-4d58-a743-2ca1433a37c9)| 
Ref. #1823
> Add missing test for `because` is `null`

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.OnlyContain.cs
- docs/_pages/releases.md
This ref: https://github.com/fluentassertions/fluentassertions/pull/2321#issuecomment-1737853301
And: https://github.com/fluentassertions/fluentassertions/issues/1492
> Change `OnlyContain` to succeed on empty collections

- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Src/FluentAssertions/Primitives/DateOnlyAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
- Src/FluentAssertions/Primitives/GuidAssertions.cs
- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
- Src/FluentAssertions/Primitives/TimeOnlyAssertions.cs
- Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs
- Src/FluentAssertions/Types/TypeSelectorAssertions.cs
Update grammar for lines "Gets the object _which_ value is being asserted" to "Gets the object _whose_ value is being asserted". No changes to API or updates to functionality. For issue #2353
> Grammatical changes of "which" to "whose"

- Src/FluentAssertions/Common/StringExtensions.cs
- Src/FluentAssertions/Primitives/StringEqualityStrategy.cs
- Src/FluentAssertions/Primitives/StringValidator.cs
- Tests/FluentAssertions.Equivalency.Specs/BasicSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/CyclicReferencesSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/NestedPropertiesSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.Be.cs
- Tests/FluentAssertions.Specs/Types/PropertyInfoAssertionSpecs.cs
- docs/_pages/releases.md
When asserting that two strings are equal, and one of the strings is longer than 8 characters or contains a NewLine, instead of simply stating at which index the first difference occurs, this difference is made visible using arrows, e.g.
```csharp
var subject = "this is a long text that differs in between";
var expected = "this was too short";
subject.Should().Be(expected, "because we use arrows now");
```
throws with message
```
Expected subject to be the same string because we use arrows now, but they differ at index 5:
↓ (actual)
"this is a long text…"
"this was too short"
↑ (expected)."
```
For multi-line strings, instead of only providing information about the index, the failure message also contains the line and column information, e.g. `…but they differ on line 5 and column 1 …
> Improve failure message for string assertions when checking for equality

- cSpell.json
- docs/_pages/releases.md
Since typos are awkward in every case :)
> Do not ignore `cSpell` on releases.md anymore

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/NonGenericAsyncFunctionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- docs/_pages/releases.md
- qodana.yaml
As listed in #1677 and started in #1972, I converted AsyncFunctionAssertions into "real" base class (protected constructor).
Further, I moved some methods from base class into concrete class to prevent from overwriting (using `new` keyword).
> Converted AsyncFunctionAssertions into real base class

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
This ref. and hopefully closes #2352
> Add a note to XML-docs that explains the `(Not)ContainEquivalentOf` problem

- Src/FluentAssertions/Specialized/ActionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- docs/_pages/releases.md
Gid rid of more `new` modifiers.
Similar to what we did in #2359
On [grep.app](https://grep.app/search?q=DelegateAssertions&filter[repo][0]=kzrnm/ac-library-csharp) I found a single usage of `DelegateAssertions` and that used the generic `Throw<TException>` which does not change in this PR.
> Move non-generic `NotThrow[After]` to `ActionAssertions`

- Src/FluentAssertions/Common/TypeExtensions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.Implement.cs
Inspired by https://github.com/fluentassertions/fluentassertions/pull/2358#discussion_r1355137402 I had a look at other places we work with interfaces.
I benchmarked the difference between `GetInterfaces().Contains` and `IsAssignableFrom`
| Method              | Mean     | Error    | StdDev   | Ratio | Gen0   | Allocated | Alloc Ratio |
|-------------------- |---------:|---------:|---------:|------:|-------:|----------:|------------:|
| GetInterfaces       | 24.97 ns | 0.290 ns | 0.257 ns |  1.00 | 0.0051 |      32 B |        1.00 |
| AssignableFrom      | 10.97 ns | 0.037 ns | 0.034 ns |  0.44 |      - |         - |        0.00 |
| GetInterfacesNoLinq | 14.35 ns | 0.261 ns | 0.244 ns |  0.58 | 0.0051 |      32 B |        1.00 |
<details>
<summary>benchmark code</summary>
```cs
using …
```
> Use targeted methods instead of LINQ

- Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
- Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs
- docs/_pages/releases.md
Fixes: #2308 
~~**Note**: The very first two commits are to fix the actual problem. Commit 3-6 are for code quality (and therefore can moved to a separate PR if needed).~~
> Handle comparing an `IDictionary` subject with an `IDictionary<,>` expectation

- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
- docs/_pages/releases.md
> Pass `FormattingOptions` to inner `AssertionScope`

- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.HaveCountGreaterThanOrEqualTo.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.HaveCountLessThanOrEqualTo.cs
- Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/SimpleTimeSpanAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/AssemblyAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- qodana.yaml
Qodana is failing due to "The number of problems exceeds the fail threshold".
This was a surprise to me, because no PR was merged which had other than "Qodana alright!"-messages.
As I dug into the logs (and also checked the uploaded results on qodana.cloud) I realized, that sometimes `develop` (with the correct fail threshold) and sometimes `refs/heads/develop` (which has a higher fail rate) is chosen from qodana. I couldn't figure out when this happens.. seems a little random to me.
As a possible solution we could try the hint from YouTrack: https://youtrack.jetbrains.com/issue/QD-7084/Getting-refs-heads-branch-instead-of-just-branch-Qodana-GitHub-Actions#focus=Comments-27-8090586.0-0
Note: 
- I think the real impact will be seen only after this is merged.
- The diffenences between this …
> Ignore ` UnusedMember.Global` Qodana scan rule and add missing tests

- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- qodana.yaml
> Add missing chaining test for "Method return value is never used"

- Src/FluentAssertions/Primitives/BooleanAssertions.cs
- Tests/FluentAssertions.Specs/Primitives/BooleanAssertionSpecs.cs
- docs/_pages/releases.md
Display `true` and `false` as capitalized rather than in lowercase so that both expected value and actual value uses the same casing. 
**Before**: `Expected boolean to be false, but found True.`
**After**:   `Expected boolean to be False, but found True.`
> Capitalize true and false in failure messages

- FluentAssertions.sln
- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/CustomAssertionsAssemblyAttribute.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/ExampleExtensions/AssemblyInfo.cs
- Tests/ExampleExtensions/ExampleExtensions.csproj
- Tests/ExampleExtensions/StringAssertionExtensions.cs
- Tests/FluentAssertions.Specs/ExtensibilitySpecs.cs
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- docs/_pages/introduction.md
- docs/_pages/releases.md
Instead of marking individual methods with the `[CustomAssertion]`, you can now add the `[assembly: CustomAssertionsAssembly]` attribute to a file within the project to tell Fluent Assertions that all code in that assembly should be treated as custom assertion code.
Part of the solution to resolve #2002
> Introduces an attribute to mark an entire assembly as one that contains custom assertions.

- .nuke/build.schema.json
- Build/Build.cs
- Build/Configuration.cs
1. Made the solution build configuration a build parameter
2. Use the `Debug` configuration for a local build
3. Use the `CI` configuration on a server
Needed this to get a local package for testing #2002
> Allow specifying the build configuration.

- Src/FluentAssertions/Common/TimeOnlyExtensions.cs
- Src/FluentAssertions/Equivalency/Execution/ObjectReference.cs
- qodana.yaml
> A few fixed qodana issues

- Src/FluentAssertions/Primitives/BooleanAssertions.cs
> Pass Boolean literals as becauseArguments

- Src/FluentAssertions/Numeric/NumericAssertions.cs
- Src/FluentAssertions/Types/PropertyInfoAssertions.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/PropertyInfoAssertionSpecs.cs
- docs/_pages/releases.md
Inspired by #2398 I searched for more places where we don't guard continued assertions.
> Improve failure message for `NotBeOfType` and `BeReadable`/`BeWritable`

- Src/FluentAssertions/Specialized/ActionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
From my understanding this shouldn't make any difference, but increase the code coverage
Alternatively we just could remove the unsed constructor, but this would be a breaking change.
> Use base class constructor in delegate assertions

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/DelegateAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- docs/_pages/releases.md
> Do not continue asserting on the concrete exception type when the exception is `null`

- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveExplicitMethod.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.HaveExplicitProperty.cs
- docs/_pages/releases.md
> Guard methods against assertion scope `[Not]HaveExplicit(Property|Method)`

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Primitives/ObjectAssertions.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
Unless `Subject.Should()` resolves to a another overload of `Should` than the initial `sut.Should()`, calling `Subject.Should().Foo()` instead of `Foo()` directly should not add any value, but on the negative side lengthen the stack trace in case the assertion fails.
> Remove unecessary call to `Subject.Should()`

- Tests/Approval.Tests/ApiApproval.cs
- Tests/Approval.Tests/Approval.Tests.csproj
* Simplify how paths relative to the solution directory are accessed.
* Actually use the Verify.DiffPlex integration instead of using DiffPlex directly.
> Simplify the ApiApproval test

- Src/FluentAssertions/Common/TypeMemberReflector.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- docs/_pages/releases.md
This fixes #2409 
I guess this is what I meant with this [comment](https://github.com/fluentassertions/fluentassertions/pull/1575#discussion_r641972449)
> Exclude `private protected` members from `BeEquivalentTo`

- docs/_data/tips/datetimes.yml
The tips got lost in #813.
#843 restored all but one.
before:
after:
> Restore `DateTime` tips

- Src/FluentAssertions/Equivalency/EqualityStrategyCache.cs
- Src/FluentAssertions/Equivalency/EqualityStrategyProvider.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
Refactor according to [this comment](https://github.com/fluentassertions/fluentassertions/blob/6.12.0/Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs#L029) in the `SelfReferenceEquivalencyAssertionOptions`:
Extract the private fields `referenceTypes`, `valueTypes`, `getDefaultEqualityStrategy` and `equalityStrategyCache` to a dedicated class `EqualityStrategyProvider`.
* [] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
> Add EqualityStrategyProvider for `SelfReferenceEquivalencyAssertionOptions`

- Tests/FluentAssertions.Specs/Common/ConfigurationSpecs.cs
Add missing tests for [`Configuration.cs`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Common/Configuration.cs).
See #1823
> Add missing tests for `Configuration`

- Src/FluentAssertions/Common/MemberPathSegmentEqualityComparer.cs
- Src/FluentAssertions/Formatting/DateOnlyValueFormatter.cs
- Src/FluentAssertions/Formatting/TimeOnlyValueFormatter.cs
- Src/FluentAssertions/Primitives/DateOnlyAssertions.cs
- Src/FluentAssertions/Primitives/NullableDateOnlyAssertions.cs
- Src/FluentAssertions/Primitives/NullableTimeOnlyAssertions.cs
- Src/FluentAssertions/Primitives/TimeOnlyAssertions.cs
- Tests/Benchmarks/TypeMemberReflectorBenchmarks.cs
- Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.HaveCountGreaterThan.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.HaveCountGreaterThanOrEqualTo.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.HaveCountLessThan.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.HaveCountLessThanOrEqualTo.cs
- Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/NotThrowSpecs.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateOnlyAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.BeLessThan.cs
- Tests/FluentAssertions.Specs/Specialized/DelegateAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
Remove unused using directives which also result in warnings from ReSharper or Qodana.
> Remove unused using directives

- Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
The `ExpressionVisitor.Visit` method can accept `null` as node expression (see [here (.NET core)](https://source.dot.net/#System.Linq.Expressions/System/Linq/Expressions/ExpressionVisitor.cs,f0615a823a9efe36) or [here (.NET Framework 4.8)](https://referencesource.microsoft.com/#System.Core/Microsoft/Scripting/Ast/ExpressionVisitor.cs,f0615a823a9efe36)).
This fixes a `Possible 'System.NullReferenceException'` in #2450
> Avoid possible 'System.NullReferenceException' in `PredicateLambdaExpressionValueFormatter`

- Build/Build.cs
- Build/_build.csproj
- package.json
- yarn.lock
The dependabot cSpell update failed, because it requires node >= ^18.
Since 10 hours the newset LTS Node.js.redist package ist available on nuget :)
> Bump cSpell to 8.0.0

- .github/workflows/build.yml
Since we do not support .NET Core 2.1.x and 3.1.x anymore nor test against this TFMs I think we don't need to set them up in the build pipline.
> Remove .NET Core 2.1.x and 3.1.x from build SDK setup

- Tests/FluentAssertions.Specs/Specialized/ActionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/DelegateAssertionSpecs.cs
Fixes `Method return value is never used (non-private accessibility)` in #2450
> Add missing tests for ActionAssertions and DelegateAssertions

- Src/FluentAssertions/CallerIdentifier.cs
Fix issue detected by ReSharper:
- Possible 'null' assignment to non-nullable entity
> Avoid possible 'null' assignment in `CallerIdentifier`

- Build/Build.cs
- Src/FluentAssertions/Formatting/Formatter.cs
Fix ﻿"Variable in local function hides variable from outer scope"
- Src\FluentAssertions\Formatting\Formatter.cs:111 Parameter 'output' hides outer local variable with the same name
- Build\Build.cs:127 Parameter '_' hides outer parameter with the same name
- Build\Build.cs:133 Parameter '_' hides outer parameter with the same name
- Build\Build.cs:179 Parameter '_' hides outer parameter with the same name
- Build\Build.cs:209 Parameter '_' hides outer parameter with the same name
- Build\Build.cs:242 Parameter '_' hides outer parameter with the same name
- Build\Build.cs:245 Parameter '_' hides outer parameter with the same name
- Build\Build.cs:301 Parameter '_' hides outer parameter with the same name
- Build\Build.cs:319 Parameter '_' hides outer parameter with the same name
- …
> Avoid variable in local function that hides variable from outer scope

- Src/FluentAssertions/Polyfill/StringBuilderExtensions.cs
- qodana.yaml
> Disable qodana rules in poly fills

- .github/workflows/code_quality.yml
Add `-EAP` to argument for Qodana Scan as Qodana currently only supports .NET 8 in the EAP (Early-Access Program):
https://youtrack.jetbrains.com/issue/QD-7660/Qodana-busted-in-.NET-8-RTM
> Use Qodana EAP to support .NET 8

- .github/workflows/code_quality.yml
As was recommended by my contact at JetBrains, they've released a new version and we had to switch back.
> Switch back to the release version of Qodana (to officially support .NET 8)

- .github/workflows/code_quality.yml
- profile.yaml
- qodana.yaml
This PR turns off RoslynAnalyzers in Qodana by introducing new profile that is based on qodana.starter. This profile creates group InspectionsToExclude and excludes them from the default sets.
> Turn off RoslynAnalyzers in Qodana WF

- Src/FluentAssertions/Equivalency/Steps/EnumerableEquivalencyStep.cs
- Tests/FluentAssertions.Equivalency.Specs/BasicSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/TestTypes.cs
- docs/_pages/releases.md
- qodana.yaml
This finishes #2445 
Al the credit goes to @ShaharPrishMSFT
> Fix issue when an empty ArraySegment is a member of a class

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.BeEmpty.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.BeNullOrEmpty.cs
- Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.BeEmpty.cs
- Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.BeEmpty.cs
- Tests/FluentAssertions.Specs/Primitives/ReferenceTypeAssertionsSpecs.cs
- Make BeEmpty() materialize only the first item, as no further processing is needed for validation
- The error message now mentions "but found at least one item" and outputs the said item
Fixes #2490
> BeEmpty() materializes IEnumerable<T> only once, even on failure

- yarn.lock
**Reason:**
Before it had a strange error when running `yarn install` (GHA build _and_ locally)
After googling this error I found this issue: https://github.com/yarnpkg/yarn/issues/4812
And one of the tips was: https://github.com/yarnpkg/yarn/issues/4812#issuecomment-1193692415
So I deleted the lock file and run `yarn install` again, but this time it installs the latest 8 (8.3.2 at this moment) and the error was gone afterwards
> Bump cspell to 8.3.2

- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentifierSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/BooleanAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/DateOnlyAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/NullableBooleanAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.Be.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.BeOneOf.cs
- Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
Fix "redundancies in code" issues detected by ReSharper:
- Using directive is not required by the code and can be safely removed
- Redundant explicit array size specification
- Redundant 'class' keyword in record declaration
- Type argument specification is redundant
- Redundant string interpolation
- Expression is always true/false
- The field is always assigned before being used and can be converted into a local variable
> Avoid redundancies in code

- Src/FluentAssertions/Primitives/DateTimeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.BeIn.cs
- docs/_pages/datetimespans.md
- docs/_pages/releases.md
> Add missing `NotBeIn(DateTimeKind)` `DateTime` assertion

- Tests/FluentAssertions.Extensibility.Specs/AssertionEngineInitializer.cs
To address https://github.com/fluentassertions/fluentassertions/pull/2292#issuecomment-1781529207, I've added an additional `[AssertionEngineInitializer]` assembly attribute to point to an initializer method that throws. That should cover a bit more of the code in `Services.ExecuteCustomInitializers`.
> Added an extra assertion engine initializer that throws for extra coverage

- CONTRIBUTING.md
As mentioned [in this comment](https://github.com/fluentassertions/fluentassertions/pull/2413#issuecomment-1875521816) the convention in this project is to use [rebase](https://git-scm.com/docs/git-rebase) instead of [merge](https://git-scm.com/docs/git-merge) when updating a local branch.
I added this to the `DOs and DON'Ts` section in Contributing.md
> Document preference of rebase over merge when updating local branches

- qodana.yaml
Using `frameworks:` property one could limit analysed TFMs.
> Update qodana.yaml to limit target frameworks

- Tests/Approval.Tests/ApiApproval.cs
[xUnit.net 2.6.5][1] introduced a new `AddRange` method that can be used to simplify the implementation of `TargetFrameworksTheoryData`.
[1]: https://xunit.net/releases/v2/2.6.5
> Simplify the API approval test

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/XmlAssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
- docs/_pages/releases.md
Compelling example:
```csharp
[Theory]
[InlineData(true)]
[InlineData(false)]
public void Test1(bool currentUser)
{
IPrincipal principal = currentUser ? new WindowsPrincipal(WindowsIdentity.GetCurrent()) : new ClaimsPrincipal();
IIdentity? identity = principal.Identity;
identity.Should().NotBeOfType<GenericIdentity>();
identity.IsAuthenticated.Should().BeFalse();
}
```
Fixes #1115
> Add [NotNull] attribute on the Should() method for object assertions

- Src/FluentAssertions/Formatting/MultidimensionalArrayFormatter.cs
- Tests/.editorconfig
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/ExtensibilitySpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Accessibility.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Basic.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Browsability.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Covariance.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Including.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.MemberHiding.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScope.ChainingApiSpecs.cs
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.BeDataContractSerializable.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.BeXmlSerializable.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
- qodana.yaml
**Note to Reviewer** commit-by-commit. 
Since PRs cannot be used to verify the net affect, check out https://github.com/fluentassertions/fluentassertions/actions/runs/7512592573
> Address various Qodana issues to bring the threshold back to 0

- Src/FluentAssertions/Common/StringExtensions.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.MatchEquivalentOf.cs
- docs/_pages/releases.md
As mentioned in #2566 treating the verbatim string `@"\r\n"` as a newline seems suspicius, as it is equivalent to `"\\r\\n"`.
> Avoid treating `"\\r\\n"` as new line.

- Src/FluentAssertions/FluentAssertions.csproj
Use the `PublicKey` MSBuild property to simplify the PublicKey configuration
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#internalsvisibleto
In addition to #2300
> Simplify InternalsVisibleTo PublicKey

- README.md
In https://github.com/fluentassertions/fluentassertions/pull/1906 we agreed in changing the badge in README to master.
This PR restores this :)
> Revert coveralls badge to `master`

- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Src/FluentAssertions/Execution/AssertionScope.cs
- Tests/FluentAssertions.Specs/Execution/AssertionScope.MessageFormatingSpecs.cs
ba6028ba85b6e7326c5c8ab84cdd2e221ebcd34a:
#2607 added chaining of nested contexts.
It always creates a new `Lazy<string>` but we do allow a null `Context`
https://github.com/fluentassertions/fluentassertions/blob/e760ba4fa8a17987a761c713a6bd92813ce8f764/Src/FluentAssertions/Execution/AssertionScope.cs#L316
So if both context are null, we can then then avoid creating a new context.
Also if one of the contexts are null, we can just return the other one.
Now we only need to create a new context in the last case where we have two non-null contexts.
As the lambda passed to the new `Lazy<string>` takes a closure over the other contexts, one needs to take some care to avoid always allocating the closure object.
* Dev: What's currently in develop
* Foo: The prettiest code using both switch …
> Avoid allocations when chaining contexts

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- docs/_pages/releases.md
When the subject `Task` was canceled we did not recognize that.
Instead we got a non-faulting (but canceled) task when awaiting `Task.WhenAny`.
This fixes #2444
> Make `ThrowWithinAsync` respect canceled tasks

- Src/FluentAssertions/Common/StringExtensions.cs
- Src/FluentAssertions/Equivalency/Execution/CollectionMemberOptionsDecorator.cs
- Src/FluentAssertions/Equivalency/IEquivalencyOptions.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyOptions.cs
- Src/FluentAssertions/Equivalency/Steps/StringEqualityEquivalencyStep.cs
- Src/FluentAssertions/Primitives/StringAssertions.cs
- Src/FluentAssertions/Primitives/StringWildcardMatchingStrategy.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllBeEquivalentTo.cs
- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.BeEquivalentTo.cs
- Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.BeEquivalentTo.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.BeEquivalentTo.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.ContainEquivalentOf.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.EndWithEquivalentOf.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.MatchEquivalentOf.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.StartWithEquivalentOf.cs
- docs/_pages/releases.md
- docs/_pages/strings.md
Add the following option to the `EquivalencyAssertionOptions<T>` for strings
```C#
public EquivalencyAssertionOptions<T> IgnoringNewlineStyle()
{
// This will replace "\r\n" with "\n" in actual and expected before comparison
return this;
}
```
This fixes #2612 and fixes #2566
> Add option to ignore newline style when comparing strings for equivalency

- .github/workflows/code_quality.yml
Need to temporally roll back GH action, to fix the experienced issue.
> Roll back qodana-action to v2023.3

- Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs
The changes in #2643 triggered another analyzer.
Probably because the signature of `Compare(T? x, T?)` says that either of `x` and `y` could be null.
This change way the simplest way (in terms of lines of code) to satisfy the analyzers.
> Handle null comparands

- Src/FluentAssertions/Equivalency/Steps/EqualityComparerEquivalencyStep.cs
- Tests/FluentAssertions.Equivalency.Specs/AssertionRuleSpecs.cs
- docs/_pages/releases.md
The way the `EqualityComparerEquivalencyStep<T>` step is comparing the comparand's type against the equality comparer's type has been reviewed to take into account nullables.  
This fixes #2595.
> Fixed `BeEquivalentTo` when using a custom comparer targeting nullable types

- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Primitives/ReferenceTypeAssertionsSpecs.Satisfy.cs
- Tests/FluentAssertions.Specs/Primitives/ReferenceTypeAssertionsSpecs.cs
- docs/_pages/basicassertions.md
- docs/_pages/releases.md
Added support for `Satisfy` on `ReferenceTypeAssertions` allowing to use element inspectors as an alternative to using predicates on Match.
Example:
```cs
var myDto = new Dto { Name = "Some Name" };
myDto.Should().Satisfy<Dto>(dto => dto.Name.Should().Be("Some Name"));
```
Fixed #2516
> Add support for `Satisfy` on `ReferenceTypeAssertions`

- Src/FluentAssertions/Formatting/DateTimeOffsetValueFormatter.cs
- Src/FluentAssertions/Formatting/FormattedObjectGraph.cs
- Src/FluentAssertions/Formatting/GuidValueFormatter.cs
- Src/FluentAssertions/Formatting/StringValueFormatter.cs
- Src/FluentAssertions/Formatting/TaskFormatter.cs
Removed unreachable path.
I think we can rely on the return value of `CanHandle()` that we are dealing with a `Task`.
I tried to get into the `Format` method using `Formatter.Format((Task)null)`, but I always ended up in the `NullFormatter`.
An interpolated string has no missed branches for whatever reason.
Removed an unused method, which was introduced in https://github.com/fluentassertions/fluentassertions/pull/2144
Since we first check in `HasTime` that the value also could have milli seconds, the `if` branch can never be entered
> Improve code coverage in `...Formatter`s

- Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.BeGreaterThan.cs
- Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.BeLessThan.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.BeGreaterThan.cs
- Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.BeLessThan.cs
`ByteAssertions`
`NullableByteAssertions`
`NullableInt*Assertions`
`NullableUInt*Assertions`
> Add missing tests for several `NumericAssertions`

- Src/FluentAssertions/Execution/AssertionScope.cs
- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/Formatting/FormattingOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Execution/AssertionScope.ScopedFormatters.cs
- docs/_pages/extensibility.md
- docs/_pages/introduction.md
- docs/_pages/releases.md
> Add scoped value formatters

- docs/_pages/extensibility.md
Continuing https://github.com/fluentassertions/fluentassertions/pull/2685 in a separate PR, due to my wrong branching choice
Description from original PR:
> There are (at least) two pages in the docs, that describe creating custom assertion methods - [Introduction](https://fluentassertions.com/introduction#subject-identification) and [Extensibility](https://fluentassertions.com/extensibility/#building-your-own-extensions)
> 
> `[CustomAssertion]` attribute is only mentioned in _Introduction_, along with a description of why including it is important, whereas in _Extensibility_ there is no mention of that attribute, and people googling https://www.google.com/search?q=fluent+assertions+how+to+create+custom+assertion will more likely land on _Extensibility_ rather than _Introduction_
> 
> …
> Add `[CustomAssertion]` attribute to extensibility docs

- Tests/TestFrameworks/MSTestV2.Specs/FrameworkSpecs.cs
- Tests/TestFrameworks/MSpec.Specs/FrameworkSpecs.cs
- Tests/TestFrameworks/NUnit3.Specs/FrameworkSpecs.cs
- Tests/TestFrameworks/XUnit2.Specs/FrameworkSpecs.cs
While it makes sense not to take hard dependencies on test frameworks in the FluentAssertions library, the TestFrameworks specs all have a dependency on the their respective test frameworks. Use them to simplify the assertion on the exceptions which should be thrown.
Note that the support for NUnit4 was introduced exactly like this in 2f56211b769b7a9a10b619d8f3a2d868dd473735.
> Simplify FrameworkSpecs

- Src/FluentAssertions/EventRaisingExtensions.cs
- Src/FluentAssertions/Events/EventAssertions.cs
- Src/FluentAssertions/Events/OccurredEvent.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- docs/_pages/releases.md
The call to `RaisePropertyChangeFor` on `EventAssertions<T>` now returns a filtered list of events related to the property given as parameter.  The `NotRaisePropertyChangeFor` function has been revised as well to match the behavior of `RaisePropertyChangeFor` especially when the parameter provided is `null`.
This fixes #393.
> Filter the list of events returned by RaisePropertyChangeFor

- Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
Since the issue is regarding `Formatter.ToString` I don't have a strong opinion on whether we need to add tests for `[Not]BeSameAs`.
Similarly I'm not sure what/if we should should put a notice in the release notes.
> Do not use `UsingLineBreaks` for `[Not]BeSameAs`

- Build/Build.cs
- Build/_build.csproj
- GitVersion.yml
~**Note**: This issue is possibly related to NUKE, because the `GitVersion` class have some fields which the actual response of `dotnet gitversion` doesn't have (because of breaking changes), so this should also be fixed in NUKE itself.~
~But until then, we do this generation manually...~
> Update to `GitVersion` 6.0.2 and fix PR version generation

- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Src/FluentAssertions/Execution/AssertionFailedException.cs
- Src/FluentAssertions/Execution/DefaultAssertionStrategy.cs
- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/Formatting/MaxLinesExceededException.cs
- Src/FluentAssertions/Primitives/StringContainsStrategy.cs
- Src/FluentAssertions/Primitives/StringEndStrategy.cs
- Src/FluentAssertions/Primitives/StringEqualityStrategy.cs
- Src/FluentAssertions/Primitives/StringStartStrategy.cs
- Src/FluentAssertions/Primitives/StringValidator.cs
- Src/FluentAssertions/Primitives/StringValidatorSupportingNull.cs
- Src/FluentAssertions/Primitives/StringWildcardMatchingStrategy.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Excluding.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.EndWith.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.StartWith.cs
This applies to places where removal is not an option. E.g. custom `Exceptions`.
Thus: exclude from coverage report
Using interpolation instead of concatenation should also increase CC
> Increase code coverage

- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Src/FluentAssertions/Equivalency/EquivalencyOptions.cs
- Src/FluentAssertions/Equivalency/NestedExclusionOptionBuilder.cs
- Src/FluentAssertions/Equivalency/Selection/ExcludeMemberByPathSelectionRule.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyOptions.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Excluding.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Including.cs
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
This refers to `Excluding()` / `.For().Exclude()` and `Including()`.
This closes #2479
> Allow anonymous object for selecting fields/properties at `Exclude` and `Include`

- Directory.Build.props
- Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
- Tests/FluentAssertions.Equivalency.Specs/CyclicReferencesSpecs.cs
- docs/_pages/releases.md
When the equivalency validation engine detects a cyclic reference, it excludes the node from further comparisons. But if the expectation is non-null and the subject is null (or vice versa), it should still trigger an assertion failure.
Fixes #2787
> The expectation node identified as a cyclic reference is still compared to the subject node using simple equality.

- docs/_pages/objectgraphs.md
It's still a function and needs to be called, otherwise it shows a syntax error.
(Removed the checklist as it is not relevant to this change.)
> Fix minor syntax error in objectgraphs.md

- Src/FluentAssertions/Equivalency/Selection/AllPropertiesSelectionRule.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Interfaces.cs
- docs/_pages/releases.md
You can exclude explicitly implemented properties from `BeEquivalentTo` via `ExcludingExplicitlyImplementedProperties` 
Closes #2811
> You can exclude explicitly implemented properties from BeEquivalentTo

- Src/FluentAssertions/FluentAssertions.csproj
#2673 bumped from 4.4.0 -> 6.0.1, but 6.0.0 should be enough. 
As a testing-only library I think we should strive for picking lower versions of dependencies to avoid that tests use a newer package than what is used in production due to included FA.
> Downgrade `ConfigurationManager` from 6.0.1 to 6.0.0

- Src/FluentAssertions/FluentAssertions.csproj
- Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
- docs/_pages/releases.md
Backport of #2673 and #2855 to v7.
See those two PRs for detailed analyses.
CC: @ViktorHofer @AArnott @jacekmlynek
Since you've previously been involved in package vs framework references.
Additional details:
In https://github.com/fluentassertions/fluentassertions/pull/2122#issuecomment-1419701160 I experimented with referencing 6.9.0 and 6.10.0 as nuget packages from a net47 project and then comparing detailed MSBuild logs.
It showed how 6.10.0 no longer had conflicts between package and framework assemblies.
Doing that same comparison between `main` and this PR, the MSBuild log is now down from 90 to 0 occurrences of
```
Encountered conflict between 'Reference:'System.Foo' and 'Platform:System.Foo'
````
and now skips the running the build task `AddFacadesToReferences`
Comparing the …
> Backport bump of `System.Configuration.ConfigurationManager` and `System.Threading.Tasks.Extensions`

- .github/workflows/codeql.yml
This pull request includes an update to the GitHub Actions workflow configuration for CodeQL analysis. The most important change is the addition of a step to set up the .NET SDKs.
Workflow configuration update:
* [`.github/workflows/codeql.yml`](diffhunk://#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27R27-R32): Added a step to set up .NET SDKs using `actions/setup-dotnet@v4` with version `8.0.x`.
> The CodeQL build needed the .NET 8.0 SDK

- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/NestedPropertiesSpecs.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Including.cs
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
- docs/_pages/releases.md
This pull request primarily focuses on renaming the `ExcludingNestedObjects` method to `WithoutRecursing` across various files to improve clarity and better describe its purpose. Additionally, it updates related documentation and test cases to reflect this change.
> Renamed ExcludingNestedObjects to WithoutRecursing to better describe its purpose

- .github/workflows/code_quality.yml
The new version is having a conflict with PolySharp 1.15, so we need to rollback.
See also https://github.com/fluentassertions/fluentassertions/pull/2884
> Rollback Qodana version to solve a conflict with PolySharp

- Tests/UWP.Specs/App.xaml.cs
- Tests/UWP.Specs/Directory.Build.props
- Tests/UWP.Specs/Package.appxmanifest
- Tests/UWP.Specs/UWP.Specs.csproj
Got UWP.Specs to build at all and `Determining_caller_identity_should_not_throw_for_native_programs` to run using MSTest 3.6.4
> Upgrade MSTest for UWP.Specs

- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
This partly reverts #2872.
This is to avoid pulling in dependencies that are newer than what end users might be using.
> Downgrade System.Collections.Immutable to 1.5.0

- .github/dependabot.yml
Follow up to #2890 as dependabot chose to ignore the explicit version range `[1.5.0]` in 
https://github.com/fluentassertions/fluentassertions/blob/de6adcf532651ab29b88aa3fafa33056518d98e7/Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj#L20
> Ignore updates to System.Collections.Immutable

- docs/_pages/releases.md
Updated the release notes such that 8.0.0 reflects the changes from 7.0.0 and not from when we branched out from 6.12.0
> Remove release notes from 8.0.0 that were backported to 6.12.x or 7.0.0

- Src/FluentAssertions/Configuration/GlobalFormattingOptions.cs
- Src/FluentAssertions/Formatting/FormattingOptions.cs
- Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
- Tests/FluentAssertions.Specs/Configuration/EquivalencyOptionsSpecs.cs
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
Remove the dependency on [Chill](https://www.nuget.org/packages/chill) in test projects by slightly rewriting the few unit tests using it.
Depends on #2901
> Remove chill

- Src/FluentAssertions/Configuration/GlobalEquivalencyOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
This is needed by packages like [FluentAssertions.DataSets](https://github.com/fluentassertions/fluentassertions.datasets) to be able to hook into the equivalency engine.
> GlobalEquivalencyOptions.CloneDefaults needs to be public

- Src/FluentAssertions/Common/ExpressionExtensions.cs
- Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
- docs/_pages/releases.md
> Fix a crash when using `WithStrictOrderingFor(x => x)` with `BeEquivalentTo`

- Src/FluentAssertions/Xml/XDocumentAssertions.cs
- Src/FluentAssertions/Xml/XElementAssertions.cs
- Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
Inspired by #2932 I had a look at other places where we use `First()`
Follow-up to #2690
> Avoid `InvalidOperationException` for `HaveElementWithValue`

- docs/_pages/releases.md
One actually wrong link and several wrong link appearences.
> Fix a few release note links

- .nuke/build.schema.json
- Build/Build.cs
- FluentAssertions.sln
- Src/FluentAssertions/Execution/LateBoundTestFramework.cs
- Src/FluentAssertions/Execution/TUnitFramework.cs
- Src/FluentAssertions/Execution/TestFrameworkProvider.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Tests/TestFrameworks/TUnit.Specs/FrameworkSpecs.cs
- Tests/TestFrameworks/TUnit.Specs/TUnit.Specs.csproj
- docs/_pages/about.md
- docs/_pages/introduction.md
- docs/_pages/releases.md
- docs/index.html
Backported [the work](https://github.com/fluentassertions/fluentassertions/pull/2758) of @thomhurst to add support for [TUnit](https://github.com/thomhurst/TUnit) to v7 of Fluent Assertions. 
#2935 
Needs to be merged after #2970 is merged.
> Backport TUnit to v7

- Src/FluentAssertions/AssertionEngine.cs
- Src/FluentAssertions/License.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/AssemblyInitializer.cs
- docs/_pages/introduction.md
- docs/_pages/releases.md
Resolves #2963 by providing a toggle to suppress the license warning that happens during each test run.
> Provide a toggle to suppress the soft warning about commercial use

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/DataRowAssertionExtensions.cs
- Src/FluentAssertions/DataSetAssertionExtensions.cs
- Src/FluentAssertions/DataTableAssertionExtensions.cs
- Src/FluentAssertions/EnumAssertionsExtensions.cs
- Src/FluentAssertions/Xml/XmlAssertionExtensions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
- docs/_pages/releases.md
(backported from commit ca87a816e50659cad9a3f1cb32756bce84527ed1)
> Backport "Add [NotNull] attribute on the Should() method for object assertions"

- .github/workflows/build.yml
Spotted this in https://github.com/fluentassertions/fluentassertions/actions/runs/13090382724/job/36526326802
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
From https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact)
> Backport updates to pipelines

- Src/FluentAssertions/AndWhichConstraint.cs
- Src/FluentAssertions/CallerIdentification/CallerStatementBuilder.cs
- Src/FluentAssertions/CallerIdentification/ParsingState.cs
- Src/FluentAssertions/CallerIdentification/SemicolonParsingStrategy.cs
- Src/FluentAssertions/CallerIdentification/ShouldCallParsingStrategy.cs
- Src/FluentAssertions/CallerIdentification/WhichParsingStrategy.cs
- Src/FluentAssertions/CallerIdentifier.cs
- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Common/StringExtensions.cs
- Src/FluentAssertions/Execution/AssertionChain.cs
- Src/FluentAssertions/Execution/SubjectIdentificationBuilder.cs
- Src/FluentAssertions/Types/MemberInfoAssertions.cs
- Src/FluentAssertions/Types/TypeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/AndWhichConstraintSpecs.cs
- Tests/FluentAssertions.Specs/Execution/CallerIdentificationSpecs.cs
- Tests/FluentAssertions.Specs/Types/MethodInfoAssertionSpecs.cs
- docs/_pages/releases.md
Given the following chained assertion
```csharp
collection.Should().ContainSingle().Which.Parameters.Should().ContainSingle().Which.Should().Be(3)
```
If the second `ContainSingle`, fails, this PR ensures that the subject is displayed as 
`collection[0].Parameters[0]`. 
This required several changes to make this possible:
* Establishes the term "subject identification" instead of "caller identifier"
* The existing `CallerIdentifier` has received a new method `DetermineCallerIdentities` that extracts all subjects from a chained assertion like the one above. 
* The `AssertionChain` delegates tracking which subject to use for its failures using a new `SubjectIdentificationBuilder` class. This one also takes into account any ambient `AssertionScope`s and modifications that `Which` does to the …
> Improves the subject identification for chained assertions and those that use Which

- Src/FluentAssertions/CallerIdentification/StatementParser.cs
- Src/FluentAssertions/CallerIdentifier.cs
This pull request includes a renaming and refactoring of a class in the `Src/FluentAssertions/CallerIdentification` directory to better reflect its functionality. The most important changes include renaming `CallerStatementBuilder` to `StatementParser` and updating the corresponding references.
> Renamed CallerStatementBuilder to StatementParser

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- docs/_pages/releases.md
> Fixed a regression in which CompleteWithinAsync treated a canceled task as an exception

- docs/_pages/introduction.md
This fixes an error in the [introduction page](https://fluentassertions.com/introduction#assertion-scopes). Presently it shows the assertion 
```C#
5.Should().Be(10);
```
and says the output would be 
```
Expected value to be 100, but found 95 (difference of -5).
```
The correct output would be 
```
Expected value to be 10, but found 5 (difference of -5).
```
> Fixed typo in introduction page

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/NonGenericAsyncFunctionAssertions.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
- docs/_pages/releases.md
The resolved merge conflict was due to 3205e04d919a5be03803ccb6834bbc3b8662d3ab moving `CompleteWithinAsync` from `AsyncFunctionAssertions` from `NonGenericAsyncFunctionAssertions`
> Upmerge from v7

- Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
- Src/FluentAssertions/Equivalency/Steps/AssertionRuleEquivalencyStep.cs
- Src/FluentAssertions/Equivalency/Steps/EnumEqualityStep.cs
- Src/FluentAssertions/Equivalency/Steps/StringEqualityEquivalencyStep.cs
- Src/FluentAssertions/Execution/StringExtensions.cs
- Src/FluentAssertions/Execution/WithoutFormattingWrapper.cs
- Src/FluentAssertions/Formatting/Formatter.cs
- Src/FluentAssertions/Formatting/PassthroughValueFormatter.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Tests/FluentAssertions.Specs/Execution/AssertionChainSpecs.MessageFormating.cs
- docs/_pages/releases.md
Especially in `BeEquivalentTo` calls we often pass the path from the root of the graph to the position in the graph that is being compared as a string into the `FailWith` calls. Since it's (apparently) possible that dictionary keys contain `{` and/or `}`, this caused a crash in the `MessageBuilder` while building the final failure message. We couldn't use normal `string.Format` placeholders like `{0}`, `{1}` and such because that caused the `Formatter` class to enclose strings with quotes. We solved that by introducing a special internal extension method `AsNonFormattable` that wraps the object to be formatted in such a way that the `Formatter` will not try to apply any formatting. 
This solves #2704
> Fix a formatting exception when {} is used as a dictionary key.

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Execution/AssertionChain.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Src/FluentAssertions/Specialized/FunctionAssertions.cs
- Src/FluentAssertions/Streams/BufferedStreamAssertions.cs
- Src/FluentAssertions/Xml/Equivalency/XmlReaderValidator.cs
Was lost in #2539 as the annotations were adding while developing that feature.
> Restore `StringSyntax` annotations

- Src/FluentAssertions/Execution/SubjectIdentificationBuilder.cs
- Tests/FluentAssertions.Specs/Execution/AssertionChainSpecs.Chaining.cs
- docs/_pages/releases.md
Fixes #3031
Regression from #3000 where previously `getCallerIdentifier() + callerPostfix` would return an empty string.
See https://github.com/fluentassertions/fluentassertions/pull/3000/files#diff-f1890f45abb0a4df9c59f857aff667980d90f2c1ece7ea0f12e5dd85590ae8ccL105
> Handle missing caller identifier

- .editorconfig
- Build/_build.v3.ncrunchproject
- FluentAssertions.sln.DotSettings
- FluentAssertions.v3.ncrunchsolution
- Src/FluentAssertions/Formatting/Anchor.cs
- Src/FluentAssertions/Formatting/BuildingLineState.cs
- Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
- Src/FluentAssertions/Formatting/EnumerableValueFormatter.cs
- Src/FluentAssertions/Formatting/FlushedLineState.cs
- Src/FluentAssertions/Formatting/FormattedObjectGraph.cs
- Src/FluentAssertions/Formatting/ILineState.cs
- Src/FluentAssertions/Formatting/Line.cs
- Src/FluentAssertions/Formatting/LineCollection.cs
- Src/FluentAssertions/Formatting/StringValueFormatter.cs
- Tests/.editorconfig
- Tests/Approval.Tests/Approval.Tests.v3.ncrunchproject
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/Benchmarks.net472.v3.ncrunchproject
- Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/ReferenceTypeAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/Xml/XmlNodeFormatterSpecs.cs
- docs/_pages/releases.md
While trying to fix #2696, I decided to redesign the implementation of the `FormattedObjectGraph` to make it easier to understand. 
Fixes #2696
> Reworked formatting and support multi-dimensional arrays.

- Src/FluentAssertions/Formatting/Line.cs
- Src/FluentAssertions/Primitives/IStringComparisonStrategy.cs
- Src/FluentAssertions/Primitives/StringContainsStrategy.cs
- Src/FluentAssertions/Primitives/StringEndStrategy.cs
- Src/FluentAssertions/Primitives/StringEqualityStrategy.cs
- Src/FluentAssertions/Primitives/StringStartStrategy.cs
- Src/FluentAssertions/Primitives/StringValidator.cs
- Src/FluentAssertions/Primitives/StringValidatorSupportingNull.cs
- Src/FluentAssertions/Primitives/StringWildcardMatchingStrategy.cs
- Src/FluentAssertions/Specialized/ExceptionAssertions.cs
- Tests/FluentAssertions.Specs/Exceptions/OuterExceptionSpecs.cs
- Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
In a test like `When_one_of_the_types_does_not_match_the_generic_type_it_should_throw_with_a_clear_explanation`, a multi-line exception message like this
```
Expected exception message to match the equivalent of "Expected type to be "System.Int33" because they are of different type, but found "[System.Int32, System.String, System.Int32]".", but "Expected type to be "System.Int32" because they are of different type, but found "[System.Int32, System.String, System.Int32]"." does not.
```
after this PR, they will be rendered as 
```
Expected exception message to match the equivalent of
"Expected type to be "System.Int33" because they are of different type, but found "[System.Int32, System.String, System.Int32]".",
but
"Expected type to be "System.Int32" because they are of different type, …
```
> Improve rendering of exception messages when using WithMessage 

- .github/ISSUE_TEMPLATE/01_bug_report.yml
> Fix links to test suites in bug report template

- Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
- Src/FluentAssertions/Formatting/LineCollection.cs
- Src/FluentAssertions/Formatting/XElementValueFormatter.cs
- Src/FluentAssertions/Primitives/StringWildcardMatchingStrategy.cs
- Src/FluentAssertions/Streams/BufferedStreamAssertions.cs
- Tests/FluentAssertions.Specs/Xml/XmlNodeFormatterSpecs.cs
Since https://github.com/fluentassertions/fluentassertions/actions/runs/14577365118/job/40886331551 we have had a red Qodana pipeline.
The timestamps matches that Github [announced](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts) a shutdown of an old(er) cache service.
That improved with #3044.
Now it's just 7 warnings, which this PR takes care of.
The removal of `StringSplitOptions.None` is a leftover from 0a649cb006744405050f0a72ad48442831b3c8cd where I introduced and started using `string.Split(string separator, StringSplitOptions options = StringSplitOptions.None)`.
> Fix qodana warnings

- Src/FluentAssertions/Equivalency/Selection/ExcludeMembersByNameSelectionRule.cs
- Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyOptions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Excluding.cs
- docs/_pages/objectgraphs.md
- docs/_pages/releases.md
Adds a new convenience option
```csharp
subject.Should().BeEquivalentTo(expectation, options => options
.ExcludingMembersNamed("LastName", "Age"));
```
Closes #3052
> Allow excluding properties by name anywhere in the graph

- Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
- Src/FluentAssertions/Specialized/DelegateAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Exceptions/ThrowAssertionsSpecs.cs
- Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
- docs/_pages/releases.md
This implements issue #3056
The contributor waives any moral rights in the contribution to the extent permitted by law and agrees not to assert any claim of authorship or control over the contribution. The contributor represents that they are the sole author of the contribution and that it is provided free of any third-party claims.
The contributor understands and agrees that the maintainers may, at their sole discretion, use, license, or redistribute the …
> Added Should().Throw(), ThrowAsync() and ThrowWithinAsync() flavors that don’t require a specific exception type

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- Build/Build.cs
- Build/_build.csproj
- Directory.Build.props
- README.md
- Src/FluentAssertions/Common/MethodInfoExtensions.cs
- Src/FluentAssertions/FluentAssertions.csproj
- Tests/.editorconfig
- Tests/Approval.Tests/Approval.Tests.csproj
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
- Tests/Benchmarks/Benchmarks.csproj
- Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Basic.cs
- Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
- Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.MatchRegex.cs
- Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
- Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
- Tests/TestFrameworks/TUnit.Specs/TUnit.Specs.csproj
- Tests/TestFrameworks/XUnit3.Specs/XUnit3.Specs.csproj
- Tests/TestFrameworks/XUnit3Core.Specs/XUnit3Core.Specs.csproj
- Tests/UWP.Specs/Directory.Build.props
- Tests/UWP.Specs/UWP.Specs.csproj
- Tests/VB.Specs/VB.Specs.vbproj
- global.json
This PR updates the minimum required SDK to .NET 9.
While C# 13.0 doesn't seem very interesting for _us_, .NET 9 SDK still brings a new set of analyzers.
The NET 9.0.200 SDK supports the new slnx format, but unfortunately NUKE cannot parse it.
See https://github.com/nuke-build/nuke/issues/1520
The contributor waives any moral rights in the contribution to the extent permitted by law and agrees not to assert any claim of authorship or control over the …
> Use .NET 9 SDK

- Directory.Build.props
By suggestion from https://github.com/NuGet/Home/issues/7921#issuecomment-478152479
> By default, Microsoft.NET.NuGetOfflineCache.targets (imported by Microsoft.NET.Sdk.BeforeCommon.targets) will add an extra search path for nuget packages that is not controlled by the user nuget.config. It will add the `sdk/NuGetFallbackFolder` from your dotnet installation to the set of nuget search locations. This could potentially poison your nuget cache between repos, even if you've configured per-repo nuget caches.
https://github.com/dotnet/reproducible-builds/blob/main/docs/Reproducible-MSBuild/Techniques/DisableImplicitNuGetFallbackFolder.md
By submitting this contribution, the contributor hereby irrevocably grants to the project owners and maintainers a perpetual, worldwide, royalty-free, …
> Set `DisableImplicitNuGetFallbackFolder`

- Src/FluentAssertions/Specialized/JsonNodeAssertions.cs
SA1612 suggested that we include documentation for the `config`.
Should we fix up the other suggestions and raise the severity of SA1612 to error?
The contributor waives any moral rights in the contribution to the extent permitted by law and agrees not to assert any claim of authorship or control over the contribution. The contributor represents that they are the sole author of the contribution and that it is provided free of any third-party claims.
The …
> Add docs for `config` parameter

- Src/FluentAssertions/AssertionExtensions.cs
- Src/FluentAssertions/JsonAssertionExtensions.cs
- Src/FluentAssertions/Specialized/JsonNodeAssertions.cs
- Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
- Tests/FluentAssertions.Equivalency.Specs/JsonNodeSpecs.cs
- docs/_pages/json.md
- docs/_pages/releases.md
The first commit demonstrates the issue; the second commit proposes a solution.
The third commit makes the `JsonNodeAssertions` generic, which propagates the type safety of the `Subject`.
Fixes #3103
The contributor waives any moral rights in the contribution to the extent permitted by law and agrees not to assert any claim of authorship or control over the contribution. The contributor represents that they are the sole author of the contribution and that …
> Fixed ambiguity when using Should on a JsonNode derived class
