FluentAssertions.Core/Collections/CollectionAssertions.cs, FluentAssertions.Shared.Specs/CollectionAssertionSpecs.cs, FluentAssertions.Shared.Specs/GenericCollectionAssertionOfStringSpecs.cs
=> collection.Should().BeEmpty() now properly reports the collection items it did find.

FluentAssertions.Net40.Specs/Net40.Specs.csproj, FluentAssertions.Net45.Specs/Net45.Specs.csproj, FluentAssertions.Shared.Specs/EventAssertionSpecs.cs, Shared/Execution/AssertionFailedException.cs, Shared/Execution/FallbackTestFramework.cs, Shared/Shared.projitems
=> Made the AssertFailedException serializable

FluentAssertions.Core/Formatting/TimeSpanValueFormatter.cs, FluentAssertions.Shared.Specs/TimeSpanFormatterSpecs.cs
=> Better support for rendering a TimeSpan.MinValue/MaxValue. 

FluentAssertions.Core/Equivalency/ByteArrayOrderingRule.cs, FluentAssertions.Core/Equivalency/EquivalencyAssertionOptionsBase.cs, FluentAssertions.Core/Equivalency/ExcludeMemberByPathSelectionRule.cs, FluentAssertions.Core/Equivalency/MatchAllOrderingRule.cs, FluentAssertions.Core/Equivalency/PathBasedOrderingRule.cs, FluentAssertions.Core/Equivalency/PredicateBasedOrderingRule.cs
=> Improved logging of the equivalency configuration

FluentAssertions.Core/Common/ExpressionExtensions.cs, FluentAssertions.Core/Core.csproj, FluentAssertions.Core/Equivalency/EquivalencyAssertionOptions.cs, FluentAssertions.Core/Equivalency/Selection/ExcludeMemberByPathSelectionRule.cs, FluentAssertions.Core/Equivalency/Selection/IncludeMemberByPathSelectionRule.cs, FluentAssertions.Core/Equivalency/Selection/IncludeMemberByPredicateSelectionRule.cs, FluentAssertions.Core/Equivalency/Selection/SelectMemberByPathSelectionRule.cs, FluentAssertions.Net45.Specs/Net45.Specs.csproj.DotSettings, FluentAssertions.Shared.Specs/CollectionEquivalencySpecs.cs
=> Enabled the use of Including() with a nested property expression. 

Src/Core/Types/MemberInfoAssertions.cs, Tests/FluentAssertions.Shared.Specs/MethodInfoAssertionSpecs.cs
Used it to test my web api methods are not decorated with Authorize attribute
=> NotBeDecoratedWith attribute assertion added

FluentAssertions.sln, Src/FluentAssertions.Json.Shared/JsonAssertionExtensions.cs, Src/FluentAssertions.Json.Shared/Shared.Json.projitems, Src/JetBrainsAnnotations.cs, Src/Shared/AssertionExtensions.cs, Src/Shared/Shared.projitems
=> Pure and MustUseReturnValue ReSharper Annotations

Src/Core/Common/ExpressionExtensions.cs, Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
Currently, `foo.ShouldBeEquivalentTo(bar, opts => opts.Excluding(x => x.Baz[0].Quux)` will throw an `ArgumentException` if `Baz` is not an array, but is rather a list, dictionary etc.. This adds support for including/excluding using such non-array indexer expressions.
=> Support Excluding/Including with expressions using indexers on types other than arrays

.github/PULL_REQUEST_TEMPLATE.md
Changed the remark about editing the wiki to be about updating the documentation markdown file.
=> Update PULL_REQUEST_TEMPLATE.md to reflect the documentation move

README.md
This pull request only affects README.md
=> Updated the URL for the documentation in README.md

docs/documentation.md
=> Documentation: Adding a missing day value to the month March

docs/404.html
This 404.html comes from the minima project (https://github.com/jekyll/minima).
=> Add 404.html

Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs, Src/FluentAssertions/Types/TypeAssertions.cs
=> Add missing dots to end sentences

Src/Core/Equivalency/EnumerableEquivalencyValidator.cs, Src/Core/Execution/AssertionScope.cs, Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs
=> Fixes a crash when a guid needed formatting

Tests/Shared.Specs/TypeSelectorSpecs.cs
Now everybody that `lol` is my name for temporary variables.
=> Forgot to remove temporary variable from commit

docs/AssertionScope.md, docs/_config.yml, docs/about.md, docs/documentation.md, docs/examples.md, docs/index.md
Tries to improve the general flow of the website
- Wording changes to affect tone, perspective, or length
- Generally tries to make the website more intuitive for users who do not already know what FluentAssertions is
=> [Try to] improve the general flow of the website

Src/FluentAssertions/Formatting/Formatter.cs, Src/FluentAssertions/Formatting/TaskFormatter.cs, Tests/Shared.Specs/FormatterSpecs.cs
=> Added proper formatting of Task and Task<T>

Src/FluentAssertions/ObjectAssertionsExtensions.cs, Tests/Shared.Specs/ObjectAssertionSpecs.cs
=> BeDataContractSerializable didn't allow customizing the comparison

docs/_data/mstest-migration/assert.yml, docs/_data/tips/collections.yml, docs/_data/tips/comparable.yml, docs/_data/tips/datetimes.yml, docs/_data/tips/dictionaries.yml, docs/_data/tips/strings.yml, docs/_data/tips/types.yml, docs/documentation.md, docs/tips.md, docs/v3/documentation.md
More work on #592 .
This one brings:
* Archived v3/v4 docs and links to them from v5 docs.
* More tips on improving assertions
* Added 14 assertions to `documentation.md`
=> More documentation

Src/FluentAssertions/Common/DateTimeExtensions.cs, Src/FluentAssertions/Formatting/ValueFormatterAttribute.cs, Src/FluentAssertions/ObjectAssertionsExtensions.cs, Src/FluentAssertions/Primitives/StringAssertions.cs, Src/FluentAssertions/Specialized/ExceptionAssertions.cs, Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs, Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs, Src/FluentAssertions/Types/TypeSelectorAssertions.cs
This PR replaces hardcoded `\r\n` with `Environment.Newline`
=> Use Environment.Newline

Src/FluentAssertions/Execution/AssertionScope.cs
Closes #551.
Does not change the behaviour.
Only documentation for "because" formatting is improved.
=> Explicitly mention that "because" formatting can throw FormatException

Src/FluentAssertions.nuspec, Src/FluentAssertions/FluentAssertions.csproj, Src/FluentAssertions/FluentAssertions.net451.v3.ncrunchproject, Src/FluentAssertions/FluentAssertions.netstandard1.4.v3.ncrunchproject, Src/FluentAssertions/FluentAssertions.netstandard1.6.v3.ncrunchproject, Tests/Net45.Specs/Net45.Specs.csproj
=> Downgraded the .NET version from 4.5.1 to 4.5

Src/FluentAssertions/Equivalency/GenericDictionaryEquivalencyStep.cs, Tests/Shared.Specs/CollectionEquivalencySpecs.cs, Tests/Shared.Specs/DictionaryEquivalencySpecs.cs
=> Include the missing and superfluous items when comparing dictionaries. 

Src/FluentAssertions/Common/TypeExtensions.cs, Src/FluentAssertions/Types/TypeAssertions.cs, Src/FluentAssertions/Types/TypeSelectorAssertions.cs, Tests/Shared.Specs/TypeAssertionSpecs.cs, docs/documentation.md
=> Added BeDecoratedWithOrInherit and NotBeDecoratedWithOrInherit for type assertions

Src/FluentAssertions/Equivalency/EquivalencyValidationContext.cs, Src/FluentAssertions/Equivalency/EquivalencyValidationContextExtentions.cs, Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs, Tests/Net45.Specs/Net45.Specs.csproj, Tests/Shared.Specs/DictionaryEquivalencySpecs.cs
=> Nested dictionary items didn't use the right expectation type

Src/FluentAssertions/Common/TypeExtensions.cs, Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs, Tests/Shared.Specs/DictionaryEquivalencySpecs.cs
=> Ensures that a KeyValuePair doesn't stop deep comparisons

Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs, Tests/Shared.Specs/ComparableSpecs.cs
This PR adds `BeEquivalentTo` to `ComparableAssertions`
This fixes #755
=> Add BeEquivalentTo to ComparableAssertions

Src/FluentAssertions.nuspec, Src/FluentAssertions/FluentAssertions.csproj
=> Downgraded to .NET Standard 1.3

docs/documentation.md
Adding documentation for a hidden gem of a feature (`AssertionScope`). Been wanting this for months, and finally thought I'd give it a go to implement, but was pleasantly surprised to find it in the Unit Tests and exposed already!
=> Adding Assertion Scope Documentation

Src/FluentAssertions/NumericAssertionsExtensions.cs, Tests/Shared.Specs/NullableNumericAssertionSpecs.cs, Tests/Shared.Specs/NumericAssertionSpecs.cs
=> Improved the failure messages for `(Not)BeApproximately`

Src/FluentAssertions.nuspec, Src/FluentAssertions/FluentAssertions.csproj
=> Depends on System.ValueTuple 4.4.

docs/_data/mstest-migration/assert.yml, docs/_data/mstest-migration/collectionAssert.yml, docs/_data/mstest-migration/exceptions.yml, docs/_data/mstest-migration/stringAssert.yml, docs/_data/tips/collections.yml, docs/_data/tips/comparable.yml, docs/_data/tips/dictionaries.yml, docs/_data/tips/exceptions.yml, docs/_data/tips/nullables.yml, docs/_data/tips/strings.yml, docs/_data/tips/types.yml, docs/assets/css/main.scss
The tips and examples somehow got lost in #813 .
Now they're back.
=> Re-add lost examples

Tests/Shared.Specs/EventAssertionSpecs.cs
Proposal to remove the two tests that keep failing on AppVeyor.
=> Removed two GC tests that are unstable on AppVeyor

docs/_data/mstest-migration/exceptions.yml, docs/_data/tips/exceptions.yml
=> Exceptions tips

Src/FluentAssertions/FluentAssertions.csproj
Just prettifying the csproj by using self-closing tags.
=> Use self-closing tags

docs/_pages/examples.md
=> Update examples.md to fix minor typo

Src/FluentAssertions/Execution/MessageBuilder.cs
Relevant reason: prettier
Irrelevant reason: 5 ns faster on my machine.
=> Replace Any with Contains

Src/FluentAssertions/Events/EventMonitor.cs, Tests/Shared.Specs/EventAssertionSpecs.cs
Ran into #821 when upgrading to FA 5.
Inspiration from: https://stackoverflow.com/a/26766221/11808
=> Trying to fix #821 by traversing interfaces

Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs, Tests/Shared.Specs/ExecutionTimeAssertionsSpecs.cs, Tests/Shared.Specs/FluentActionsSpecs.cs, Tests/Shared.Specs/MethodInfoAssertionSpecs.cs
This includes some of the changes from #1020.
Hopefully this doesn't cause xunit+AppVeyor to hang.
=> Async cleanup

build.cake, build.ps1, dotnet-install.ps1
=> Auto-install .NET Core version if it is missing

Src/FluentAssertions/FluentAssertions.csproj
=> Set language version of FluentAssertions.csproj to C# 7.1

Src/FluentAssertions/Specialized/ActionAssertions.cs, Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs, Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs, Tests/Shared.Specs/ExceptionAssertionSpecs.cs
Resolves issue #1053 
This PR also contains the changes made in PR #1050
=> Refactoring of AsyncFunctionAssertions and ActionAssertions

docs/_pages/examples.md
=> Fix: ( -> ;

Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs, Src/FluentAssertions/Specialized/NonGenericAsyncFunctionAssertions.cs, Tests/Shared.Specs/TaskOfTAssertionSpecs.cs
I missed some comments mentioned in #1048 and processed the suggestions.
=> Rework on async function assertions

docs/_data/navigation.yml
=> Fix a couple of broken links

docs/.htaccess, docs/_data/navigation.yml, docs/_pages/extensibility.md, docs/_pages/introduction.md, docs/index.html
=> Fixed a couple more broken links and added backwards compatible URLs

Tests/Shared.Specs/AssertionScopeSpecs.cs
=> Test that a null strategy throws

Src/FluentAssertions/Execution/AssertionScope.cs, Tests/Shared.Specs/AssertionScopeSpecs.cs
When using the new public constructor of `AssertionScope` introduced in #1094 the `AssertionScope` was constructed differently than when using the parameterless constructor.
The public constructor taking an `IAssertionStrategy` should work exactly like the parameterless constructor, except that it uses the injected `assertionStrategy` instead of `CollectingAssertionStrategy`.
This fixes #1118
=> Fix constructors of AssertionScope

Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs, Src/FluentAssertions/Specialized/DelegateAssertions.cs, Src/FluentAssertions/Specialized/FunctionAssertions.cs, Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs, Src/FluentAssertions/Specialized/NonGenericAsyncFunctionAssertions.cs
Storing the *same* `clock` both in base and super class...
=> Expose clock from base class instead of duplication

Src/FluentAssertions/Execution/MSTestFrameworkRT.cs, Src/FluentAssertions/Execution/NUnitPclTestFramework.cs
Remove files that are no longer used.
This fixes #1108
=> Remove leftovers from 4.x

Tests/Shared.Specs/AsyncFunctionExceptionAssertionSpecs.cs
=> Update NotThrowAfter tests to use FakeClock (GH-1116) 

AcceptApiChanges.sh
Follow up to #1222 for those of us that work in linux shells.
=> Add API acceptance script for linux shells

Src/FluentAssertions/Collections/CollectionAssertions.cs, Src/FluentAssertions/Common/TypeExtensions.cs, Src/FluentAssertions/Equivalency/EquivalencyAssertionOptionsExtensions.cs, Src/FluentAssertions/Types/TypeAssertions.cs, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net45.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.3.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard1.6.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt, Tests/Shared.Specs/Types/TypeAssertionSpecs.cs, docs/_pages/releases.md
Remove members marked as `Obsolete` for removal in 6.0.
=> Remove obsoleted members

Tests/Shared.Specs/Collections/CollectionAssertionSpecs.cs, Tests/Shared.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs, Tests/Shared.Specs/Collections/GenericCollectionAssertionsSpecs.cs, Tests/Shared.Specs/Collections/GenericDictionaryAssertionSpecs.cs, Tests/Shared.Specs/Equivalency/BasicEquivalencySpecs.cs, Tests/Shared.Specs/Equivalency/CollectionEquivalencySpecs.cs, Tests/Shared.Specs/Equivalency/DictionaryEquivalencySpecs.cs, Tests/Shared.Specs/ExtensibilitySpecs.cs, Tests/Shared.Specs/Extensions/ObjectExtensionsSpecs.cs, Tests/Shared.Specs/Numeric/ComparableSpecs.cs, Tests/Shared.Specs/Primitives/DateTimeAssertionSpecs.cs, Tests/Shared.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs, Tests/Shared.Specs/Primitives/EnumAssertionSpecs.cs, Tests/Shared.Specs/Primitives/GuidAssertionSpecs.cs, Tests/Shared.Specs/Primitives/NullableBooleanAssertionSpecs.cs, Tests/Shared.Specs/Primitives/NullableGuidAssertionSpecs.cs, Tests/Shared.Specs/Primitives/ObjectAssertionSpecs.cs, Tests/Shared.Specs/Primitives/ReferenceTypeAssertionsSpecs.cs, Tests/Shared.Specs/Primitives/SimpleTimeSpanAssertionSpecs.cs, Tests/Shared.Specs/Primitives/StringAssertionSpecs.cs, Tests/Shared.Specs/Specialized/AssemblyAssertionSpecs.cs, Tests/Shared.Specs/TimeSpanExtensions.cs, Tests/Shared.Specs/Types/MethodInfoAssertionSpecs.cs, Tests/Shared.Specs/Types/PropertyInfoAssertionSpecs.cs, Tests/Shared.Specs/Xml/XAttributeAssertionSpecs.cs, Tests/Shared.Specs/Xml/XDocumentAssertionSpecs.cs, Tests/Shared.Specs/Xml/XElementAssertionSpecs.cs
=> Cleansed the specs from all the #if statements

Src/FluentAssertions/Execution/MessageBuilder.cs, Src/FluentAssertions/Specialized/ExceptionAssertions.cs, Tests/Shared.Specs/Primitives/StringAssertionSpecs.cs, docs/_pages/releases.md
=> Fix error description containing "}}}}"

Src/FluentAssertions/FluentAssertions.csproj
=> Added missing dependency on System.Xml

Src/FluentAssertions/Xml/Equivalency/Node.cs, Src/FluentAssertions/Xml/Equivalency/XmlReaderValidator.cs, Tests/Shared.Specs/Xml/XDocumentAssertionSpecs.cs, docs/_pages/releases.md
Merge current master into develop after #1273
=> fix XPath index calculation when child node names are repeated in repated parent nodes

global.json
=> Enable the projects to be loaded with .NET SDK 3.1.200 (and further)

Src/FluentAssertions/Equivalency/IAssertionContext.cs, Src/FluentAssertions/Equivalency/IEquivalencyValidationContext.cs
Not all `because`s are parameters :)
=> Fix xml references  to `Because` member

Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt
=> Removed unused code.

Src/FluentAssertions/Equivalency/AssertionRuleEquivalencyStep.cs
No need to re-compile the `Expression` into a `Func` each time `AppliesTo` is
called.
Made a simple benchmark to verify the improvement.
```c#
list.Should().BeEquivalentTo(list2, opt => opt
.WithStrictOrdering()
.Using<string>(ctx => ctx.Should().NotBeNull())
.When(ctx => ctx.SelectedMemberPath == "Id")
);
```
Before:
```
|         Method |     N |         Mean |      Error |     StdDev |      Gen 0 |      Gen 1 | Gen 2 |    Allocated |
|--------------- |------ |-------------:|-----------:|-----------:|-----------:|-----------:|------:|-------------:|
| BeEquivalentTo |    10 |     2.685 ms |  0.0392 ms |  0.0367 ms |    74.2188 |    35.1563 |     - |    236.15 KB |
| BeEquivalentTo |   100 |    25.310 ms |  0.4918 ms |  0.4360 ms |   687.5000 |   343.7500 |     - |   2177.74 KB |
| …
```
=> Cache `When` predicate

Build/_build.csproj, Tests/Approval.Tests/Approval.Tests.csproj, Tests/Benchmarks/Benchmarks.csproj, Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj, Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj, Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj, Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj, Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
The simplified `_build.csproj` was kindly provided by @matkoch
=> Update test and build packages

Src/FluentAssertions/Types/TypeSelectorAssertions.cs, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt, Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs, docs/_pages/releases.md, docs/_pages/typesandmethods.md
closes #1180 
fixes #1175 
Credits to @kimsey0 for all the work.
=> Add [Not]Be{In,Under}Namespace assertions to TypeSelectorAssertions

Src/FluentAssertions/Events/EventAssertions.cs, Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs, docs/_pages/releases.md
=> Improved the message when the PropertyChanged event was raised for the wrong property

Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
Let's see if it keeps running without problems.
=> Bump xUnit.StaFact to the latest version

Src/FluentAssertions/Common/TypeExtensions.cs
=> Remove unused overloads of GetCustomAttributes

Src/FluentAssertions/Common/ExpressionExtensions.cs
Postpone construction of exception message until an exception is thrown.
=> Lazy construction of unsupported expression message

Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs, Src/FluentAssertions/Collections/StringCollectionAssertions.cs, Src/FluentAssertions/Equivalency/AutoConversionStep.cs, Src/FluentAssertions/Equivalency/Matching/TryMatchByNameRule.cs, Src/FluentAssertions/Equivalency/Node.cs, Src/FluentAssertions/Equivalency/ValueTypeEquivalencyStep.cs, Src/FluentAssertions/Formatting/DefaultValueFormatter.cs, Src/FluentAssertions/Primitives/StringAssertions.cs, Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs, Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs, Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs, Tests/FluentAssertions.Specs/Exceptions/ExceptionAssertionSpecs.cs, Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs, Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs, Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs, Tests/FluentAssertions.Specs/TypeEnumerableExtensionsSpecs.cs, Tests/FluentAssertions.Specs/Types/MethodInfoAssertionSpecs.cs
Fixing some IDE0055 warnings from Visual Studio
=> Fix some VS warnings

Build/Build.cs, Build/_build.csproj, Src/FluentAssertions/Collections/SubsequentOrderingAssertions.cs, Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs, Src/FluentAssertions/Execution/LateBoundTestFramework.cs, Src/FluentAssertions/Execution/NSpecFramework.cs, Src/FluentAssertions/Execution/XUnit2TestFramework.cs, Src/FluentAssertions/FluentAssertions.csproj, Src/FluentAssertions/Formatting/DoubleValueFormatter.cs, Src/FluentAssertions/Primitives/StringAssertions.cs, Src/FluentAssertions/SystemExtensions.cs, Tests/Approval.Tests/Approval.Tests.csproj, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt, Tests/FluentAssertions.Specs/.editorconfig, Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionsSpecs.cs, Tests/FluentAssertions.Specs/CultureAwareTesting/CulturedFactAttribute.cs, Tests/FluentAssertions.Specs/CultureAwareTesting/CulturedTheoryAttribute.cs, Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs, Tests/FluentAssertions.Specs/Equivalency/ExtensibilityRelatedEquivalencySpecs.cs, Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs, Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj, Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs, Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs, Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs, Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj, Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
Updated nugets and fixed/suppressed new warnings.
=> Test packages

docs/_pages/eventmonitoring.md
Took me a couple of minutes to figure out the correct call, so I thought - might as well fix it in doc.
No code changed, so checklist does not apply.
=> Minor issue in eventmonitoring.md fixed

Src/FluentAssertions/Equivalency/DictionaryEquivalencyStep.cs, Src/FluentAssertions/Equivalency/GenericDictionaryEquivalencyStep.cs, Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs, docs/_pages/releases.md
=> Some dictionary failures did not honor the user-provided reason

Src/FluentAssertions/Specialized/AssemblyAssertions.cs, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.approved.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.approved.txt, docs/_pages/releases.md
Fixed `becauseArgs` being the wrong type.
=> Changed `becauseArgs` from `string[]` to `object[]`

Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs, Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.cs, Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.cs, Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionsSpecs.cs, Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs, Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs, Tests/FluentAssertions.Specs/Equivalency/CollectionEquivalencySpecs.cs, Tests/FluentAssertions.Specs/Equivalency/DictionaryEquivalencySpecs.cs, Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs, Tests/FluentAssertions.Specs/Exceptions/ExceptionAssertionSpecs.cs, Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs, Tests/FluentAssertions.Specs/Extensions/FluentDateTimeSpecs.cs, Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs, Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs, Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs, Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs, Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.cs, Tests/FluentAssertions.Specs/Specialized/DelegateAssertionSpecs.cs, Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs, Tests/FluentAssertions.Specs/Types/MethodInfoAssertionSpecs.cs, Tests/FluentAssertions.Specs/Types/MethodInfoSelectorAssertionSpecs.cs, Tests/FluentAssertions.Specs/Types/TypeAssertionSpecs.cs
Let's use this new extension method ourselves.
=> Use WithParameterName in our own tests

Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
I simply forgot to commit the last test I wrote as part of #1475
=> Add culture test of ThrowIfAny

docs/_pages/extensibility.md
Fix C# syntax error in a snippet inside extensibility.md
=> Fix snippet inside extensibility.md

Src/FluentAssertions/FluentAssertions.csproj, docs/_pages/about.md, docs/_pages/releases.md
Accidentally squashed the previous upmerge from `master`
=> Upmerge from master (again)

.editorconfig
As mentioned in #1555, lines should not exceed 130 characters.
=> Add max line length in editor config

Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
With this PR I want to run build and tests in the environment where unit tests were failing from time to time.
I'll push several updates to get multiple runs.
Finally you may decide whether I should force push to remove all trigger commits or you squash the complete PR to keep the build results visible.
=> Update to Xunit.StaFact 1.1.5-alpha to solve failing unit tests due to unwanted concurrency

docs/_pages/exceptions.md
Use the new `WithParameterName()` method in the documentation.
=> Use WithParameterName in the documentation

docs/_config.yml, docs/assets/js/lunr/lunr-store.js
Add pages to search index store.
This enables the search functionality, instead of always an empty results page.
=> Make search work on homepage

Src/FluentAssertions/AssertionExtensions.cs, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt, Tests/FluentAssertions.Specs/Specialized/ExecutionTimeAssertionsSpecs.cs
=> Fake timing for unstable test of ExecutionTimeOf

Src/FluentAssertions/Common/Guard.cs, Src/FluentAssertions/Primitives/EnumAssertions.cs, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt, Tests/FluentAssertions.Specs/Primitives/EnumAssertionSpecs.cs, docs/_pages/releases.md
=> Added BeOneOf and Match to enum assertions

.github/workflows/pr.yml, Build/Build.cs, Build/_build.csproj
Add GitHub as a build environment.
I'm not sure of additional (and maybe conditional steps) that the AppVeyor environment contains.
Example: https://github.com/eNeRGy164/fluentassertions/actions/runs/1119600839
**Todo for the maintainers**:
=> Add GitHub build action

docs/_pages/releases.md
=> Added a missing breaking change to the release notes

Src/FluentAssertions/Equivalency/IMemberInfo.cs, docs/_pages/objectgraphs.md
=> Updated the docs for using ISubjectInfo

docs/_pages/collections.md
change affects only the documentation
=> updated collection.Should().BeEquivalentTo to not use params

docs/_pages/upgradingtov6.md
=> Added more upgrade info to fix the breaking changes in v6

FluentAssertions.sln.DotSettings, Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
Replaced the regions within the numeric tests with nested classes and moved the specific tests for floats, doubles and decimals into the correct nested class. 
DON'T SQUASH
=> Reordered the numeric tests and replaced regions with nested classes

Tests/FluentAssertions.Specs/.editorconfig, Tests/FluentAssertions.Specs/Numeric/ComparableSpecs.cs, Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
Also had to reorder some of the tests to group them by API and disable CA1052 for test projects.
=> Replaced regions in numeric specs with nested classes

docs/_pages/upgradingtov6.md
=> Fix Some Typos in UpgradingToV6.md

Tests/FluentAssertions.Specs/Exceptions/InnerExceptionSpecs.cs, Tests/FluentAssertions.Specs/Execution/AssertionScope.MessageFormatingSpecs.cs, Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
Some cleanups in Specs. 
A little dogfooding and getting rid of a distraction method. 
I haven't heard it used before, so I'll pretend I coined that term for "helper methods" that are unhelpful and simply a distraction.
=> Cleanups in Specs

Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.cs, Tests/FluentAssertions.Specs/Primitives/DateTimeOffsetAssertionSpecs.cs, Tests/FluentAssertions.Specs/Primitives/EnumAssertionSpecs.cs
=> Structure assertions with nested classes instead of regions (Part 1)

docs/_pages/collections.md
This if very useful and not at all obvious from the docs that this is possible.
=> Add ContainSingle.Where to collection examples

docs/_pages/enums.md
=> Add Enum.BeOneOf to the docs

Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
As discussed in person with @dennisdoomen the summary was not strictly correct.
=> Update summary of EquivalencyValidator.cs

docs/index.html
db3653daa685cd0148f392a05ff751dc130ee7ed
=> update catch phrase url

nuget.config
=> Fix nuget config to be able to restore/build the project when having custom HTTP nuget sources

Src/FluentAssertions/FluentAssertions.csproj
=> Fix copyright year

.github/workflows/build.yml
=> Check if `lcov.info` does exist

docs/_pages/data.md
═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
SpellCheck         Succeeded       0:24
───────────────────────────────────────
Total                              0:24
═══════════════════════════════════════
​
Build succeeded on 2023-01-21 12:00:39. ＼（＾ᴗ＾）／
=> Update data.md to fix typo

Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
**NOTE** Review while hiding whitespace changes.
=> Regrouping and formatting of the selection rule specs

Src/FluentAssertions/Equivalency/Steps/AutoConversionStep.cs, Tests/FluentAssertions.Equivalency.Specs/MemberConversionSpecs.cs, docs/_pages/releases.md
Fixes #2011 
There's not really a way for ChangeType to handle this case so it is handled specifically.
=> Add support to convert into to enum

Src/FluentAssertions/Primitives/NullableDateOnlyAssertions.cs, Src/FluentAssertions/Primitives/NullableDateTimeAssertions.cs, Src/FluentAssertions/Primitives/NullableTimeOnlyAssertions.cs
=> Fix xml docs for time-related assertions

docs/run.bat
=> Ensure running the site works again

docs/_pages/numerictypes.md
=> Fix example wording

.github/workflows/code_quality.yml, qodana.yaml
Setup:
- Create an organization, team, and project on https://qodana.cloud/ (enable _Make the organization public_)
- Copy token and add [here](https://github.com/fluentassertions/fluentassertions/settings/secrets/actions) as `QODANA_TOKEN`
=> Add Qodana

docs/_pages/xml.md
Seems that I have forgotten these two lines in my PR #1880
=> Add missing `HaveElement()` occurrence docs

Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs, Tests/FluentAssertions.Specs/Execution/AssertionScope.MessageFormatingSpecs.cs, Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
=> Fix qodana issues 3

docs/index.html
I think this should be the correct link?
=> Fix sponsors link

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_api_proposal.yml, .github/ISSUE_TEMPLATE/03_general_feature.yml
The original approach looked promising on the first sight, but is not really helpful in real life. 
What should we do, if an author marks "Yes, I can help", but afterwards nothing more? Should we wait? And how long this should take?
So I tweaked them a little bit, to make it more explicit what e.g. a "yes" is causing.
| Before | After |
|--------|--------|
| <img width="568" alt="image" src="https://github.com/fluentassertions/fluentassertions/assets/49762557/5dfb8f0a-6fd8-490f-861e-012a11cdfffa"> | <img width="486" alt="image" src="https://github.com/fluentassertions/fluentassertions/assets/49762557/d10fda7e-203b-4c5f-af8b-9f8965b8b8cf"> |
=> Optimize the PR-help-options in issue templates

cSpell.json, docs/_data/navigation.yml, docs/_pages/fsharp.md
=> Add F# usage docs

Tests/Benchmarks/Benchmarks.csproj
=> Remove unused System.Collections dependency from benchmarks

.github/dependabot.yml
According to [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) 'npm' should also be used for yarn.
=> Use 'npm' for yarn packages.

.github/workflows/code_quality.yml
=> Checkout the merge commit for Qodana to generate correct results

qodana.yaml
See latest Qodana scan: https://qodana.cloud/projects/AgRgk/reports/QLJY9
As we grow in code-quality the Qodana `failThreshold` have to decrease :)
=> Decrease the Qodana `failThreshold`

Src/FluentAssertions/Common/StopwatchTimer.cs, Src/FluentAssertions/EquivalencyPlan.cs
=> Replace constructor with members initialized inline

Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
=> Switch to preferred syntax style

docs/_pages/releases.md
=> Add release notes for #2393

Directory.Build.props, Src/FluentAssertions/Common/StringExtensions.cs, Src/FluentAssertions/Common/TypeMemberReflector.cs, Src/FluentAssertions/Specialized/ExceptionAssertions.cs, Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.NotContainItemsAssignableTo.cs, qodana.yaml
=> Fix qodana issues

docs/_data/tips/datetimes.yml
=> Added more date/time tips

qodana.yaml
Actually I don't know if `protected` would satisfy the qodana rule..
Let's try...
=> Correct Qodana `failThreshold`

FluentAssertions.sln
With each change it is necessary to also update the `docs/_pages/releases.md` file.
I added it to the solution items, so that it can be updated directly from within the IDE.
=> Add `releases.md` to solution items

README.md
Because we test against .NET8 VS 17.0 is obviously not enough anymore.
This also applies to just load the solution. Since #2466 was merged (which bumped the SDK to 8.0.100), you cannot load FluentAssertions solution anymore. Installing .NET8 SDK does not help either, because it then complains about "MSBuild is not compatible with .NET8".
After upgrading to VS 17.8+ I now can load FA again
=> Update the required minimum VS version

Build/_build.csproj
=> ReportGenerator 5.1.23 -> 5.2.0

Build/Build.cs
=> Ignore `yarn install` errors

docs/_pages/releases.md
=> Update release notes WRT recent BeEmpty improvements

Build/CustomNpmTasks.cs
See: https://github.com/fluentassertions/fluentassertions/pull/2545#pullrequestreview-1821312793
=> Disable `npm` update notification

Build/CustomNpmTasks.cs, Build/_build.csproj
=> Bump nuke and build project to 8.0

Src/FluentAssertions/Execution/Continuation.cs, Src/FluentAssertions/Execution/ContinuationOfGiven.cs
Correct spelling in 'Then' property summary xml documentation.
=> Correct spelling in 'Then' property summary xml documentation.

Src/FluentAssertions/FluentAssertions.csproj, Tests/FluentAssertions.Extensibility.Specs/FluentAssertions.Extensibility.Specs.csproj, Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj, docs/_pages/releases.md
Fixes https://github.com/fluentassertions/fluentassertions/issues/2668
Update the ConfigurationManager dependency to 6.0.1 and System.Threading.Tasks.Extensions to 4.5.4.
=> Update FluentAssertions package dependencies

Tests/Benchmarks/Benchmarks.csproj, Tests/Benchmarks/Program.cs
=> Fix building Benchmark project

cSpell.json, docs/_data/navigation.yml, docs/_includes/head/custom.html, docs/_layouts/single.html, docs/_pages/extensibility.md, docs/_pages/fsharp.md
Upmerge the documentation changes that happened on `master` to `develop`
=> Upmerge from master

docs/Gemfile.lock
=> update ruby dependencies

.github/workflows/build.yml, Build/Build.cs
=> Better test reporting

.nuke/build.schema.json, Build/Build.cs, FluentAssertions.sln, Src/FluentAssertions/Execution/LoadableTestFramework.cs, Src/FluentAssertions/Execution/TUnitFramework.cs, Src/FluentAssertions/Execution/TestFrameworkProvider.cs, Src/FluentAssertions/Execution/XUnit2TestFramework.cs, Src/FluentAssertions/FluentAssertions.csproj, Tests/TestFrameworks/TUnit.Specs/FrameworkSpecs.cs, Tests/TestFrameworks/TUnit.Specs/TUnit.Specs.csproj, docs/_pages/about.md, docs/_pages/introduction.md, docs/_pages/releases.md, docs/index.html
=> TUnit Framework Support

.github/workflows/code_quality.yml
Backport the Qodana settings from `develop`
=> Use the same Qodana build pipeline as develop is using

docs/_includes/nav_list, docs/_sass/minimal-mistakes/_navigation.scss
=> Add section highlighting for better navigation

docs/_config.yml, docs/_includes/editlink.html
=> Missed two more references to master

Src/FluentAssertions/Equivalency/EquivalencyValidator.cs, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt, Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt, docs/_pages/releases.md
=> Made the equivalency validator core internal

Build/Build.cs, Build/CustomNpmTasks.cs, Build/_build.csproj, global.json
Fixed some of the breaking changes.
=> Bumped Nuke to v9

Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
=> Suppress Qodana warnings about awaiting a void method.

Tests/UWP.Specs/UWP.Specs.csproj
https://github.com/microsoft/testfx/issues/4371 was resolved in MSTest 3.7.0
=> Update MSTest for UWP

docs/_pages/collections.md
=> Add missing semicolon

docs/_pages/enums.md
=> Add missing semicolons

docs/_pages/enums.md
=> Update enums.md to fix typo

README.md, Src/FluentAssertions/FluentAssertions.csproj, docs/_includes/head.html, docs/_includes/head/custom.html, docs/_includes/scripts.html, docs/_pages/releases.md, docs/_sass/minimal-mistakes/_archive.scss, docs/_sass/minimal-mistakes/_base.scss, docs/_sass/minimal-mistakes/_buttons.scss, docs/_sass/minimal-mistakes/_masthead.scss, docs/_sass/minimal-mistakes/_navigation.scss, docs/_sass/minimal-mistakes/_page.scss, docs/_sass/minimal-mistakes/_utilities.scss, docs/_sass/minimal-mistakes/_variables.scss, docs/index.html
=> Various textual and styling fixes as well as some clarification of v7 and v8.

Build/_build.csproj, Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj, Tests/FluentAssertions.Extensibility.Specs/FluentAssertions.Extensibility.Specs.csproj, Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
=> Adjust dependencies

Src/FluentAssertions/Equivalency/EquivalencyValidationContext.cs, Src/FluentAssertions/Equivalency/EquivalencyValidator.cs, Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyOptions.cs, Src/FluentAssertions/Equivalency/Tracing/InternalTraceWriter.cs, Tests/FluentAssertions.Equivalency.Specs/TracingSpecs.cs, docs/_pages/releases.md
=> Ensured WithTracing is safe when used with BeEquivalentTo globally

Src/FluentAssertions/FluentAssertions.csproj
not required since sdk 8
https://github.com/dotnet/sourcelink?tab=readme-ov-file#using-source-link-in-net-projects
The contributor waives any moral rights in the contribution to the extent permitted by law and agrees not to assert any claim of authorship or control over the contribution. The contributor represents that they are the sole author of the contribution and that it is provided free of any third-party claims.
The contributor understands and …
=> remove Microsoft.SourceLink.GitHub

Build/_build.csproj, Directory.Build.props, Tests/Approval.Tests/Approval.Tests.csproj, Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj, Tests/TestFrameworks/TUnit.Specs/TUnit.Specs.csproj, Tests/TestFrameworks/XUnit3.Specs/XUnit3.Specs.csproj, Tests/TestFrameworks/XUnit3Core.Specs/XUnit3Core.Specs.csproj, Tests/UWP.Specs/UWP.Specs.csproj
The contributor waives any moral rights in the contribution to the extent permitted by law and agrees not to assert any claim of authorship or control over the contribution. The contributor represents that they are the sole author of the contribution and that it is provided free of any third-party claims.
The contributor understands and agrees that the maintainers may, at their sole discretion, use, license, or redistribute the contribution as part of any …
=> Update nuget packages

Build/Build.cs, Build/packages.lock.json, Directory.Build.props, Src/FluentAssertions/packages.lock.json, Tests/Approval.Tests/packages.lock.json, Tests/AssemblyA/packages.lock.json, Tests/AssemblyB/packages.lock.json, Tests/Benchmarks/packages.lock.json, Tests/ExampleExtensions/packages.lock.json, Tests/FSharp.Specs/FSharp.Specs.fsproj, Tests/FSharp.Specs/packages.lock.json, Tests/FluentAssertions.Equivalency.Specs/packages.lock.json, Tests/FluentAssertions.Extensibility.Specs/packages.lock.json, Tests/FluentAssertions.Specs/packages.lock.json, Tests/TestFrameworks/MSTestV2.Specs/packages.lock.json, Tests/TestFrameworks/MSpec.Specs/packages.lock.json, Tests/TestFrameworks/NUnit3.Specs/packages.lock.json, Tests/TestFrameworks/NUnit4.Specs/packages.lock.json, Tests/TestFrameworks/TUnit.Specs/packages.lock.json, Tests/TestFrameworks/XUnit2.Specs/packages.lock.json, Tests/TestFrameworks/XUnit3.Specs/packages.lock.json, Tests/TestFrameworks/XUnit3Core.Specs/packages.lock.json, Tests/VB.Specs/packages.lock.json
This PR adds a lock file and enforces it to be used when restoring nuget packages in a CI pipeline.
This gives more visibility about what packages change when a package reference is changed.
https://devblogs.microsoft.com/dotnet/enable-repeatable-package-restores-using-a-lock-file/
The contributor waives any moral rights in the contribution to the extent permitted by law and agrees not to assert any claim of authorship or control over the contribution. …
=> Add lock file for nuget packages
